import { AbsoluteFill } from "remotion";
import { brand, radius, type } from "../design/tokens";
import { CameraMove, Reveal } from "../motion/primitives";

const metric = (label: string, value: string, note: string) => <article style={{ padding: 24, border: "1px solid #dce5dc", borderRadius: radius.small, background: "#fff" }}><small style={{ color: brand.muted, fontFamily: type.sans, fontSize: 12, fontWeight: 800, letterSpacing: ".1em", textTransform: "uppercase" }}>{label}</small><strong style={{ display: "block", marginTop: 11, fontFamily: type.display, fontSize: 38, fontWeight: 500, letterSpacing: "-.04em" }}>{value}</strong><span style={{ display: "block", marginTop: 6, color: "#5d9874", fontFamily: type.sans, fontSize: 13 }}>{note}</span></article>;
export const Intelligence = () => <AbsoluteFill style={{ overflow: "hidden", color: brand.ink, background: brand.deep }}>
  <div style={{ position: "absolute", top: 116, left: 155, zIndex: 2, color: brand.white }}><Reveal at={8}><div style={{ color: "#f3c8aa", fontFamily: type.sans, fontSize: 16, fontWeight: 850, letterSpacing: ".15em", textTransform: "uppercase" }}>Performance + learning</div></Reveal><Reveal at={27}><h2 style={{ margin: "17px 0 0", fontFamily: type.display, fontSize: 71, fontWeight: 500, letterSpacing: "-.06em" }}>Know what’s driving growth.</h2></Reveal></div>
  <CameraMove from={.96} to={1} start={0} end={220}><Reveal at={56} duration={28} y={25}><div style={{ position: "absolute", top: 315, right: 150, left: 150, padding: 38, borderRadius: radius.card, background: "#f7f9f5", boxShadow: "0 32px 90px rgba(0,0,0,.28)" }}><div style={{ display: "flex", alignItems: "baseline", justifyContent: "space-between" }}><div><div style={{ color: brand.clay, fontFamily: type.sans, fontSize: 13, fontWeight: 850, letterSpacing: ".13em", textTransform: "uppercase" }}>Growth signals</div><h3 style={{ margin: "10px 0 0", fontFamily: type.display, fontSize: 42, fontWeight: 500, letterSpacing: "-.045em" }}>The relationship behind the result.</h3></div><span style={{ padding: "10px 14px", borderRadius: 999, color: "#486e5d", background: brand.greenSoft, fontFamily: type.sans, fontSize: 13, fontWeight: 800 }}>Last 30 days</span></div><div style={{ display: "grid", gridTemplateColumns: "repeat(4, 1fr)", gap: 16, marginTop: 30 }}>{metric("Revenue", "$48,240", "+18.4%")}{metric("Returning customers", "38%", "+6.1 pts")}{metric("Campaign response", "12.8%", "Above baseline")}{metric("Follow-up ready", "27", "For your review")}</div><div style={{ display: "grid", gridTemplateColumns: "1.4fr .9fr", gap: 18, marginTop: 18 }}><div style={{ height: 178, padding: 24, border: "1px solid #dce5dc", borderRadius: radius.small, background: "#fff" }}><div style={{ color: brand.muted, fontFamily: type.sans, fontSize: 13, fontWeight: 800 }}>Campaign → customers → repeat orders</div><svg viewBox="0 0 620 110" style={{ width: "100%", height: 120, marginTop: 9 }}><path d="M0 89 C90 83 115 44 200 57 S300 98 370 53 S492 36 620 10" fill="none" stroke={brand.clay} strokeWidth="4" strokeLinecap="round" /><path d="M0 104 L620 104" stroke="#e7ddcf" /></svg></div><div style={{ padding: 24, borderRadius: radius.small, color: "#fff", background: brand.ink }}><small style={{ fontFamily: type.sans, color: "#f3c8aa", fontSize: 12, fontWeight: 850, letterSpacing: ".1em" }}>WHAT NEXT?</small><p style={{ margin: "13px 0 0", fontFamily: type.display, fontSize: 28, lineHeight: 1.1 }}>Follow up while the first purchase is still fresh.</p></div></div></div></Reveal></CameraMove>
</AbsoluteFill>;
