<x-layouts::app.sidebar title="Service Plans & Customer Hub">
    <flux:main>
        <div class="fb-workflow-shell space-y-6">
            <header class="border-b border-zinc-200 pb-5">
                <div class="fb-eyebrow">{{ $tenant->name }} · Field service</div>
                <div class="mt-2 flex flex-wrap items-end justify-between gap-4">
                    <div><h1 class="text-3xl font-semibold text-zinc-950">Service Plans & Customer Hub</h1><p class="mt-2 max-w-3xl text-sm text-zinc-600">Create a polished maintenance experience: clear plans, customer-safe photos, approved add-ons, secure acceptance, and recurring service work. Everbranch never stores a customer card in this workflow.</p></div>
                    <a href="{{ route('field-service.calendar') }}" class="fb-btn fb-btn-secondary">Open work calendar</a>
                </div>
            </header>

            @if(session('status'))<div class="fb-state fb-state-success break-words">{{ session('status') }}</div>@endif
            @if($errors->any())<div class="fb-state border-rose-200 bg-rose-50 text-rose-900"><strong>Review the highlighted fields.</strong><ul class="mt-2 list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

            <section class="grid gap-3 md:grid-cols-2 xl:grid-cols-3" aria-label="Service plan setup steps">
                @foreach([['1','Business defaults','Service area, terms contact, and customer copy.'],['2','Plan cards','Good / Better / Best plan pricing and benefits.'],['3','Benefits and limits','Visits, priority, terms, and renewal cadence.'],['4','Customer add-ons','Fixed-price upgrades with no surprise totals.'],['5','Photos and portal','Choose tenant-owned images and preview the customer offer.'],['6','Test and launch','Create an offer, record acceptance, then manually activate after external payment.']] as [$number,$title,$copy])
                    <article class="rounded-xl border border-zinc-200 bg-white p-4"><div class="text-xs font-bold text-emerald-700">STEP {{ $number }}</div><h2 class="mt-1 font-semibold text-zinc-950">{{ $title }}</h2><p class="mt-1 text-sm text-zinc-600">{{ $copy }}</p></article>
                @endforeach
            </section>

            @if($canConfigure)
            <section class="fb-panel">
                <div class="fb-panel-head"><div><div class="fb-panel-title">1. Business defaults and customer controls</div><div class="fb-panel-copy">Terms and customer-facing details are captured before a plan can be offered.</div></div></div>
                <div class="fb-panel-body"><form method="POST" action="{{ route('service-memberships.settings.update') }}" class="grid gap-4 md:grid-cols-2">@csrf @method('PUT')
                    <label class="text-sm font-semibold">Terms contact email<input type="email" name="terms_contact_email" value="{{ old('terms_contact_email', $settings->terms_contact_email) }}" class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Terms contact phone<input name="terms_contact_phone" value="{{ old('terms_contact_phone', $settings->terms_contact_phone) }}" class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Service-area label<input name="service_area_label" value="{{ old('service_area_label', $settings->service_area_label) }}" placeholder="Greater Raleigh service area" class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Offer expires after (days)<input type="number" min="1" max="90" name="offer_expiry_days" value="{{ old('offer_expiry_days', data_get($settings->customer_experience, 'offer_expiry_days', 14)) }}" class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold md:col-span-2">Customer terms<textarea name="terms" rows="4" class="mt-1 w-full rounded-lg border-zinc-300" placeholder="Describe renewal, included visits, cancellation, and invoice terms.">{{ old('terms', data_get($settings->customer_experience, 'terms')) }}</textarea></label>
                    <label class="text-sm font-semibold md:col-span-2">Customer confirmation copy<textarea name="customer_email_copy" rows="2" class="mt-1 w-full rounded-lg border-zinc-300" placeholder="What happens after the customer accepts?">{{ old('customer_email_copy', data_get($settings->customer_experience, 'customer_email_copy')) }}</textarea></label>
                    <div class="md:col-span-2"><button class="fb-btn fb-btn-primary">Save customer controls</button></div>
                </form></div>
            </section>

            <section class="fb-panel">
                <div class="fb-panel-head"><div><div class="fb-panel-title">2–5. Create a customer-ready service plan</div><div class="fb-panel-copy">Publishing saves an immutable version. Add-ons and photos are copied into every customer offer snapshot.</div></div></div>
                <div class="fb-panel-body"><form method="POST" action="{{ route('service-memberships.plans.store') }}" class="grid gap-4 lg:grid-cols-3">@csrf
                    <label class="text-sm font-semibold">Plan name<input name="name" required placeholder="Complete Care" class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Plan badge<input name="badge" placeholder="Most popular" class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Display order<input type="number" name="sort_order" value="0" min="0" class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Price<input type="number" name="price" step="0.01" min="0" required class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Billing frequency<select name="billing_frequency" class="mt-1 w-full rounded-lg border-zinc-300"><option value="annual">Annual</option><option value="monthly">Monthly</option></select></label>
                    <label class="text-sm font-semibold">Visit cadence (days)<input type="number" name="visit_interval_days" value="365" min="1" max="730" required class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Generated visit title<input name="visit_title" value="Membership service visit" required class="mt-1 w-full rounded-lg border-zinc-300"></label>
                    <label class="text-sm font-semibold">Service priority<select name="priority" class="mt-1 w-full rounded-lg border-zinc-300"><option value="normal">Standard</option><option value="priority">Priority scheduling</option></select></label>
                    <label class="text-sm font-semibold lg:col-span-3">Plan description<textarea name="description" rows="2" class="mt-1 w-full rounded-lg border-zinc-300" placeholder="Describe the outcome, not just the list of tasks."></textarea></label>
                    <label class="text-sm font-semibold lg:col-span-2">Benefits — one per line<textarea name="benefits" rows="5" class="mt-1 w-full rounded-lg border-zinc-300" placeholder="Annual safety inspection&#10;Priority scheduling&#10;10% off repairs"></textarea></label>
                    <label class="text-sm font-semibold">Plan-specific terms<textarea name="terms" rows="5" class="mt-1 w-full rounded-lg border-zinc-300" placeholder="Included-visit and renewal details"></textarea></label>
                    <fieldset class="rounded-xl border border-zinc-200 p-4 lg:col-span-3"><legend class="px-1 text-sm font-semibold">Optional customer add-on</legend><div class="grid gap-3 md:grid-cols-4"><label class="text-sm">Name<input name="addons[0][name]" placeholder="Surge protection" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm">Price<input type="number" step="0.01" min="0" name="addons[0][price]" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm">Frequency<select name="addons[0][billing_frequency]" class="mt-1 w-full rounded-lg border-zinc-300"><option value="one_time">One time</option><option value="annual">Annual</option><option value="monthly">Monthly</option></select></label><label class="text-sm">Maximum quantity<input type="number" name="addons[0][max_quantity]" min="1" max="99" value="1" class="mt-1 w-full rounded-lg border-zinc-300"></label></div><label class="mt-3 block text-sm">Description<input name="addons[0][description]" class="mt-1 w-full rounded-lg border-zinc-300"></label></fieldset>
                    <fieldset class="rounded-xl border border-zinc-200 p-4 lg:col-span-3"><legend class="px-1 text-sm font-semibold">Customer-offer photo</legend><div class="grid gap-3 md:grid-cols-3"><label class="text-sm">Tenant-owned image<select name="media[0][workspace_asset_id]" class="mt-1 w-full rounded-lg border-zinc-300"><option value="">No photo</option>@foreach($assets as $asset)<option value="{{ $asset->id }}">{{ $asset->file_name }}{{ $asset->caption ? ' — '.$asset->caption : '' }}</option>@endforeach</select></label><label class="text-sm">Caption<input name="media[0][caption]" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm">Accessible alt text<input name="media[0][alt_text]" placeholder="Technician inspecting service panel" class="mt-1 w-full rounded-lg border-zinc-300"></label></div></fieldset>
                    <div class="lg:col-span-3"><button class="fb-btn fb-btn-primary">Publish customer-ready plan</button></div>
                </form></div>
            </section>
            @else
                <section class="fb-state border-amber-200 bg-amber-50 text-amber-950">Plan pricing, terms, add-ons, and media are owner/admin controlled. Managers can create offers, review acceptance, and activate a membership after external payment is verified.</section>
            @endif

            <section class="fb-panel"><div class="fb-panel-head"><div><div class="fb-panel-title">6. Send a secure customer offer</div><div class="fb-panel-copy">Offers use an expiring, single-purpose link. Acceptance does not charge a card or activate the membership automatically.</div></div></div><div class="fb-panel-body"><form method="POST" action="{{ route('service-memberships.offers.store') }}" class="grid gap-3 md:grid-cols-4">@csrf
                <label class="text-sm font-semibold">Customer<select name="marketing_profile_id" required class="mt-1 w-full rounded-lg border-zinc-300"><option value="">Choose customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ trim($customer->first_name.' '.$customer->last_name) ?: $customer->email }}</option>@endforeach</select></label>
                <label class="text-sm font-semibold md:col-span-2">Published plan version<select name="service_plan_version_id" required class="mt-1 w-full rounded-lg border-zinc-300"><option value="">Choose plan</option>@foreach($templates as $template)@foreach($template->versions as $version)<option value="{{ $version->id }}">{{ $template->name }} · v{{ $version->version }}</option>@endforeach@endforeach</select></label>
                <label class="text-sm font-semibold">Expires in days<input name="expires_in_days" type="number" min="1" max="90" value="14" class="mt-1 w-full rounded-lg border-zinc-300"></label><div class="md:col-span-4"><button class="fb-btn fb-btn-primary">Create secure offer link</button></div>
            </form></div></section>

            <section class="grid gap-6 xl:grid-cols-2"><div class="fb-panel"><div class="fb-panel-head"><div><div class="fb-panel-title">Offers awaiting action</div><div class="fb-panel-copy">Manual activation is allowed only after accepted terms and external-payment verification.</div></div></div><div class="fb-panel-body space-y-3">@forelse($offers as $offer)<article class="rounded-xl border border-zinc-200 p-4"><div class="flex flex-wrap justify-between gap-3"><div><div class="font-semibold text-zinc-950">{{ $offer->customer?->first_name }} {{ $offer->customer?->last_name }} · {{ data_get($offer->snapshot, 'template.name', 'Service plan') }}</div><div class="mt-1 text-sm text-zinc-600">{{ ucfirst($offer->status) }} · expires {{ $offer->expires_at?->format('M j, Y') ?? '—' }}</div></div><span class="rounded-full bg-zinc-100 px-3 py-1 text-xs font-semibold">{{ ucfirst($offer->status) }}</span></div>@if($offer->status === 'accepted')<form method="POST" action="{{ route('service-memberships.offers.activate', $offer) }}" class="mt-3 grid gap-2 md:grid-cols-3">@csrf<input name="external_invoice_reference" placeholder="External invoice reference" class="rounded-lg border-zinc-300 text-sm"><input type="url" name="external_invoice_url" placeholder="Optional secure invoice URL" class="rounded-lg border-zinc-300 text-sm"><button class="fb-btn fb-btn-primary">Verify & activate</button></form>@elseif(in_array($offer->status,['sent','draft']))<form method="POST" action="{{ route('service-memberships.offers.revoke', $offer) }}" class="mt-3">@csrf<button class="text-sm font-semibold text-rose-700">Revoke offer</button></form>@endif</article>@empty<p class="text-sm text-zinc-600">No offers yet.</p>@endforelse</div></div>
                <div class="fb-panel"><div class="fb-panel-head"><div><div class="fb-panel-title">Active service memberships</div><div class="fb-panel-copy">The daily generator creates one idempotent job per due visit.</div></div></div><div class="fb-panel-body space-y-3">@forelse($memberships as $membership)<article class="rounded-xl border border-zinc-200 p-4"><div class="font-semibold text-zinc-950">{{ $membership->customer?->first_name }} {{ $membership->customer?->last_name }} · {{ data_get($membership->snapshot, 'template.name', 'Service plan') }}</div><div class="mt-1 text-sm text-zinc-600">Next included visit: {{ $membership->next_visit_due_on?->format('M j, Y') ?? 'Not scheduled' }} · renews {{ $membership->renews_on?->format('M j, Y') ?? '—' }}</div></article>@empty<p class="text-sm text-zinc-600">No active memberships yet.</p>@endforelse</div></div></section>
        </div>
    </flux:main>
</x-layouts::app.sidebar>
