api_version = "2026-04"

[[extensions]]
name = "t:name"
handle = "everbranch-bundle-scent-validation"
type = "function"
uid = "e0517735-8c8d-214c-1960-a343ec3833557bdbf128"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
