<x-app-layout><x-slot name="header"><h1 class="text-xl font-semibold text-zinc-900">Prepare client agreement</h1></x-slot>
<form method="post" action="{{ route('landlord.agreements.store') }}" class="mx-auto max-w-2xl space-y-5 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">@csrf
    <div><h2 class="text-lg font-semibold">Front Yard Foods launch-partner template</h2><p class="mt-1 text-sm text-zinc-600">Creates a tenant-scoped draft. No charge or entitlement is activated.</p></div>
    @if($errors->any())<div class="rounded-lg bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
    <label class="block text-sm font-medium">Workspace<select name="tenant_id" required class="mt-1 block w-full rounded-lg border-zinc-300"><option value="">Select a workspace</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected(old('tenant_id', $selectedTenantId) == $tenant->id)>{{ $tenant->name }}</option>@endforeach</select></label>
    <div class="grid gap-4 sm:grid-cols-3"><label class="text-sm font-medium">Implementation total ($)<input name="implementation_amount" type="number" min="0" step="0.01" value="{{ old('implementation_amount') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label><label class="text-sm font-medium">Due on acceptance ($)<input name="due_on_acceptance" type="number" min="0" step="0.01" value="{{ old('due_on_acceptance') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label><label class="text-sm font-medium">Due before launch ($)<input name="due_before_launch" type="number" min="0" step="0.01" value="{{ old('due_before_launch') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label></div>
    <label class="block text-sm font-medium">Additional agreed scope<textarea name="additional_scope" rows="5" maxlength="20000" placeholder="Add client-specific deliverables or exclusions that are not already in the reusable template." class="mt-1 block w-full rounded-lg border-zinc-300">{{ old('additional_scope') }}</textarea></label>
    <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">The implementation amount is intentionally configurable. Front Yard Foods’ $299 onboarding, $59 × 6 launch price, $149 from cycle 7, and $50/hour written-approval rule remain explicit.</div>
    <div class="flex justify-end gap-3"><a href="{{ route('landlord.agreements.index') }}" class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold">Cancel</a><button class="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Prepare draft</button></div>
</form></x-app-layout>
