<x-app-layout><x-slot name="header"><h1 class="text-xl font-semibold text-zinc-900">Prepare client agreement</h1></x-slot>
<form method="post" action="{{ route('landlord.agreements.store') }}" class="mx-auto max-w-2xl space-y-5 rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm">@csrf
    <div><h2 class="text-lg font-semibold">Launch-partner agreement template</h2><p class="mt-1 text-sm text-zinc-600">Creates a tenant-scoped draft. No charge or entitlement is activated.</p></div>
    @if($errors->any())<div class="rounded-lg bg-red-50 p-3 text-sm text-red-800">{{ $errors->first() }}</div>@endif
    <label class="block text-sm font-medium">Workspace<select name="tenant_id" required class="mt-1 block w-full rounded-lg border-zinc-300"><option value="">Select a workspace</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected(old('tenant_id', $selectedTenantId) == $tenant->id)>{{ $tenant->name }}</option>@endforeach</select></label>
    <label class="block text-sm font-medium">Template<select name="template_key" required class="mt-1 block w-full rounded-lg border-zinc-300"><option value="front_yard_foods_launch_partner">Front Yard Foods — commerce launch</option><option value="collins_electric_launch_partner" @selected(old('template_key')==='collins_electric_launch_partner')>Collins Electric — field operations launch</option></select></label>
    <div class="grid gap-4 sm:grid-cols-3"><label class="text-sm font-medium">Implementation total ($)<input name="implementation_amount" type="number" min="0" step="0.01" value="{{ old('implementation_amount') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label><label class="text-sm font-medium">Due on acceptance ($)<input name="due_on_acceptance" type="number" min="0" step="0.01" value="{{ old('due_on_acceptance') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label><label class="text-sm font-medium">Due before launch ($)<input name="due_before_launch" type="number" min="0" step="0.01" value="{{ old('due_before_launch') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label></div>
    <div class="grid gap-4 sm:grid-cols-3"><label class="text-sm font-medium">Onboarding / completed work ($)<input name="onboarding_amount" type="number" min="0" step="0.01" value="{{ old('onboarding_amount', '299.00') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label><label class="text-sm font-medium">Launch partner monthly ($)<input name="launch_partner_amount" type="number" min="0" step="0.01" value="{{ old('launch_partner_amount', '59.00') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label><label class="text-sm font-medium">Standard monthly ($)<input name="standard_amount" type="number" min="0" step="0.01" value="{{ old('standard_amount', '149.00') }}" class="mt-1 block w-full rounded-lg border-zinc-300"></label></div>
    <label class="block text-sm font-medium">Additional agreed scope<textarea name="additional_scope" rows="5" maxlength="20000" placeholder="Add client-specific deliverables or exclusions that are not already in the reusable template." class="mt-1 block w-full rounded-lg border-zinc-300">{{ old('additional_scope') }}</textarea></label>
    <div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Choose the matching client template. Collins defaults to $299 due on acceptance, $59/month for six cycles, $149/month from cycle seven, and $50/hour only after separate written approval.</div>
    <div class="flex justify-end gap-3"><a href="{{ route('landlord.agreements.index') }}" class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold">Cancel</a><button class="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Prepare draft</button></div>
</form></x-app-layout>
