<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between gap-4"><div><h1 class="text-xl font-semibold text-zinc-900">Agreements</h1><p class="mt-1 text-sm text-zinc-600">Immutable proposals, acceptance evidence, subscription authorization, and termination/export tracking.</p></div><a href="{{ route('landlord.agreements.create') }}" class="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">New agreement</a></div></x-slot>
    <div class="space-y-5">
        @if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('status') }}</div>@endif
        <form class="grid gap-3 rounded-2xl border border-zinc-200 bg-white p-4 sm:grid-cols-3" method="get">
            <select name="tenant_id" class="rounded-lg border-zinc-300 text-sm"><option value="">All workspaces</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected($tenantId === (int) $tenant->id)>{{ $tenant->name }}</option>@endforeach</select>
            <select name="status" class="rounded-lg border-zinc-300 text-sm"><option value="">All statuses</option>@foreach(\App\Models\Agreement::STATUSES as $option)<option value="{{ $option }}" @selected($status === $option)>{{ str_replace('_', ' ', ucfirst($option)) }}</option>@endforeach</select>
            <button class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold">Filter</button>
        </form>
        <div class="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-zinc-200 text-sm"><thead class="bg-zinc-50 text-left text-xs uppercase tracking-wide text-zinc-500"><tr><th class="px-4 py-3">Agreement</th><th class="px-4 py-3">Workspace</th><th class="px-4 py-3">Status</th><th class="px-4 py-3">Version</th><th class="px-4 py-3">Updated</th></tr></thead><tbody class="divide-y divide-zinc-100">@forelse($agreements as $agreement)<tr><td class="px-4 py-4"><a class="font-semibold text-emerald-800 hover:underline" href="{{ route('landlord.agreements.show', $agreement) }}">{{ $agreement->title }}</a></td><td class="px-4 py-4 text-zinc-600">{{ $agreement->tenant->name }}</td><td class="px-4 py-4"><span class="rounded-full bg-zinc-100 px-2.5 py-1 text-xs font-medium">{{ str_replace('_', ' ', $agreement->status) }}</span></td><td class="px-4 py-4 text-zinc-600">{{ $agreement->currentVersion?->version_number ?? '—' }}</td><td class="px-4 py-4 text-zinc-600">{{ $agreement->updated_at?->diffForHumans() }}</td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-zinc-500">No agreements match these filters.</td></tr>@endforelse</tbody></table></div></div>
        {{ $agreements->links() }}
    </div>
</x-app-layout>
