<x-app-layout>
    <x-slot name="header"><div class="flex items-center justify-between gap-4"><div><h1 class="text-xl font-semibold text-zinc-900">Direct invoices</h1><p class="mt-1 text-sm text-zinc-600">Everbranch and Evergrove charges sent through Stripe. Shopify and third-party expenses are excluded.</p></div><a href="{{ route('landlord.agreements.index') }}" class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold">Agreements</a></div></x-slot>
    <div class="space-y-5">
        @if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('status') }}</div>@endif
        @if(session('status_error'))<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">{{ session('status_error') }}</div>@endif
        <form class="grid gap-3 rounded-2xl border border-zinc-200 bg-white p-4 sm:grid-cols-3" method="get">
            <select name="tenant_id" class="rounded-lg border-zinc-300 text-sm"><option value="">All workspaces</option>@foreach($tenants as $tenant)<option value="{{ $tenant->id }}" @selected($tenantId === (int) $tenant->id)>{{ $tenant->name }}</option>@endforeach</select>
            <select name="status" class="rounded-lg border-zinc-300 text-sm"><option value="">All statuses</option>@foreach(\App\Models\TenantDirectInvoice::STATUSES as $option)<option value="{{ $option }}" @selected($status === $option)>{{ str_replace('_', ' ', ucfirst($option)) }}</option>@endforeach</select>
            <button class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold">Filter</button>
        </form>
        @if($tenantId)<div class="flex justify-end"><a href="{{ route('landlord.invoices.create', $tenantId) }}" class="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">New invoice</a></div>@else<div class="rounded-xl border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900">Select a workspace above, then filter, to create an invoice for that customer.</div>@endif
        <div class="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full divide-y divide-zinc-200 text-sm"><thead class="bg-zinc-50 text-left text-xs uppercase tracking-wide text-zinc-500"><tr><th class="px-4 py-3">Invoice</th><th class="px-4 py-3">Workspace</th><th class="px-4 py-3">Customer</th><th class="px-4 py-3">Total</th><th class="px-4 py-3">Status</th></tr></thead><tbody class="divide-y divide-zinc-100">@forelse($invoices as $invoice)<tr><td class="px-4 py-4"><a class="font-semibold text-emerald-800 hover:underline" href="{{ route('landlord.invoices.show', [$invoice->tenant_id, $invoice]) }}">{{ $invoice->provider_invoice_number ?: 'Draft #'.$invoice->id }}</a></td><td class="px-4 py-4 text-zinc-600">{{ $invoice->tenant->name }}</td><td class="px-4 py-4"><div>{{ $invoice->customer_name }}</div><div class="text-zinc-500">{{ $invoice->customer_email }}</div>@if($invoice->customer_phone)<div class="text-zinc-500">••• {{ substr($invoice->customer_phone, -4) }}</div>@endif</td><td class="px-4 py-4">${{ number_format(($invoice->provider_total_cents ?: $invoice->authorized_subtotal_cents) / 100, 2) }}</td><td class="px-4 py-4">{{ str_replace('_', ' ', ucfirst($invoice->status)) }}</td></tr>@empty<tr><td colspan="5" class="px-4 py-10 text-center text-zinc-500">No direct invoices match these filters.</td></tr>@endforelse</tbody></table></div></div>
        {{ $invoices->links() }}
    </div>
</x-app-layout>
