@php
    $positiveSubtotalCents = (int) collect($invoice->line_items)->sum(fn ($line) => max(0, (int) ($line['amount_cents'] ?? 0)));
    $discountCents = abs((int) collect($invoice->line_items)->sum(fn ($line) => min(0, (int) ($line['amount_cents'] ?? 0))));
@endphp
<x-app-layout><x-slot name="header"><div class="flex items-center justify-between"><div><h1 class="text-xl font-semibold text-zinc-900">{{ $invoice->provider_invoice_number ?: 'Invoice draft #'.$invoice->id }}</h1><p class="mt-1 text-sm text-zinc-600">{{ $tenant->name }} · {{ str_replace('_', ' ', ucfirst($invoice->status)) }}</p></div><a href="{{ route('landlord.invoices.index', ['tenant_id' => $tenant->id]) }}" class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold">All invoices</a></div></x-slot>
<div class="mx-auto max-w-4xl space-y-5">
    @if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('status') }}</div>@endif @if(session('status_error'))<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">{{ session('status_error') }}</div>@endif
    <section class="rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><div class="grid gap-4 sm:grid-cols-3"><div><div class="text-xs uppercase text-zinc-500">Customer</div><div class="mt-1 font-semibold">{{ $invoice->customer_name }}</div><div class="text-sm text-zinc-600">{{ $invoice->customer_email }}</div></div><div><div class="text-xs uppercase text-zinc-500">Due</div><div class="mt-1 font-semibold">{{ $invoice->days_until_due }} days after send</div><div class="text-sm text-zinc-600">{{ $invoice->authorization_reference }}</div></div><div><div class="text-xs uppercase text-zinc-500">Total</div>@if($discountCents > 0)<div class="mt-1 text-sm text-zinc-500 line-through">${{ number_format($positiveSubtotalCents / 100, 2) }}</div><div class="text-2xl font-semibold">${{ number_format(($invoice->provider_total_cents ?: $invoice->authorized_subtotal_cents) / 100, 2) }}</div><div class="text-sm font-medium text-emerald-700">Discount −${{ number_format($discountCents / 100, 2) }}</div>@else<div class="mt-1 text-2xl font-semibold">${{ number_format(($invoice->provider_total_cents ?: $invoice->authorized_subtotal_cents) / 100, 2) }}</div>@endif @if($invoice->provider_tax_cents)<div class="text-sm text-zinc-600">Includes ${{ number_format($invoice->provider_tax_cents / 100, 2) }} Stripe-confirmed tax</div>@endif</div></div></section>
    <section class="overflow-hidden rounded-2xl border border-zinc-200 bg-white"><table class="min-w-full divide-y divide-zinc-200 text-sm"><thead class="bg-zinc-50 text-left text-xs uppercase text-zinc-500"><tr><th class="px-4 py-3">Description</th><th class="px-4 py-3">Category</th><th class="px-4 py-3 text-right">Amount</th></tr></thead><tbody class="divide-y divide-zinc-100">@foreach($invoice->line_items as $line)@php($isDiscount = ($line['category'] ?? null) === 'discount' || (int) ($line['amount_cents'] ?? 0) < 0)<tr><td class="px-4 py-4 {{ $isDiscount ? 'text-emerald-800' : '' }}">{{ $line['description'] }} @if(($line['quantity'] ?? 1) > 1)<span class="text-zinc-500">× {{ $line['quantity'] }}</span>@endif @if(!$isDiscount && ($line['quantity'] ?? 1) > 1 && isset($line['unit_amount_cents']))<span class="text-zinc-500">at ${{ number_format($line['unit_amount_cents'] / 100, 2) }}</span>@endif</td><td class="px-4 py-4 {{ $isDiscount ? 'font-medium text-emerald-700' : 'text-zinc-600' }}">{{ str_replace('_', ' ', $line['category']) }}</td><td class="px-4 py-4 text-right font-medium {{ $isDiscount ? 'text-emerald-700' : '' }}">{{ $isDiscount ? '−' : '' }}${{ number_format(abs((int) $line['amount_cents']) / 100, 2) }}</td></tr>@endforeach</tbody></table></section>
    <section class="rounded-2xl border border-zinc-200 bg-white p-5"><h2 class="font-semibold">Payment and receipt</h2><div class="mt-3 flex flex-wrap gap-3">@if($invoice->hosted_invoice_url)<a href="{{ $invoice->hosted_invoice_url }}" target="_blank" rel="noopener noreferrer" class="rounded-lg bg-emerald-700 px-4 py-2 text-sm font-semibold text-white">Open Stripe invoice</a>@endif @if($invoice->invoice_pdf_url)<a href="{{ $invoice->invoice_pdf_url }}" target="_blank" rel="noopener noreferrer" class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold">Invoice PDF</a>@endif</div><p class="mt-3 text-sm text-zinc-600">Stripe is the payment authority. ACH remains unpaid until Stripe confirms settlement. This invoice never changes Everbranch module access.</p></section>
    <div class="flex flex-wrap justify-end gap-3">@if($invoice->isEditable())<a href="{{ route('landlord.invoices.edit', [$tenant, $invoice]) }}" class="rounded-lg border border-zinc-300 px-4 py-2 text-sm font-semibold">Edit draft</a><form method="post" action="{{ route('landlord.invoices.send', [$tenant, $invoice]) }}">@csrf<button class="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white" @disabled(!$stripeAvailable)>Send with Stripe</button></form>@elseif($invoice->status === 'send_failed')<form method="post" action="{{ route('landlord.invoices.send', [$tenant, $invoice]) }}">@csrf<button class="rounded-lg bg-zinc-950 px-4 py-2 text-sm font-semibold text-white" @disabled(!$stripeAvailable)>Retry Stripe send</button></form>@endif @if(in_array($invoice->status, ['open','payment_failed','uncollectible'], true))<form method="post" action="{{ route('landlord.invoices.void', [$tenant, $invoice]) }}">@csrf<button class="rounded-lg border border-red-300 px-4 py-2 text-sm font-semibold text-red-700">Void invoice</button></form>@endif</div>
    @unless($stripeAvailable)<div class="rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Stripe invoice sending is disabled or this workspace is not allowlisted. The draft is safe and no customer has been charged.</div>@endunless
</div></x-app-layout>
