<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>{{ $agreement->title }}</title>@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body class="min-h-screen bg-zinc-100 text-zinc-900">
<header class="border-b border-zinc-200 bg-white"><div class="mx-auto flex max-w-6xl items-center justify-between px-4 py-4 sm:px-6"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-700">Evergrove Software</p><p class="font-semibold">Secure proposal</p></div><div class="text-right text-xs text-zinc-500"><p>{{ $agreement->tenant->name }}</p><p>Version {{ $agreement->currentVersion?->version_number }} · {{ strtoupper(substr((string) $agreement->currentVersion?->content_hash, 0, 12)) }}</p></div></div></header>
<main class="mx-auto max-w-6xl px-4 py-8 sm:px-6">
    @if(session('status'))<div class="mb-6 rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{{ session('status') }}</div>@endif
    @if(session('status_error'))<div class="mb-6 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-900">{{ session('status_error') }}</div>@endif
    @if(!$unlocked)
        <section class="mx-auto mt-12 max-w-md rounded-2xl border border-zinc-200 bg-white p-6 shadow-sm"><h1 class="text-2xl font-semibold">Open secure proposal</h1><p class="mt-2 text-sm leading-6 text-zinc-600">Enter the password Evergrove shared with you. Failed attempts are rate-limited and recorded without storing the password.</p><form method="post" action="{{ route('proposals.unlock', ['token' => $token]) }}" class="mt-6 space-y-4">@csrf<label class="block text-sm font-medium">Proposal password<input name="password" type="password" required autocomplete="current-password" class="mt-1 block w-full rounded-lg border-zinc-300"></label>@error('password')<p class="text-sm text-red-700">{{ $message }}</p>@enderror<button class="w-full rounded-lg bg-zinc-950 px-4 py-3 font-semibold text-white">View proposal</button></form></section>
    @else
        <section class="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-8">{!! $agreement->currentVersion->rendered_content !!}</section>
        @if($agreement->acceptance)
            <section class="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-6"><h2 class="text-xl font-semibold text-emerald-950">Accepted and locked</h2><p class="mt-2 text-sm text-emerald-900">Accepted {{ $agreement->acceptance->accepted_at->toDayDateTimeString() }}. This exact version is read-only.</p><a class="mt-4 inline-flex rounded-lg bg-emerald-800 px-4 py-2 font-semibold text-white" href="{{ route('proposals.download', ['token' => $token]) }}">Download permanent agreement copy</a></section>
            @if($billingOrder)
                @php
                    $payableLines = collect((array) $billingOrder->line_items)->whereIn('payment_timing', ['due_on_acceptance', 'recurring_current']);
                    $futureLines = collect((array) $billingOrder->line_items)->where('payment_timing', 'recurring_future');
                @endphp
                <section class="mt-6 rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-8"><div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-700">Secure Stripe payment</p><h2 class="mt-1 text-2xl font-semibold">Locked payment summary</h2><p class="mt-2 text-sm text-zinc-600">Amounts come from the accepted agreement. Shopify and third-party provider expenses are not included.</p></div><span class="rounded-full bg-zinc-100 px-3 py-1 text-sm font-medium">{{ str_replace('_', ' ', $billingOrder->status) }}</span></div>
                    <div class="mt-6 divide-y divide-zinc-100 rounded-2xl border border-zinc-200">@foreach($payableLines as $line)<div class="flex items-start justify-between gap-4 p-4"><div><p class="font-medium">{{ $line['label'] }}</p><p class="mt-1 text-xs text-zinc-500">{{ str_replace('_', ' ', $line['cost_category']) }} · {{ $line['frequency'] === 'month' ? 'monthly' : 'one time' }}</p></div><p class="font-semibold">${{ number_format($line['amount_cents'] / 100, 2) }}</p></div>@endforeach @foreach($futureLines as $line)<div class="flex items-start justify-between gap-4 bg-zinc-50 p-4"><div><p class="font-medium">{{ $line['label'] }}</p><p class="mt-1 text-xs text-zinc-500">Future recurring phase beginning with cycle {{ $line['starts_cycle'] ?? '' }}</p></div><p class="font-semibold">${{ number_format($line['amount_cents'] / 100, 2) }}/month</p></div>@endforeach</div>
                    @if($billingOrder->status === 'paid')<div class="mt-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">Payment confirmed by Stripe.@if($billingOrder->receipts->first()?->hosted_invoice_url) <a class="font-semibold underline" href="{{ $billingOrder->receipts->first()->hosted_invoice_url }}" target="_blank" rel="noopener noreferrer">Open invoice</a>@endif</div>
                    @elseif($checkoutAvailable && !in_array($billingOrder->status, ['refunded','void']))<form method="post" action="{{ route('proposals.checkout', ['token' => $token]) }}" class="mt-5">@csrf<button class="w-full rounded-xl bg-zinc-950 px-5 py-3 font-semibold text-white">Pay securely with card or bank account</button></form><p class="mt-2 text-center text-xs text-zinc-500">Bank payments remain processing until Stripe confirms settlement.</p>
                    @else<div class="mt-5 rounded-xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950">Live payment is not available yet. No charge has been created.</div>@endif
                </section>
            @endif
        @else
            <section id="acceptance" class="mt-6 rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm sm:p-8"><h2 class="text-2xl font-semibold">Electronic acceptance</h2><p class="mt-2 text-sm leading-6 text-zinc-600">Your signature binds this exact content hash: <span class="font-mono">{{ $agreement->currentVersion->content_hash }}</span></p>
                @if($errors->any())<div class="mt-4 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-800"><ul class="list-disc pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
                <form method="post" action="{{ route('proposals.accept', ['token' => $token]) }}" class="mt-6 space-y-5">@csrf
                    <div class="grid gap-4 md:grid-cols-3"><label class="text-sm font-medium">Full legal name<input name="signer_legal_name" value="{{ old('signer_legal_name') }}" required class="mt-1 block w-full rounded-lg border-zinc-300"></label><label class="text-sm font-medium">Title / authority<input name="signer_title" value="{{ old('signer_title') }}" required class="mt-1 block w-full rounded-lg border-zinc-300"></label><label class="text-sm font-medium">Email<input name="signer_email" type="email" value="{{ old('signer_email') }}" required class="mt-1 block w-full rounded-lg border-zinc-300"></label></div>
                    @php $checks = ['authorized_to_bind' => 'I am authorized to bind '.$agreement->tenant->name.'.', 'accepted_scope' => 'I accept the complete scope and responsibilities.', 'accepted_pricing' => 'I accept every separately stated price and third-party cost.', 'accepted_subscription' => $agreement->agreement_type === 'supplemental_work' ? 'I authorize this separate one-time charge and understand it is not recurring.' : 'I authorize the recurring Everbranch subscription described above.', 'accepted_hourly_rate' => 'I accept the $50/hour rule only after written approval.', 'accepted_termination' => 'I accept the applicable termination and data-export terms.', 'electronic_consent' => 'I consent to electronic records and signatures.']; @endphp
                    <div class="space-y-3">@foreach($checks as $name => $label)<label class="flex gap-3 rounded-xl border border-zinc-200 p-4 text-sm"><input type="checkbox" name="{{ $name }}" value="1" required class="mt-0.5 rounded border-zinc-300 text-emerald-700"><span>{{ $label }}</span></label>@endforeach</div>
                    <label class="block text-sm font-medium">Typed electronic signature<input name="electronic_signature_value" value="{{ old('electronic_signature_value') }}" required placeholder="Type the full legal name exactly" class="mt-1 block w-full rounded-lg border-zinc-300 font-serif text-lg italic"></label>
                    <button class="w-full rounded-xl bg-emerald-800 px-5 py-3 font-semibold text-white hover:bg-emerald-900">Sign and accept this exact agreement</button>
                </form>
            </section>
        @endif
    @endif
</main></body></html>
