<x-shopify-embedded-shell :authorized="$authorized" :shopify-api-key="$shopifyApiKey" :shop-domain="$shopDomain" :host="$host" :store-label="$storeLabel" :headline="$headline" :subheadline="$subheadline" :app-navigation="$appNavigation" :page-subnav="$pageSubnav ?? []" :page-actions="$pageActions">
    @if ($authorized && $prospect)
        @php $fit = (array) $prospect->fit_explanation; @endphp
        <div class="space-y-6">
            <section class="fb-page-surface p-6"><div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_220px]"><div><div class="text-sm text-zinc-600">{{ str_replace('_', ' ', $prospect->primary_category ?: 'category needs review') }} · {{ collect([$prospect->city, $prospect->state])->filter()->join(', ') ?: $prospect->address }}</div><div class="mt-4 flex flex-wrap gap-3 text-sm">@if($prospect->website)<a class="font-semibold underline" href="{{ $prospect->website }}" target="_blank" rel="noopener">Open website</a>@endif @if($prospect->google_maps_url)<a class="font-semibold underline" href="{{ $prospect->google_maps_url }}" target="_blank" rel="noopener">Open Google Maps</a>@endif</div><div class="mt-4 text-sm text-zinc-600">{{ $prospect->phone ?: 'Public phone not returned' }} · {{ $prospect->operational_status ? str_replace('_', ' ', strtolower($prospect->operational_status)) : 'Operating status unknown' }}</div></div><div class="rounded-2xl border border-zinc-200 bg-zinc-50 p-5"><div class="text-xs font-semibold uppercase text-zinc-500">Explainable fit</div><div class="mt-2 text-4xl font-semibold text-zinc-950">{{ $prospect->fit_score }}</div><div class="mt-1 text-sm text-zinc-600">{{ $prospect->fit_confidence }}% evidence confidence</div></div></div></section>
            @if ($prospect->existing_customer_match)<section class="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800">Possible existing wholesale customer match. Review it; the system has not merged or converted this record.</section>@endif
            @if ($prospect->convertedAccount)<section class="rounded-2xl border border-emerald-200 bg-emerald-50 p-5 text-sm text-emerald-900">Converted to canonical wholesale account <strong>{{ $prospect->convertedAccount->company_name }}</strong> on {{ $prospect->converted_at?->format('M j, Y') }}. Research and activities remain attached to this prospect.</section>@endif
            <div class="grid gap-6 lg:grid-cols-3">
                @foreach ([['Positive signals', $fit['positive_signals'] ?? [], 'emerald'], ['Negative signals', $fit['negative_signals'] ?? [], 'rose'], ['Missing information', $fit['missing_information'] ?? [], 'amber']] as [$label, $items, $tone])
                    <section class="fb-page-surface p-5"><h2 class="font-semibold text-zinc-950">{{ $label }}</h2><ul class="mt-4 space-y-3 text-sm text-zinc-700">@forelse($items as $item)<li>{{ $item }}</li>@empty<li>None recorded.</li>@endforelse</ul></section>
                @endforeach
            </div>
            <section class="fb-page-surface overflow-hidden"><div class="border-b border-zinc-200 px-6 py-4"><h2 class="font-semibold text-zinc-950">Source evidence</h2></div>@foreach($prospect->evidence as $evidence)<div class="border-b border-zinc-100 px-6 py-4 last:border-0"><div class="text-xs font-semibold uppercase text-zinc-500">{{ str_replace('_', ' ', $evidence->source_type) }} · observed {{ $evidence->observed_at->format('M j, Y') }}</div><p class="mt-2 text-sm text-zinc-700">{{ $evidence->summary }}</p></div>@endforeach</section>
            <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_420px]">
                <section class="fb-page-surface overflow-hidden"><div class="border-b border-zinc-200 px-6 py-4"><h2 class="font-semibold text-zinc-950">Follow-ups</h2></div>@forelse($prospect->followUps->sortByDesc('created_at') as $followUp)<div class="border-b border-zinc-100 px-6 py-4 last:border-0"><div class="flex justify-between gap-4"><div class="font-semibold text-zinc-950">{{ $followUp->title }}</div><div class="text-xs font-semibold uppercase text-zinc-500">{{ str_replace('_', ' ', $followUp->status) }}</div></div><div class="mt-1 text-sm text-zinc-600">{{ $followUp->due_at ? 'Due '.$followUp->due_at->format('M j, Y g:i A') : 'No due date' }}</div></div>@empty<div class="px-6 py-10 text-sm text-zinc-600">No prospect follow-ups recorded.</div>@endforelse</section>
                @if (filled($contextToken))
                    <form method="POST" action="{{ route('shopify.app.wholesale.prospects.action', ['prospectPublicId' => $prospect->public_id, 'store_key' => 'wholesale'], false) }}" class="fb-page-surface space-y-4 p-5">
                        @csrf
                        <input type="hidden" name="context_token" value="{{ $contextToken }}">
                        <input type="hidden" name="shopify_session_token" value="" data-wholesale-session-token>
                        <h2 class="font-semibold text-zinc-950">Record prospect action</h2>
                        <label class="block"><span class="text-xs font-semibold uppercase text-zinc-500">Action</span><select name="action" class="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5"><option value="qualify">Qualify prospect</option><option value="schedule_follow_up">Schedule follow-up</option><option value="set_priority">Set priority</option><option value="add_note">Add note</option><option value="request_research">Request more research</option><option value="record_call">Record phone call</option><option value="record_contact_attempt">Record contact attempt</option><option value="convert">Convert to wholesale account</option><option value="mark_duplicate">Mark duplicate</option><option value="mark_do_not_contact">Mark do not contact</option><option value="clear_do_not_contact">Clear do not contact</option><option value="reject">Reject prospect</option></select></label>
                        <div class="grid gap-4 sm:grid-cols-2"><label><span class="text-xs font-semibold uppercase text-zinc-500">Priority</span><select name="priority" class="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></label><label><span class="text-xs font-semibold uppercase text-zinc-500">Due date</span><input type="datetime-local" name="due_at" class="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5"></label></div>
                        <label class="block"><span class="text-xs font-semibold uppercase text-zinc-500">Rejection reason</span><input name="rejection_reason" maxlength="255" class="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5"></label>
                        <label class="block"><span class="text-xs font-semibold uppercase text-zinc-500">Note</span><textarea name="note" rows="3" maxlength="3000" class="mt-2 w-full rounded-xl border border-zinc-300 bg-white px-3 py-2.5"></textarea></label>
                        <button class="rounded-full bg-zinc-950 px-4 py-2 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-60" data-wholesale-mutation-button @disabled(! $canManage)>Record action</button>
                        <p class="text-xs text-zinc-500" data-wholesale-verification-help>{{ $canManage ? 'Shopify admin identity verified.' : 'Finishing Shopify admin verification…' }}</p>
                    </form>
                @endif
            </div>
        </div>
    @endif

    @include('shopify.partials.wholesale-embedded-mutation-bootstrap')
</x-shopify-embedded-shell>
