<x-layouts::app.sidebar :title="$tenant->name.' estimator'">
    <div class="mx-auto w-full max-w-[1500px] space-y-6 px-4 py-6 sm:px-6">
        <header class="flex flex-col gap-4 border-b border-zinc-200 pb-5 lg:flex-row lg:items-end lg:justify-between"><div><div class="text-xs font-semibold uppercase text-emerald-800">Estimator Branch · private beta</div><h1 class="mt-2 text-3xl font-semibold">Price from work you have actually invoiced</h1><p class="mt-2 text-sm text-zinc-600">Every suggested price requires owner review. Drafts remain in Everbranch and never write to QuickBooks.</p></div><form method="POST" action="{{ route('estimator.candidates.rebuild', $tenant) }}">@csrf<button class="rounded-lg border border-zinc-300 bg-white px-4 py-2 text-sm font-semibold">Refresh candidates</button></form></header>
        @if(session('status'))<div class="rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-900">{{ session('status') }}</div>@endif

        <section class="grid gap-5 xl:grid-cols-[1fr_1fr]">
            <div class="rounded-lg border border-zinc-200 bg-white p-5"><h2 class="font-semibold">Suggested services</h2><div class="mt-3 max-h-[38rem] divide-y divide-zinc-100 overflow-auto">
                @forelse($candidates as $candidate)
                    <article class="py-3"><div class="flex items-start justify-between gap-3"><div><div class="font-semibold">{{ $candidate->name }}</div><div class="mt-1 text-xs text-zinc-500">{{ $candidate->sample_count }} invoices · {{ $candidate->last_invoiced_at?->format('M j, Y') }} @if($candidate->high_variance) · Wide price range @endif</div><div class="mt-1 text-sm text-zinc-600">Median ${{ number_format((float)$candidate->median_unit_price, 2) }} · ${{ number_format((float)$candidate->minimum_unit_price, 2) }}–${{ number_format((float)$candidate->maximum_unit_price, 2) }}</div></div><span class="rounded bg-zinc-100 px-2 py-1 text-xs font-semibold">{{ ucfirst($candidate->status) }}</span></div>
                        @if($candidate->status !== 'approved')<div class="mt-2 flex flex-wrap gap-2"><form method="POST" action="{{ route('estimator.candidates.approve', [$tenant, $candidate]) }}" class="flex gap-2">@csrf<input type="number" step="0.01" min="0" name="unit_price" value="{{ number_format((float)$candidate->median_unit_price, 2, '.', '') }}" class="w-32 rounded-lg border border-zinc-300 px-2 py-1 text-sm"><button class="rounded-lg bg-emerald-900 px-3 py-1 text-xs font-semibold text-white">Approve price</button></form><form method="POST" action="{{ route('estimator.candidates.archive', [$tenant, $candidate]) }}">@csrf<button class="rounded-lg border border-zinc-300 px-3 py-1 text-xs font-semibold">Archive</button></form></div>@endif
                    </article>
                @empty<div class="py-8 text-sm text-zinc-500">Refresh candidates after invoice lines have been imported.</div>@endforelse
            </div></div>

            <form method="POST" action="{{ route('estimator.store', $tenant) }}" class="rounded-lg border border-zinc-200 bg-white p-5" data-estimate-form>@csrf<h2 class="font-semibold">New estimate draft</h2><div class="mt-4 grid gap-3 sm:grid-cols-2"><label class="text-sm font-semibold">Customer<select name="marketing_profile_id" class="mt-1 w-full rounded-lg border border-zinc-300 px-2 py-2"><option value="">No customer selected</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ trim($customer->first_name.' '.$customer->last_name) ?: $customer->email }}</option>@endforeach</select></label><label class="text-sm font-semibold">Job<select name="field_service_job_id" class="mt-1 w-full rounded-lg border border-zinc-300 px-2 py-2"><option value="">No job selected</option>@foreach($jobs as $job)<option value="{{ $job->id }}">{{ $job->title }}</option>@endforeach</select></label></div><label class="mt-3 block text-sm font-semibold">Title<input name="title" class="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2"></label>
                <div class="mt-4 flex items-center justify-between"><h3 class="text-sm font-semibold">Line items</h3><button type="button" class="rounded-lg border border-zinc-300 px-3 py-1 text-xs font-semibold" data-add-line>Add line</button></div>
                <div class="mt-2 space-y-2" data-lines><div class="grid grid-cols-[1fr_5rem_7rem] gap-2" data-line><input type="hidden" name="lines[0][price_book_item_id]"><input name="lines[0][description]" required placeholder="Description" class="rounded-lg border border-zinc-300 px-2 py-2 text-sm"><input name="lines[0][quantity]" type="number" step="0.01" value="1" min="0.01" class="rounded-lg border border-zinc-300 px-2 py-2 text-sm"><input name="lines[0][unit_price]" type="number" step="0.01" value="0" min="0" class="rounded-lg border border-zinc-300 px-2 py-2 text-sm"></div></div>
                @if($items->isNotEmpty())<div class="mt-3"><div class="text-xs font-semibold uppercase text-zinc-500">Approved price book</div><div class="mt-2 flex flex-wrap gap-2">@foreach($items as $item)<button type="button" class="rounded-lg border border-zinc-300 px-2 py-1 text-xs" data-price-item data-id="{{ $item->id }}" data-description="{{ $item->name }}" data-price="{{ $item->unit_price }}">{{ $item->name }} · ${{ number_format((float)$item->unit_price, 2) }}</button>@endforeach</div></div>@endif
                <label class="mt-3 block text-sm font-semibold">Notes<textarea name="notes" rows="3" class="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2"></textarea></label><button class="mt-4 rounded-lg bg-emerald-900 px-4 py-2 text-sm font-semibold text-white">Create draft</button>
            </form>
        </section>

        <section class="grid gap-5 lg:grid-cols-[0.7fr_1.3fr]">
            <form method="POST" action="{{ route('estimator.items.store', $tenant) }}" class="rounded-lg border border-zinc-200 bg-white p-5">@csrf<h2 class="font-semibold">Add price-book item</h2><label class="mt-3 block text-sm font-semibold">Name<input name="name" required class="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2"></label><label class="mt-3 block text-sm font-semibold">Default price<input name="unit_price" required type="number" min="0" step="0.01" class="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2"></label><label class="mt-3 block text-sm font-semibold">Description<textarea name="description" rows="3" class="mt-1 w-full rounded-lg border border-zinc-300 px-3 py-2"></textarea></label><button class="mt-4 rounded-lg bg-emerald-900 px-4 py-2 text-sm font-semibold text-white">Add item</button></form>
            <div><h2 class="font-semibold">Approved price book</h2><div class="mt-3 space-y-2">@forelse($items as $item)<form method="POST" action="{{ route('estimator.items.update', [$tenant, $item]) }}" class="grid gap-2 rounded-lg border border-zinc-200 bg-white p-3 sm:grid-cols-[1fr_8rem_auto]">@csrf @method('PUT')<input name="name" value="{{ $item->name }}" class="rounded-lg border border-zinc-300 px-2 py-2 text-sm"><input name="unit_price" type="number" min="0" step="0.01" value="{{ number_format((float)$item->unit_price, 2, '.', '') }}" class="rounded-lg border border-zinc-300 px-2 py-2 text-sm"><label class="flex items-center gap-2 text-xs font-semibold"><input type="hidden" name="active" value="0"><input type="checkbox" name="active" value="1" @checked($item->active)> Active</label><input type="hidden" name="description" value="{{ $item->description }}"><button class="rounded-lg border border-zinc-300 px-3 py-2 text-xs font-semibold sm:col-span-3 sm:justify-self-end">Save item</button></form>@empty<div class="rounded-lg border border-dashed border-zinc-300 p-5 text-sm text-zinc-500">No approved items yet.</div>@endforelse</div></div>
        </section>

        <section><h2 class="font-semibold">Estimate drafts</h2><div class="mt-3 divide-y divide-zinc-100 rounded-lg border border-zinc-200 bg-white">@forelse($estimates as $estimate)<a href="{{ route('estimator.show', [$tenant, $estimate]) }}" class="flex items-center justify-between gap-3 p-4"><div><div class="font-semibold">{{ $estimate->estimate_number }} · {{ $estimate->title ?: 'Untitled estimate' }}</div><div class="text-xs text-zinc-500">{{ $estimate->lines_count }} lines · {{ ucfirst($estimate->status) }}</div></div><div class="font-semibold">${{ number_format((float)$estimate->total_amount, 2) }}</div></a>@empty<div class="p-6 text-sm text-zinc-500">No estimate drafts yet.</div>@endforelse</div></section>
    </div>
    <script>
        (() => { const root=document.querySelector('[data-estimate-form]'); if(!root)return; const lines=root.querySelector('[data-lines]'); let index=1; const add=(id='',description='',price='0')=>{const row=document.createElement('div');row.className='grid grid-cols-[1fr_5rem_7rem] gap-2';row.innerHTML=`<input type="hidden" name="lines[${index}][price_book_item_id]"><input name="lines[${index}][description]" required class="rounded-lg border border-zinc-300 px-2 py-2 text-sm"><input name="lines[${index}][quantity]" type="number" step="0.01" value="1" min="0.01" class="rounded-lg border border-zinc-300 px-2 py-2 text-sm"><input name="lines[${index}][unit_price]" type="number" step="0.01" min="0" class="rounded-lg border border-zinc-300 px-2 py-2 text-sm">`;row.children[0].value=id;row.children[1].value=description;row.children[3].value=price;lines.append(row);index++;};root.querySelector('[data-add-line]').addEventListener('click',()=>add());root.querySelectorAll('[data-price-item]').forEach(button=>button.addEventListener('click',()=>add(button.dataset.id,button.dataset.description,button.dataset.price))); })();
    </script>
</x-layouts::app.sidebar>
