<x-layouts::app :title="'Automation run history'">
    <div class="min-h-full bg-stone-50"><div class="mx-auto max-w-7xl space-y-6 px-4 py-7 sm:px-6 lg:px-8">
        <header><span class="text-xs font-black uppercase tracking-[0.2em] text-emerald-700">Observability</span><h1 class="mt-2 text-3xl font-black text-zinc-950">Run history</h1><p class="mt-2 text-sm text-zinc-600">See what ran, what changed, and where attention is needed—without exposing provider credentials.</p></header>
        <x-workflows.partials.nav />
        <form method="GET" class="grid gap-3 rounded-2xl border border-zinc-200 bg-white p-3 sm:grid-cols-[1fr,200px,auto]"><select name="workflow" class="rounded-xl border-zinc-200 bg-zinc-50 text-sm"><option value="0">All workflows</option>@foreach($workflows as $workflow)<option value="{{ $workflow->id }}" @selected($workflowId === $workflow->id)>{{ $workflow->name }}</option>@endforeach</select><select name="status" class="rounded-xl border-zinc-200 bg-zinc-50 text-sm">@foreach(['all'=>'All statuses','success'=>'Success','failed'=>'Failed','partial_failure'=>'Partial failure'] as $value=>$label)<option value="{{ $value }}" @selected($status===$value)>{{ $label }}</option>@endforeach</select><button class="rounded-xl border border-zinc-300 px-4 py-2 text-sm font-bold">Filter</button></form>
        <section class="overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm">@forelse($runs as $run)<a href="{{ route('workflows.runs.show', $run) }}" wire:navigate class="grid gap-3 border-b border-zinc-100 px-5 py-4 last:border-0 hover:bg-emerald-50/30 sm:grid-cols-[1fr,120px,150px,130px] sm:items-center"><div><div class="font-bold text-zinc-950">{{ $run->workflow?->name ?? 'Deleted workflow' }}</div><div class="mt-1 text-xs text-zinc-500">Run #{{ $run->id }} · {{ str($run->mode)->headline() }}</div></div><span class="w-fit rounded-full px-2.5 py-1 text-xs font-black {{ $run->status === 'success' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800' }}">{{ str($run->status)->headline() }}</span><span class="text-sm text-zinc-600">{{ $run->created_at->format('M j, g:i A') }}</span><span class="text-sm text-zinc-500">{{ $run->finished_at && $run->started_at ? $run->started_at->diffForHumans($run->finished_at, true) : '—' }}</span></a>@empty<div class="p-10 text-center text-sm text-zinc-500">No workflow runs match these filters.</div>@endforelse</section>
        {{ $runs->links() }}
    </div></div>
</x-layouts::app>
