@php
    $definition = (array) $workflow->draft_definition;
    $trigger = (array) ($definition['trigger'] ?? []);
    $action = (array) ($definition['action'] ?? []);
    $testState = (array) $workflow->test_state;
    $triggerTested = (bool) data_get($testState, 'trigger.ok', false);
    $actionTested = (bool) data_get($testState, 'action.ok', false);
    $projects = (array) ($asanaConnection['projects'] ?? []);
    $calendars = (array) ($googleConnection['calendars'] ?? []);
    $asanaConnected = (bool) ($asanaConnection['oauth_connected'] ?? false) || (bool) ($asanaConnection['token_ready'] ?? false);
    $googleConnected = (bool) ($googleConnection['connected'] ?? false);
    $sourceProvider = (string) ($trigger['provider'] ?? 'asana');
    $commerceSource = in_array($sourceProvider, ['shopify', 'square', 'squarespace', 'wix', 'woocommerce'], true);
    $commerceSourceOptions = (array) ($commerceSourceOptions ?? []);
    $sourceLabel = data_get($providers, $sourceProvider.'.label', str($sourceProvider)->headline());
    $selectedTriggerConnectionId = (int) ($trigger['connection_id'] ?? 0);
    $triggerConnected = $commerceSource
        ? ($selectedTriggerConnectionId > 0 ? $commerceConnections->contains('id', $selectedTriggerConnectionId) : (bool)($commerceConnectionStatus['connected'] ?? false))
        : $asanaConnected;
    $presentation = (array) $calendarAppearance;
    $descriptionFields = (array) ($presentation['description_fields'] ?? []);
    $defaultTitleTemplate = $commerceSource ? '{{source}} #{{order_number}}' : '{{task_name}}';
    $primaryMappingChip = $commerceSource ? '{{order_number}}' : '{{task_name}}';
    $customerMappingChip = '{{customer_name}}';
    $sourceMappingChip = '{{source}}';
    $calendarColors = [
        '1' => ['Lavender', '#7986cb'], '2' => ['Sage', '#33b679'], '3' => ['Grape', '#8e24aa'],
        '4' => ['Flamingo', '#e67c73'], '5' => ['Banana', '#f6c026'], '6' => ['Tangerine', '#f4511e'],
        '7' => ['Peacock', '#039be5'], '8' => ['Graphite', '#616161'], '9' => ['Blueberry', '#3f51b5'],
        '10' => ['Basil', '#0b8043'], '11' => ['Tomato', '#d50000'],
    ];
@endphp
<x-layouts::app :title="$workflow->name">
    <div class="min-h-full bg-[linear-gradient(180deg,#fafaf9,#f4f4f5)]" data-workflow-editor-root data-workflow-source-provider="{{ $sourceProvider }}" data-workflow-source-label="{{ $sourceLabel }}">
        <header class="sticky top-0 z-20 border-b border-zinc-200 bg-white/90 backdrop-blur-xl">
            <div class="mx-auto flex max-w-[1500px] flex-wrap items-center gap-3 px-4 py-3 sm:px-6">
                <a href="{{ route('workflows.index') }}" wire:navigate class="rounded-lg p-2 text-zinc-500 hover:bg-zinc-100" aria-label="Back to workflows">←</a>
                <div class="min-w-0 flex-1"><div class="truncate font-black text-zinc-950">{{ $workflow->name }}</div><div class="flex items-center gap-2 text-xs text-zinc-500"><span data-autosave-status>Draft saved</span><span>•</span><span>Version {{ $workflow->publishedVersion?->version ?? '—' }}</span></div></div>
                <span class="rounded-full px-3 py-1.5 text-xs font-black {{ $workflow->status === 'active' ? 'bg-emerald-100 text-emerald-800' : ($workflow->status === 'paused' ? 'bg-amber-100 text-amber-800' : 'bg-zinc-100 text-zinc-700') }}">{{ $workflow->status === 'active' ? 'On' : ucfirst($workflow->status) }}</span>
                @if($workflow->published_version_id)
                    <form method="POST" action="{{ $workflow->status === 'active' ? route('workflows.pause', $workflow) : route('workflows.resume', $workflow) }}">@csrf<button class="rounded-xl border border-zinc-300 bg-white px-4 py-2 text-sm font-bold text-zinc-800 hover:bg-zinc-50">{{ $workflow->status === 'active' ? 'Pause' : 'Turn on' }}</button></form>
                    <form method="POST" action="{{ route('workflows.run', $workflow) }}">@csrf<button class="rounded-xl border border-emerald-300 bg-emerald-50 px-4 py-2 text-sm font-bold text-emerald-800 hover:bg-emerald-100">Run now</button></form>
                @endif
                <form method="POST" action="{{ route('workflows.publish', $workflow) }}">@csrf<button @disabled(!($triggerTested && $actionTested)) class="rounded-xl px-4 py-2 text-sm font-black {{ $triggerTested && $actionTested ? 'bg-zinc-950 text-white hover:bg-zinc-800' : 'cursor-not-allowed bg-zinc-200 text-zinc-500' }}">Publish</button></form>
            </div>
        </header>

        <div class="mx-auto grid max-w-[1500px] gap-5 px-4 py-5 sm:px-6 xl:grid-cols-[minmax(0,1fr)_430px]">
            <main class="relative min-h-[720px] overflow-hidden rounded-3xl border border-zinc-200 bg-stone-100 p-5 sm:p-8">
                <div class="absolute inset-0 opacity-60 [background-image:radial-gradient(#d4d4d8_1px,transparent_1px)] [background-size:20px_20px]"></div>
                <div class="relative mx-auto max-w-2xl">
                    <div class="mb-6 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-zinc-200 bg-white/90 p-4 shadow-sm">
                        <div><div class="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-700">Workflow map</div><div class="mt-1 text-sm font-bold text-zinc-950">{{ $template['description'] }}</div></div>
                        <div class="text-xs text-zinc-500">Checks every 10 minutes</div>
                    </div>

                    <article class="rounded-3xl border-2 {{ $triggerTested ? 'border-emerald-300' : 'border-rose-200' }} bg-white p-5 shadow-xl shadow-zinc-900/8">
                        <div class="flex items-start gap-4"><x-workflows.partials.provider-icon :provider="$sourceProvider" :providers="$providers" size="lg" /><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><span class="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-400">1. Trigger</span>@if($triggerTested)<span data-test-passed class="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-black text-emerald-800">Test passed</span>@endif</div><h2 class="mt-1 text-lg font-black text-zinc-950">{{ $template['trigger_event'] }}</h2><p class="mt-1 text-sm text-zinc-600">{{ $commerceSource ? 'Watch the selected store and keep each order paired to one calendar event.' : 'Watch one Asana project. Tasks without dates are safely skipped.' }}</p></div></div>
                        <div class="mt-5 rounded-2xl bg-rose-50 p-4 text-sm"><span class="font-bold text-rose-900">{{ $commerceSource ? 'Account' : 'Project' }}:</span> <span class="text-rose-800">{{ $commerceSource ? ($commerceConnections->firstWhere('id', (int)($trigger['connection_id'] ?? 0))?->external_account_label ?? 'Choose an account in Setup') : data_get(collect($projects)->firstWhere('gid', $trigger['project_gid'] ?? null), 'name', 'Choose a project in Setup') }}</span></div>
                    </article>
                    <div class="mx-auto flex h-16 w-10 flex-col items-center"><div class="h-full w-0.5 bg-emerald-400"></div><div class="-mt-1 flex h-7 w-7 items-center justify-center rounded-full border-2 border-emerald-400 bg-white text-emerald-700">↓</div></div>
                    <article class="rounded-3xl border-2 {{ $actionTested ? 'border-emerald-300' : 'border-sky-200' }} bg-white p-5 shadow-xl shadow-zinc-900/8">
                        <div class="flex items-start gap-4"><x-workflows.partials.provider-icon provider="google_calendar" :providers="$providers" size="lg" /><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><span class="text-[10px] font-black uppercase tracking-[0.2em] text-zinc-400">2. Action</span>@if($actionTested)<span data-test-passed class="rounded-full bg-emerald-100 px-2 py-0.5 text-[10px] font-black text-emerald-800">Test passed</span>@endif</div><h2 class="mt-1 text-lg font-black text-zinc-950">Create or update calendar event</h2><p class="mt-1 text-sm text-zinc-600">{{ $commerceSource ? 'Choose when the order appears, then control its title, details, location, privacy, and color.' : 'Date-only tasks become all-day events. Timed tasks use the duration you choose.' }}</p></div></div>
                        <div class="mt-5 rounded-2xl bg-sky-50 p-4 text-sm"><span class="font-bold text-sky-900">Calendar:</span> <span class="text-sky-800">{{ data_get(collect($calendars)->firstWhere('id', $action['calendar_id'] ?? null), 'summary', 'Choose a calendar in Setup') }}</span></div>
                        <div class="mt-4 overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm" aria-label="Calendar event preview">
                            <div class="flex items-center justify-between border-b border-zinc-100 bg-zinc-50 px-4 py-2.5"><span class="text-[10px] font-black uppercase tracking-[0.18em] text-zinc-500">Event preview</span><span class="text-[10px] font-bold text-zinc-400">Sample data</span></div>
                            <div class="flex gap-3 p-4"><span data-preview-color class="mt-1 h-12 w-1.5 shrink-0 rounded-full" style="background: {{ data_get($calendarColors, ($presentation['color_id'] ?? '').'.1', '#0b8043') }}"></span><div class="min-w-0"><h3 data-preview-title class="truncate text-sm font-black text-zinc-950">{{ $calendarPreview['summary'] ?? 'Everbranch event' }}</h3><p data-preview-time class="mt-1 text-xs font-semibold text-zinc-500">Tue, Jul 21 · {{ ($action['event_time_mode'] ?? 'source_time') === 'all_day' ? 'All day' : (($action['event_time_mode'] ?? 'source_time') === 'fixed_time' ? ($action['default_start_time'] ?? '9:00').' · ' : '').($action['default_duration_minutes'] ?? 60).' minutes' }} · {{ ($presentation['availability'] ?? 'busy') === 'free' ? 'Free' : 'Busy' }}</p>@if(filled($calendarPreview['location'] ?? null))<p data-preview-location class="mt-2 text-xs text-zinc-600">⌖ {{ $calendarPreview['location'] }}</p>@else<p data-preview-location class="mt-2 hidden text-xs text-zinc-600"></p>@endif<p data-preview-description class="mt-2 whitespace-pre-line text-xs leading-5 text-zinc-500">{{ $calendarPreview['description'] ?? '' }}</p></div></div>
                        </div>
                    </article>

                    <div class="mt-7 grid gap-3 sm:grid-cols-3">
                        <div class="rounded-2xl border border-zinc-200 bg-white/90 p-4"><div class="text-xs font-black text-zinc-950">Duplicate safe</div><p class="mt-1 text-xs leading-5 text-zinc-500">Each {{ $commerceSource ? 'order' : 'Asana task' }} stays paired with the same calendar event.</p></div>
                        <div class="rounded-2xl border border-zinc-200 bg-white/90 p-4"><div class="text-xs font-black text-zinc-950">Failure safe</div><p class="mt-1 text-xs leading-5 text-zinc-500">The cursor never advances past unresolved failures.</p></div>
                        <div class="rounded-2xl border border-zinc-200 bg-white/90 p-4"><div class="text-xs font-black text-zinc-950">{{ $commerceSource ? 'Cancellation rule' : 'Completion rule' }}</div><p class="mt-1 text-xs leading-5 text-zinc-500">{{ $commerceSource ? 'Cancelled orders follow the behavior you choose below.' : 'Completed tasks are skipped; existing events remain unchanged.' }}</p></div>
                    </div>
                </div>
            </main>

            <aside class="space-y-4">
                <form method="POST" action="{{ route('workflows.update', $workflow) }}" class="space-y-5 rounded-3xl border border-zinc-200 bg-white p-5 shadow-lg shadow-zinc-900/5" data-autosave-form>
                    @csrf @method('PUT')
                    <div class="flex items-center justify-between"><div><div class="text-[10px] font-black uppercase tracking-[0.2em] text-emerald-700">Setup</div><h2 class="mt-1 text-xl font-black text-zinc-950">Configure your steps</h2></div><span class="rounded-lg bg-zinc-100 px-2 py-1 text-[10px] font-bold text-zinc-500">Autosaves</span></div>
                    <div><label for="workflow-name" class="text-xs font-black uppercase tracking-wider text-zinc-500">Workflow name</label><input id="workflow-name" name="name" value="{{ old('name', $workflow->name) }}" class="mt-1.5 w-full rounded-xl border-zinc-200 bg-zinc-50 text-sm focus:border-emerald-500 focus:ring-emerald-500" /></div>

                    <fieldset class="space-y-3 rounded-2xl border border-rose-100 bg-rose-50/50 p-4"><legend class="px-1 text-xs font-black text-rose-800">{{ $sourceLabel }} trigger</legend>
                        @if(!$triggerConnected)<div class="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">Connect {{ $sourceLabel }} before configuring the trigger. <a href="{{ route('workflows.connections') }}" wire:navigate class="font-black underline">Open Connections</a></div>@endif
                        @if($commerceSource)
                            <label class="block text-xs font-bold text-zinc-700" for="trigger-connection">Account</label><select id="trigger-connection" name="trigger_connection_id" class="w-full rounded-xl border-zinc-200 bg-white text-sm" @disabled(!$triggerConnected)><option value="">Choose an account</option>@foreach($commerceConnections as $connection)<option value="{{ $connection->id }}" @selected((int)old('trigger_connection_id', $trigger['connection_id'] ?? 0) === $connection->id)>{{ $connection->external_account_label ?: $sourceLabel.' account' }}</option>@endforeach</select>
                            @if($sourceProvider === 'square')
                                <fieldset><legend class="text-xs font-bold text-zinc-700">Locations</legend><div class="mt-2 max-h-44 space-y-2 overflow-y-auto rounded-xl border border-zinc-200 bg-white p-2">@forelse($commerceSourceOptions as $option)<label class="flex items-start gap-2 rounded-lg px-2 py-2 text-xs hover:bg-zinc-50"><input type="checkbox" name="location_ids[]" value="{{ $option['id'] }}" class="mt-0.5 rounded border-zinc-300 text-emerald-600" @checked(in_array((string)$option['id'], array_map('strval', (array)old('location_ids', $trigger['location_ids'] ?? [])), true)) /><span><strong class="block text-zinc-800">{{ $option['label'] }}</strong>@if(filled($option['address'] ?? null))<span class="mt-0.5 block text-zinc-500">{{ $option['address'] }}</span>@endif</span></label>@empty<div class="p-2 text-xs leading-5 text-zinc-500">Test this Square connection on the Connections page to load its active locations.</div>@endforelse</div><p class="mt-1 text-[11px] leading-4 text-zinc-500">Leave every location unchecked to include all active locations.</p></fieldset>
                            @endif
                            <label class="block text-xs font-bold text-zinc-700" for="schedule-source">Place the event at</label><select id="schedule-source" name="schedule_source" class="w-full rounded-xl border-zinc-200 bg-white text-sm"><option value="fulfillment" @selected(($trigger['schedule_source'] ?? ($sourceProvider === 'shopify' ? 'order_created' : 'fulfillment')) === 'fulfillment')>{{ $sourceProvider === 'shopify' ? 'When fulfillment was recorded' : 'Fulfillment or ready time' }}</option><option value="delivery" @selected(($trigger['schedule_source'] ?? '') === 'delivery')>Scheduled delivery time</option><option value="pickup" @selected(($trigger['schedule_source'] ?? '') === 'pickup')>Scheduled pickup time</option><option value="order_created" @selected(($trigger['schedule_source'] ?? '') === 'order_created')>When the order was created</option></select><p class="text-[11px] leading-4 text-zinc-500">If the chosen time is missing, the order is held for review instead of guessing.</p>
                        @else
                            <label class="block text-xs font-bold text-zinc-700" for="project-gid">Project</label><select id="project-gid" name="project_gid" class="w-full rounded-xl border-zinc-200 bg-white text-sm" @disabled(!$asanaConnected)><option value="">Choose a project</option>@foreach($projects as $project)<option value="{{ $project['gid'] }}" @selected(old('project_gid', $trigger['project_gid'] ?? '') === $project['gid'])>{{ $project['name'] }} · {{ $project['workspace_name'] }}</option>@endforeach</select><input type="hidden" name="schedule_source" value="source_date" />
                        @endif
                    </fieldset>

                    <fieldset class="space-y-3 rounded-2xl border border-sky-100 bg-sky-50/50 p-4"><legend class="px-1 text-xs font-black text-sky-800">Google Calendar action</legend>
                        @if(!$googleConnected)<div class="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs text-amber-900">Connect Google Calendar before selecting a calendar. <a href="{{ route('workflows.connections') }}" wire:navigate class="font-black underline">Open Connections</a></div>@endif
                        <label class="block text-xs font-bold text-zinc-700" for="calendar-id">Calendar</label><select id="calendar-id" name="calendar_id" class="w-full rounded-xl border-zinc-200 bg-white text-sm" @disabled(!$googleConnected)><option value="">Choose a writable calendar</option>@foreach($calendars as $calendar)<option value="{{ $calendar['id'] }}" @selected(old('calendar_id', $action['calendar_id'] ?? '') === $calendar['id'])>{{ $calendar['summary'] }}{{ $calendar['primary'] ? ' · Primary' : '' }}</option>@endforeach</select>
                        @if($commerceSource)
                            <div><label class="text-xs font-bold text-zinc-700" for="event-time-mode">Event timing</label><select id="event-time-mode" name="event_time_mode" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm" data-event-time-mode><option value="source_time" @selected(($action['event_time_mode'] ?? 'source_time') === 'source_time')>Use the store's exact time</option><option value="fixed_time" @selected(($action['event_time_mode'] ?? '') === 'fixed_time')>Use a fixed time on that date</option><option value="all_day" @selected(($action['event_time_mode'] ?? '') === 'all_day')>Create an all-day event</option></select></div>
                            <div class="grid gap-3 sm:grid-cols-2"><div><label class="text-xs font-bold text-zinc-700" for="default-start-time">Fixed start time</label><input id="default-start-time" type="time" name="default_start_time" value="{{ old('default_start_time', $action['default_start_time'] ?? '09:00') }}" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm" data-default-start-time /></div><div><label class="text-xs font-bold text-zinc-700" for="schedule-offset-days">Day adjustment</label><select id="schedule-offset-days" name="schedule_offset_days" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm">@foreach([-7 => '7 days before', -3 => '3 days before', -1 => '1 day before', 0 => 'Same day', 1 => '1 day after', 3 => '3 days after', 7 => '7 days after'] as $days => $label)<option value="{{ $days }}" @selected((int)($action['schedule_offset_days'] ?? 0) === $days)>{{ $label }}</option>@endforeach</select></div></div>
                            <input type="hidden" name="skip_completed_tasks" value="0" />
                        @else
                            <input type="hidden" name="event_time_mode" value="source_time" /><input type="hidden" name="default_start_time" value="09:00" /><input type="hidden" name="schedule_offset_days" value="0" />
                        @endif
                        <div class="grid gap-3 sm:grid-cols-2"><div><label class="text-xs font-bold text-zinc-700" for="timezone">Timezone</label><select id="timezone" name="timezone" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm">@foreach(['America/New_York','America/Chicago','America/Denver','America/Los_Angeles','UTC'] as $timezone)<option value="{{ $timezone }}" @selected(($action['timezone'] ?? config('app.timezone')) === $timezone)>{{ str_replace('_', ' ', $timezone) }}</option>@endforeach</select></div><div><label class="text-xs font-bold text-zinc-700" for="duration">Timed duration</label><select id="duration" name="default_duration_minutes" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm" data-event-duration>@foreach([15,30,45,60,90,120] as $minutes)<option value="{{ $minutes }}" @selected((int)($action['default_duration_minutes'] ?? 60) === $minutes)>{{ $minutes }} minutes</option>@endforeach</select></div></div>
                        @unless($commerceSource)<label class="flex items-start gap-3 rounded-xl bg-white p-3 text-sm text-zinc-700"><input type="checkbox" name="skip_completed_tasks" value="1" class="mt-0.5 rounded border-zinc-300 text-emerald-600 focus:ring-emerald-500" @checked((bool)($action['skip_completed_tasks'] ?? true)) /><span><strong class="block text-zinc-950">Skip completed tasks</strong><span class="text-xs text-zinc-500">Existing events remain unchanged when a task is completed.</span></span></label>@endunless

                        <details open class="group rounded-2xl border border-sky-100 bg-white">
                            <summary class="flex cursor-pointer list-none items-center justify-between gap-3 px-4 py-3 text-sm font-black text-zinc-950"><span>Calendar appearance</span><span class="text-zinc-400 transition group-open:rotate-180" aria-hidden="true">⌄</span></summary>
                            <div class="space-y-4 border-t border-sky-100 p-4">
                                <div><label class="text-xs font-bold text-zinc-700" for="event-title-template">Event title</label><input id="event-title-template" name="event_title_template" value="{{ old('event_title_template', $presentation['title_template'] ?? $defaultTitleTemplate) }}" class="mt-1 w-full rounded-xl border-zinc-200 bg-zinc-50 text-sm" data-event-title-template /><p class="mt-1.5 text-[11px] leading-4 text-zinc-500">Use mapping chips like <code class="rounded bg-zinc-100 px-1">{{ $primaryMappingChip }}</code>@if($commerceSource), <code class="rounded bg-zinc-100 px-1">{{ $customerMappingChip }}</code>, and <code class="rounded bg-zinc-100 px-1">{{ $sourceMappingChip }}</code>@endif.</p></div>
                                <fieldset><legend class="text-xs font-bold text-zinc-700">Show in description</legend><div class="mt-2 grid gap-2 sm:grid-cols-2">
                                    @foreach(($commerceSource ? ['items' => 'Order items', 'total' => 'Order total', 'status' => 'Order status', 'customer_contact' => 'Customer contact', 'source_link' => 'Source link'] : ['notes' => 'Task notes', 'status' => 'Task status', 'source_link' => 'Asana link']) as $field => $label)
                                        <label class="flex items-center gap-2 rounded-lg border border-zinc-100 px-2.5 py-2 text-xs font-semibold text-zinc-700"><input type="checkbox" name="event_description_fields[]" value="{{ $field }}" class="rounded border-zinc-300 text-emerald-600" @checked(in_array($field, $descriptionFields, true)) data-description-field />{{ $label }}</label>
                                    @endforeach
                                </div>@if($commerceSource)<p class="mt-2 text-[11px] text-zinc-500">Customer email and phone stay off by default for privacy.</p>@endif</fieldset>
                                @if($commerceSource)<div><label class="text-xs font-bold text-zinc-700" for="event-location-source">Event location</label><select id="event-location-source" name="event_location_source" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm" data-event-location-source>@foreach(['shipping_address' => 'Shipping address', 'billing_address' => 'Billing address', 'pickup_location' => 'Pickup location', 'none' => 'No location'] as $value => $label)<option value="{{ $value }}" @selected(($presentation['location_source'] ?? 'shipping_address') === $value)>{{ $label }}</option>@endforeach</select></div>@else<input type="hidden" name="event_location_source" value="none" />@endif
                                <div class="grid gap-3 sm:grid-cols-2"><div><label class="text-xs font-bold text-zinc-700" for="event-color">Event color</label><select id="event-color" name="event_color_id" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm" data-event-color><option value="">Calendar default</option>@foreach($calendarColors as $id => [$label, $hex])<option value="{{ $id }}" data-color="{{ $hex }}" @selected((string)($presentation['color_id'] ?? '') === $id)>{{ $label }}</option>@endforeach</select></div><div><label class="text-xs font-bold text-zinc-700" for="event-availability">Show me as</label><select id="event-availability" name="event_availability" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm" data-event-availability><option value="busy" @selected(($presentation['availability'] ?? 'busy') === 'busy')>Busy</option><option value="free" @selected(($presentation['availability'] ?? 'busy') === 'free')>Free</option></select></div></div>
                                <div class="grid gap-3 sm:grid-cols-2"><div><label class="text-xs font-bold text-zinc-700" for="event-visibility">Visibility</label><select id="event-visibility" name="event_visibility" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm"><option value="default" @selected(($presentation['visibility'] ?? 'default') === 'default')>Calendar default</option><option value="private" @selected(($presentation['visibility'] ?? 'default') === 'private')>Private</option></select></div><div><label class="text-xs font-bold text-zinc-700" for="event-reminders">Reminders</label><select id="event-reminders" name="event_reminders" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm"><option value="default" @selected(($presentation['reminders'] ?? 'default') === 'default')>Calendar default</option><option value="none" @selected(($presentation['reminders'] ?? 'default') === 'none')>None</option></select></div></div>
                                @if($commerceSource)<div><label class="text-xs font-bold text-zinc-700" for="cancelled-order-behavior">Cancelled orders</label><select id="cancelled-order-behavior" name="cancelled_order_behavior" class="mt-1 w-full rounded-xl border-zinc-200 bg-white text-sm"><option value="mark_cancelled" @selected(($presentation['cancelled_order_behavior'] ?? 'mark_cancelled') === 'mark_cancelled')>Keep event and mark “Cancelled”</option><option value="leave_unchanged" @selected(($presentation['cancelled_order_behavior'] ?? 'mark_cancelled') === 'leave_unchanged')>Leave existing event unchanged</option></select></div>@else<input type="hidden" name="cancelled_order_behavior" value="mark_cancelled" />@endif
                            </div>
                        </details>
                    </fieldset>
                    <button class="w-full rounded-xl border border-zinc-300 bg-white px-4 py-2.5 text-sm font-black text-zinc-800 hover:bg-zinc-50">Save draft</button>
                </form>

                <section class="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 class="font-black text-zinc-950">Test before publishing</h2><p class="mt-1 text-xs leading-5 text-zinc-500">Tests are tied to this exact draft. Changing setup clears them.</p><div class="mt-4 grid gap-3 sm:grid-cols-2 xl:grid-cols-1 2xl:grid-cols-2"><form method="POST" action="{{ route('workflows.test-trigger', $workflow) }}">@csrf<button class="w-full rounded-xl border px-4 py-3 text-left text-sm font-bold {{ $triggerTested ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-zinc-200 bg-zinc-50 text-zinc-800' }}">{{ $triggerTested ? '✓' : '1.' }} Test trigger<span class="mt-1 block text-xs font-normal opacity-75">{{ data_get($testState, 'trigger.summary', $commerceSource ? 'Load a recent order sample' : 'Verify project access') }}</span></button></form><form method="POST" action="{{ route('workflows.test-action', $workflow) }}">@csrf<button class="w-full rounded-xl border px-4 py-3 text-left text-sm font-bold {{ $actionTested ? 'border-emerald-200 bg-emerald-50 text-emerald-800' : 'border-zinc-200 bg-zinc-50 text-zinc-800' }}">{{ $actionTested ? '✓' : '2.' }} Test action<span class="mt-1 block text-xs font-normal opacity-75">{{ data_get($testState, 'action.summary', 'Create and remove a test event') }}</span></button></form></div></section>

                @if($workflow->runs->isNotEmpty())<section class="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-black text-zinc-950">Recent runs</h2><a href="{{ route('workflows.history', ['workflow' => $workflow->id]) }}" wire:navigate class="text-xs font-black text-emerald-700">View all</a></div><div class="mt-3 divide-y divide-zinc-100">@foreach($workflow->runs as $run)<a href="{{ route('workflows.runs.show', $run) }}" wire:navigate class="flex items-center justify-between gap-3 py-3 text-sm"><span class="font-semibold text-zinc-700">{{ $run->created_at->format('M j, g:i A') }}</span><span class="rounded-full px-2 py-1 text-[10px] font-black {{ $run->status === 'success' ? 'bg-emerald-100 text-emerald-800' : 'bg-rose-100 text-rose-800' }}">{{ str($run->status)->headline() }}</span></a>@endforeach</div></section>@endif
            </aside>
        </div>
    </div>
</x-layouts::app>
