api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "wholesale-checkout-access"
type = "function"
uid = "4caeac96-c51d-8df4-6b27-ef3462e68a84349570f9"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
