<x-layouts::app.sidebar :title="$collection?->title ?? 'Create collection'"><flux:main><div class="mx-auto max-w-6xl space-y-5 pb-12">
@include('managed-website.catalog.nav')
@if(session('status'))<p role="status" class="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('status') }}</p>@endif
@if($errors->any())<div role="alert" class="rounded-lg bg-rose-50 p-4 text-sm text-rose-900">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
<header class="flex items-center justify-between"><div><a class="text-sm text-zinc-500" href="{{ route('managed-website.collections.index') }}">← Collections</a><h1 class="mt-2 text-3xl font-bold">{{ $collection?->title ?? 'Create collection' }}</h1></div><button form="collection-editor" class="fb-btn fb-btn-primary">Save collection</button></header>
<form id="collection-editor" method="POST" action="{{ $collection ? route('managed-website.collections.update',$collection) : route('managed-website.collections.store') }}" class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_300px]" x-data="{title:{{ Illuminate\Support\Js::from(old('title',$collection?->title ?? '')) }},handle:{{ Illuminate\Support\Js::from(old('handle',$collection?->handle ?? '')) }},image:{{ Illuminate\Support\Js::from(old('image_url',$collection?->image_url ?? '')) }},filter:''}">
@csrf @if($collection) @method('PUT') @endif<input type="hidden" name="revision" value="{{ old('revision',data_get($collection?->seo,'catalog_revision',0)) }}">
<div class="space-y-5"><section class="space-y-5 rounded-xl border bg-white p-6"><label class="block text-sm font-semibold">Title<input name="title" required x-model="title" @if(!$collection) @input="handle=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')" @endif class="mt-2 block w-full rounded-lg border-zinc-300 text-sm"></label><label class="block text-sm font-semibold">Description<textarea name="description" rows="5" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm">{{ old('description',$collection?->description) }}</textarea></label><label class="block text-sm font-semibold">URL handle<input name="handle" x-model="handle" required pattern="[a-z0-9]+(-[a-z0-9]+)*" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm"></label></section>
<section class="rounded-xl border bg-white p-6"><h2 class="font-bold">Products</h2><input type="search" x-model="filter" placeholder="Find a product" aria-label="Find a product" class="my-4 block w-full rounded-lg border-zinc-300 text-sm"><div class="max-h-[600px] overflow-y-auto divide-y">@forelse($products as $product)<label x-show="!filter || {{ Illuminate\Support\Js::from(mb_strtolower($product->title)) }}.includes(filter.toLowerCase())" class="flex items-center gap-4 py-3"><input type="checkbox" name="product_ids[]" value="{{ $product->id }}" @checked(in_array($product->id,old('product_ids',$collection?->products->pluck('id')->all() ?? [])))>@if(data_get($product->media,'0'))<img src="{{ $product->media[0] }}" alt="" class="h-12 w-12 rounded-lg border object-cover">@endif<span class="flex-1 text-sm font-medium">{{ $product->title }}</span><span class="text-xs text-zinc-500">{{ ucfirst($product->status) }}</span></label>@empty<p class="text-sm text-zinc-500">Add products to your catalog first.</p>@endforelse</div></section></div>
<aside class="space-y-5"><section class="rounded-xl border bg-white p-5"><label class="block text-sm font-semibold">Status<select name="status" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm">@foreach(['draft','active','archived'] as $status)<option value="{{ $status }}" @selected(old('status',$collection?->status ?? 'draft')===$status)>{{ ucfirst($status) }}</option>@endforeach</select></label><p class="mt-3 text-xs leading-5 text-zinc-500">Only active collections and active products appear on the storefront.</p></section><section class="rounded-xl border bg-white p-5"><h2 class="font-bold">Collection image</h2><template x-if="image"><img :src="image" :alt="title" class="mt-4 aspect-square w-full rounded-lg border object-cover"></template><label class="mt-4 block text-sm font-semibold">Image URL<input type="url" name="image_url" x-model="image" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm" placeholder="https://"></label></section></aside>
<div class="flex justify-end border-t pt-5 lg:col-span-2"><button class="fb-btn fb-btn-primary">Save collection</button></div>
</form></div></flux:main></x-layouts::app.sidebar>
