<x-layouts::app.sidebar title="Products">
<flux:main><div class="mx-auto max-w-[1440px] space-y-5 pb-12">
    @include('managed-website.catalog.nav')
    @if(session('status'))<p role="status" class="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('status') }}</p>@endif
    <header class="flex flex-wrap items-center justify-between gap-4"><div><h1 class="text-3xl font-bold">Products</h1><p class="mt-2 text-sm text-zinc-500">Manage your catalog, product photos, prices, and availability.</p></div><div class="flex gap-3"><a class="fb-btn fb-btn-secondary" href="{{ route('managed-website.products.export') }}">Export</a>@if($canEdit)<a class="fb-btn fb-btn-primary" href="{{ route('managed-website.products.create') }}">Add product</a>@endif</div></header>
    <section class="overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-sm">
        <div class="flex flex-wrap gap-2 border-b px-4 py-3">@foreach(['active'=>'Active','draft'=>'Draft','archived'=>'Archived','all'=>'All'] as $key=>$label)<a class="rounded-lg px-3 py-2 text-sm {{ $status===$key ? 'bg-zinc-100 font-bold' : 'text-zinc-500' }}" href="{{ route('managed-website.products.index',['status'=>$key]) }}">{{ $label }} <span class="ml-1 text-xs text-zinc-500">{{ $key==='all' ? $counts->sum() : ($counts[$key] ?? 0) }}</span></a>@endforeach</div>
        <form method="GET" class="flex flex-wrap items-end gap-3 border-b bg-zinc-50/50 p-4"><input type="hidden" name="status" value="{{ $status }}"><label class="min-w-52 flex-1 text-xs font-semibold text-zinc-600">Search products<input name="q" type="search" value="{{ $filters['q'] ?? '' }}" placeholder="Title or SKU" class="mt-1 block w-full rounded-lg border-zinc-300 text-sm"></label><label class="text-xs font-semibold text-zinc-600">Collection<select name="collection" class="mt-1 block rounded-lg border-zinc-300 text-sm"><option value="">All collections</option>@foreach($collections as $collection)<option value="{{ $collection->id }}" @selected(($filters['collection'] ?? '')==$collection->id)>{{ $collection->title }}</option>@endforeach</select></label><label class="text-xs font-semibold text-zinc-600">Sort<select name="sort" class="mt-1 block rounded-lg border-zinc-300 text-sm">@foreach(['title'=>'Title A–Z','newest'=>'Newest','updated'=>'Recently updated'] as $key=>$label)<option value="{{ $key }}" @selected(($filters['sort'] ?? 'title')===$key)>{{ $label }}</option>@endforeach</select></label><button class="fb-btn fb-btn-secondary">Filter</button></form>
        <div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="border-b bg-zinc-50 text-xs text-zinc-500"><tr><th class="px-5 py-3">Product</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Inventory</th><th class="px-5 py-3">Collections</th><th class="px-5 py-3 text-right">Price</th><th class="px-5 py-3"></th></tr></thead><tbody class="divide-y divide-zinc-100">
        @forelse($products as $product)
        <tr class="hover:bg-zinc-50"><td class="px-5 py-4"><a href="{{ route('managed-website.products.edit',$product) }}" class="flex items-center gap-4"><div class="flex h-16 w-16 shrink-0 items-center justify-center overflow-hidden rounded-lg border bg-zinc-50">@if(data_get($product->media,'0'))<img src="{{ $product->media[0] }}" alt="{{ $product->title }}" class="h-full w-full object-cover" loading="lazy">@else<span class="text-center text-xs text-zinc-400">No image</span>@endif</div><div><span class="font-semibold text-zinc-900">{{ $product->title }}</span><span class="mt-1 block text-xs text-zinc-500">{{ str($product->product_type)->headline() }} · {{ $product->variants->count() }} {{ str('variant')->plural($product->variants->count()) }}</span></div></a></td><td class="px-5 py-4"><x-ui.status-badge :tone="$product->status==='active'?'success':'neutral'">{{ ucfirst($product->status) }}</x-ui.status-badge></td><td class="px-5 py-4 text-zinc-600">{{ $product->track_inventory ? $product->variants->sum('inventory_quantity').' in stock' : 'Not tracked' }}</td><td class="px-5 py-4 text-zinc-600">{{ $product->collections->pluck('title')->join(', ') ?: '—' }}</td><td class="px-5 py-4 text-right font-medium">${{ number_format(($product->variants->min('price_cents') ?? 0)/100,2) }}@if($product->variants->min('price_cents')!==$product->variants->max('price_cents'))–${{ number_format($product->variants->max('price_cents')/100,2) }}@endif</td><td class="px-5 py-4 text-right"><a href="{{ route('managed-website.products.edit',$product) }}" class="font-semibold text-emerald-800">Edit</a></td></tr>
        @empty<tr><td colspan="6" class="p-14 text-center"><h2 class="font-semibold">No products in this view</h2><p class="mt-2 text-sm text-zinc-500">Try another filter or add your first product.</p></td></tr>@endforelse
        </tbody></table></div><div class="border-t p-4">{{ $products->links() }}</div>
    </section>
</div></flux:main>
</x-layouts::app.sidebar>
