<x-layouts::app.sidebar :title="$product?->title ?? 'Add product'">
<flux:main><div class="mx-auto max-w-[1320px] space-y-5 pb-12">
    @include('managed-website.catalog.nav')
    @if(session('status'))<p role="status" class="rounded-lg bg-emerald-50 p-4 text-sm text-emerald-900">{{ session('status') }}</p>@endif
    @if($errors->any())<div role="alert" class="rounded-lg bg-rose-50 p-4 text-sm text-rose-900">@foreach($errors->all() as $error)<p>{{ $error }}</p>@endforeach</div>@endif
    <header class="flex flex-wrap items-center justify-between gap-4"><div><a href="{{ route('managed-website.products.index') }}" class="text-sm text-zinc-500">← Products</a><h1 class="mt-2 text-3xl font-bold">{{ $product?->title ?? 'Add product' }}</h1></div><button form="product-editor" class="fb-btn fb-btn-primary">Save product</button></header>
    @php
    $variants=old('variants', $product ? $product->variants->map(fn($v)=>['id'=>$v->id,'title'=>$v->title,'sku'=>$v->sku ?? '', 'price'=>number_format($v->price_cents/100,2,'.',''),'compare_at_price'=>$v->compare_at_price_cents===null?'':number_format($v->compare_at_price_cents/100,2,'.',''),'wholesale_price'=>$v->wholesale_price_cents===null?'':number_format($v->wholesale_price_cents/100,2,'.',''),'inventory_quantity'=>$v->inventory_quantity ?? 0,'is_available'=>$v->is_available?'1':'0','shipping_weight_ounces'=>$v->shipping_weight_ounces ?? ''])->all() : [['id'=>null,'title'=>'Default','sku'=>'','price'=>'0.00','compare_at_price'=>'','wholesale_price'=>'','inventory_quantity'=>0,'is_available'=>'1','shipping_weight_ounces'=>'']]);
    @endphp
    <form id="product-editor" method="POST" enctype="multipart/form-data" action="{{ $product ? route('managed-website.products.update',$product) : route('managed-website.products.store') }}" x-data="{variants:{{ Illuminate\Support\Js::from($variants) }}, previews:[], title:{{ Illuminate\Support\Js::from(old('title',$product?->title ?? '')) }}, handle:{{ Illuminate\Support\Js::from(old('handle',$product?->handle ?? '')) }}, isNew:{{ $product?'false':'true' }} }" class="grid gap-5 lg:grid-cols-[minmax(0,1fr)_310px]">
        @csrf @if($product) @method('PUT') @endif
        <input type="hidden" name="catalog_form" value="1"><input type="hidden" name="revision" value="{{ old('revision',data_get($product?->service_details,'catalog_revision',0)) }}">
        <div class="space-y-5">
            <section class="space-y-5 rounded-xl border bg-white p-6 shadow-sm"><label class="block text-sm font-semibold">Title<input required name="title" x-model="title" @input="if(isNew) handle=title.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')" maxlength="190" class="mt-2 block w-full rounded-lg border-zinc-300 text-base" value="{{ old('title',$product?->title) }}"></label><label class="block text-sm font-semibold">Description<textarea name="description" rows="7" maxlength="8000" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm leading-6">{{ old('description',$product?->description) }}</textarea></label></section>
            <section class="rounded-xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Media</h2><p class="mt-1 text-xs text-zinc-500">The first image is the cover. Uncheck an image to remove it from this product.</p>
                <div class="mt-4 grid grid-cols-2 gap-4 sm:grid-cols-3">
                @foreach($product?->media ?? [] as $url)<label class="overflow-hidden rounded-lg border"><img src="{{ $url }}" alt="{{ $product->title }}" class="aspect-square w-full bg-zinc-50 object-contain"><span class="flex items-center gap-2 border-t p-3 text-xs"><input type="checkbox" name="retained_media[]" value="{{ $url }}" @checked(in_array($url,old('retained_media',$product->media)))> {{ $loop->first?'Cover image':'Keep image' }}</span></label>@endforeach
                <template x-for="(src,index) in previews" :key="src"><figure class="overflow-hidden rounded-lg border"><img :src="src" :alt="'New product image '+(index+1)" class="aspect-square w-full bg-zinc-50 object-contain"><figcaption class="p-3 text-xs text-zinc-500">New image · save to upload</figcaption></figure></template>
                </div>
                <label class="mt-5 block cursor-pointer rounded-lg border-2 border-dashed border-zinc-200 p-6 text-center"><span class="block text-sm font-semibold">Upload product images</span><span class="mt-1 block text-xs text-zinc-500">JPG, PNG, WebP or AVIF · Up to 10 MB each</span><input name="images[]" type="file" accept="image/jpeg,image/png,image/webp,image/avif" multiple class="mt-3 max-w-full text-sm" @change="previews.forEach(src=>URL.revokeObjectURL(src)); previews=Array.from($event.target.files).map(file=>URL.createObjectURL(file))"></label>
                <details class="mt-4"><summary class="cursor-pointer text-sm text-emerald-800">Add images by URL</summary><textarea name="image_urls" rows="3" placeholder="One https:// image URL per line" class="mt-2 w-full rounded-lg border-zinc-300 text-sm">{{ old('image_urls') }}</textarea></details>
                <label class="mt-4 block text-sm font-semibold">Cover image description<input name="image_alt" value="{{ old('image_alt',data_get($product?->service_details,'image_alt')) }}" maxlength="500" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm" placeholder="Describe the product photo for accessibility"></label>
            </section>
            <section class="rounded-xl border bg-white p-6 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="font-bold">Pricing & variants</h2><p class="mt-1 text-xs text-zinc-500">Use a variant for each size, finish, or other option.</p></div><button type="button" class="fb-btn fb-btn-secondary" @click="variants.push({id:null,title:'',sku:'',price:'0.00',compare_at_price:'',wholesale_price:'',inventory_quantity:0,is_available:'1',shipping_weight_ounces:''})" :disabled="variants.length>=50">Add variant</button></div>
                <label class="mt-5 flex items-center gap-2 text-sm"><input name="track_inventory" type="hidden" value="0"><input name="track_inventory" type="checkbox" value="1" @checked(old('track_inventory',$product?->track_inventory))> Track inventory</label>
                <div class="mt-5 space-y-4"><template x-for="(variant,index) in variants" :key="index"><fieldset class="rounded-lg border bg-zinc-50/50 p-4"><legend class="px-2 text-sm font-semibold" x-text="variant.title || 'New variant'"></legend><input type="hidden" :name="'variants['+index+'][id]'" :value="variant.id || ''"><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-3">
                    <label class="text-xs font-semibold">Variant name<input required :name="'variants['+index+'][title]'" x-model="variant.title" class="mt-1 block w-full rounded-md border-zinc-300 text-sm" placeholder="e.g. Natural / Large"></label>
                    <label class="text-xs font-semibold">SKU<input :name="'variants['+index+'][sku]'" x-model="variant.sku" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label>
                    <label class="text-xs font-semibold">Availability<select :name="'variants['+index+'][is_available]'" x-model="variant.is_available" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"><option value="1">Available</option><option value="0">Unavailable</option></select></label>
                    <label class="text-xs font-semibold">Price ($)<input required type="number" min="0" step="0.01" :name="'variants['+index+'][price]'" x-model="variant.price" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label>
                    <label class="text-xs font-semibold">Compare-at price ($)<input type="number" min="0" step="0.01" :name="'variants['+index+'][compare_at_price]'" x-model="variant.compare_at_price" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label>
                    <label class="text-xs font-semibold">Wholesale price ($)<input type="number" min="0" step="0.01" :name="'variants['+index+'][wholesale_price]'" x-model="variant.wholesale_price" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label>
                    <label class="text-xs font-semibold">Quantity in stock<input type="number" min="0" :name="'variants['+index+'][inventory_quantity]'" x-model="variant.inventory_quantity" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label>
                    <label class="text-xs font-semibold">Shipping weight (oz)<input type="number" min="1" :name="'variants['+index+'][shipping_weight_ounces]'" x-model="variant.shipping_weight_ounces" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label>
                </div><button type="button" x-show="!variant.id && variants.length>1" @click="variants.splice(index,1)" class="mt-3 text-xs text-rose-700">Remove new variant</button></fieldset></template></div>
            </section>
            <section class="rounded-xl border bg-white p-6 shadow-sm"><label class="block text-sm font-semibold">Product details<textarea name="details" rows="4" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm" placeholder="One feature or detail per line">{{ old('details',data_get($product?->service_details,'details')) }}</textarea></label></section>
            <section class="space-y-4 rounded-xl border bg-white p-6 shadow-sm"><h2 class="font-bold">Search listing</h2><label class="block text-sm font-semibold">URL handle<input name="handle" x-model="handle" required maxlength="160" pattern="[a-z0-9]+(-[a-z0-9]+)*" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm"></label><label class="block text-sm font-semibold">Search title<input name="seo_title" value="{{ old('seo_title',data_get($product?->seo,'title')) }}" maxlength="190" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm"></label><label class="block text-sm font-semibold">Search description<textarea name="seo_description" maxlength="320" rows="3" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm">{{ old('seo_description',data_get($product?->seo,'description')) }}</textarea></label></section>
        </div>
        <aside class="space-y-5">
            <section class="space-y-4 rounded-xl border bg-white p-5 shadow-sm"><label class="block text-sm font-semibold">Status<select name="status" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm">@foreach(['draft'=>'Draft','active'=>'Active','archived'=>'Archived'] as $key=>$label)<option value="{{ $key }}" @selected(old('status',$product?->status ?? 'draft')===$key)>{{ $label }}</option>@endforeach</select></label><p class="text-xs leading-5 text-zinc-500">Active products appear in your catalog. Draft and archived products stay off the storefront. Saving an active product updates it without publishing website pages.</p></section>
            <section class="space-y-4 rounded-xl border bg-white p-5 shadow-sm"><h2 class="font-bold">Organization</h2><label class="block text-sm font-semibold">Sell as<select name="product_type" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm">@foreach(['physical'=>'Physical product','service'=>'Fixed-price service','quote'=>'Quote request'] as $key=>$label)<option value="{{ $key }}" @selected(old('product_type',$product?->product_type ?? 'physical')===$key)>{{ $label }}</option>@endforeach</select></label>
            @foreach(['category'=>'Category','vendor'=>'Vendor','tags'=>'Tags'] as $key=>$label)<label class="block text-sm font-semibold">{{ $label }}<input name="{{ $key }}" value="{{ old($key,data_get($product?->service_details,$key)) }}" class="mt-2 block w-full rounded-lg border-zinc-300 text-sm"></label>@endforeach
            </section>
            <section class="rounded-xl border bg-white p-5 shadow-sm"><div class="flex items-center justify-between"><h2 class="font-bold">Collections</h2><a href="{{ route('managed-website.collections.index') }}" class="text-xs text-emerald-800">Manage</a></div><div class="mt-4 space-y-3">@forelse($collections as $collection)<label class="flex items-center gap-2 text-sm"><input type="checkbox" name="collection_ids[]" value="{{ $collection->id }}" @checked(in_array($collection->id,old('collection_ids',$product?->collections->pluck('id')->all() ?? [])))>{{ $collection->title }}<span class="text-xs text-zinc-400">{{ $collection->status==='active'?'':$collection->status }}</span></label>@empty<p class="text-sm text-zinc-500">Create a collection to organize related products.</p>@endforelse</div></section>
        </aside>
        <footer class="flex justify-end border-t pt-5 lg:col-span-2"><button class="fb-btn fb-btn-primary">Save product</button></footer>
    </form>
    @if($product && $product->status!=='archived')<form method="POST" action="{{ route('managed-website.products.destroy',$product) }}">@csrf @method('DELETE')<button class="text-sm font-semibold text-rose-700">Archive product</button></form>@endif
</div></flux:main>
</x-layouts::app.sidebar>
