<x-layouts::app.sidebar :title="$customer ? 'Customer' : 'Add customer'">
    <flux:main>
        <div class="mx-auto max-w-6xl space-y-5 pb-10">
            @if(session('status'))<div class="border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-medium text-emerald-950" role="status">{{ session('status') }}</div>@endif
            @if($customer)
                <x-ui.operational-header :title="trim($customer->first_name.' '.$customer->last_name) ?: 'Website shopper'" :description="$customer->email ?: 'No email on file'" :back="['href' => route('managed-website.customers.index'), 'label' => 'Customers']">
                    <a class="fb-btn fb-btn-secondary" href="{{ route('managed-website.orders.create') }}">Create draft order</a>
                </x-ui.operational-header>
                <div class="grid gap-5 lg:grid-cols-[1.5fr_.8fr]">
                    <section class="overflow-hidden border border-zinc-200 bg-white"><x-ui.operational-toolbar><h2 class="text-sm font-semibold text-zinc-950">Native Website orders</h2><span class="text-xs text-zinc-500">{{ $orders->total() }} total</span></x-ui.operational-toolbar><div class="divide-y divide-zinc-100">@forelse($orders as $order)<a href="{{ route('managed-website.orders.show', $order) }}" class="flex items-center justify-between gap-4 px-4 py-3 hover:bg-zinc-50"><span><strong class="block text-sm font-medium text-emerald-800">{{ $order->number }}</strong><span class="text-xs text-zinc-500">{{ $order->created_at->format('M j, Y') }} · {{ str($order->order_status)->headline() }}</span></span><span class="text-sm font-medium text-zinc-900">${{ number_format($order->total_cents / 100, 2) }}</span></a>@empty<x-ui.operational-empty-state title="No native Website orders" description="Orders for this customer will appear here. Connected-platform history remains separate." />@endforelse</div>@if($orders instanceof \Illuminate\Pagination\LengthAwarePaginator)<div class="border-t border-zinc-200 px-4 py-3">{{ $orders->links() }}</div>@endif</section>
                    <aside class="border border-zinc-200 bg-white p-4"><h2 class="text-sm font-semibold text-zinc-950">Customer details</h2><form class="mt-4 grid gap-3" method="POST" action="{{ route('managed-website.customers.update', $customer) }}">@csrf @method('PUT')<label class="text-sm font-medium">First name<input name="first_name" value="{{ $customer->first_name }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label><label class="text-sm font-medium">Last name<input name="last_name" value="{{ $customer->last_name }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label><label class="text-sm font-medium">Email<input name="email" type="email" value="{{ $customer->email }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label><label class="text-sm font-medium">Phone<input name="phone" value="{{ $customer->phone }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label><button class="fb-btn fb-btn-secondary mt-1" type="submit">Save details</button></form></aside>
                </div>
            @else
                <x-ui.operational-header title="Add customer" description="Create a native Website customer. Marketing and connected-platform records are not changed." :back="['href' => route('managed-website.customers.index'), 'label' => 'Customers']" />
                <form method="POST" action="{{ route('managed-website.customers.store') }}" class="max-w-2xl border border-zinc-200 bg-white">@csrf<div class="grid gap-4 p-5 sm:grid-cols-2"><label class="text-sm font-medium">First name<input name="first_name" value="{{ old('first_name') }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label><label class="text-sm font-medium">Last name<input name="last_name" value="{{ old('last_name') }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label><label class="text-sm font-medium sm:col-span-2">Email<input name="email" type="email" value="{{ old('email') }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label><label class="text-sm font-medium sm:col-span-2">Phone<input name="phone" value="{{ old('phone') }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label></div><div class="flex justify-end border-t border-zinc-200 bg-zinc-50 px-5 py-3"><button class="fb-btn fb-btn-primary" type="submit">Save customer</button></div></form>
            @endif
        </div>
    </flux:main>
</x-layouts::app.sidebar>
