<x-layouts::app.sidebar title="Create draft order">
    <flux:main>
        <div class="mx-auto max-w-4xl space-y-5 pb-10">
            <x-ui.operational-header title="Create draft order" description="Save an internal native Website order for review. This does not charge, reserve inventory, buy shipping, or contact anyone." :back="['href' => route('managed-website.orders.index'), 'label' => 'Orders']" />
            @if($errors->any())<div class="border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-950" role="alert">{{ $errors->first() }}</div>@endif
            <form method="POST" action="{{ route('managed-website.orders.drafts.store') }}" class="border border-zinc-200 bg-white">@csrf
                <div class="grid gap-6 p-5 lg:grid-cols-[1.4fr_.8fr]">
                    <div class="space-y-5">
                        <section><h2 class="text-sm font-semibold text-zinc-950">1. Customer</h2><p class="mt-1 text-xs text-zinc-500">Choose an existing Website customer or capture just enough detail for this draft.</p><label class="mt-3 block text-sm font-medium text-zinc-800">Existing customer<select name="website_customer_id" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"><option value="">Add details below instead</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ trim($customer->first_name.' '.$customer->last_name) ?: $customer->email }}{{ $customer->email ? ' · '.$customer->email : '' }}</option>@endforeach</select></label><div class="mt-3 grid gap-3 sm:grid-cols-2"><label class="text-sm font-medium text-zinc-800">Name<input name="customer_name" value="{{ old('customer_name') }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm" autocomplete="name"></label><label class="text-sm font-medium text-zinc-800">Email<input name="customer_email" value="{{ old('customer_email') }}" type="email" class="mt-1 block w-full rounded-md border-zinc-300 text-sm" autocomplete="email"></label><label class="text-sm font-medium text-zinc-800 sm:col-span-2">Phone<input name="customer_phone" value="{{ old('customer_phone') }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm" autocomplete="tel"></label></div></section>
                        <section class="border-t border-zinc-200 pt-5"><h2 class="text-sm font-semibold text-zinc-950">2. Item</h2><div class="mt-3 grid gap-3 sm:grid-cols-[1fr_120px]"><label class="text-sm font-medium text-zinc-800">Product<select required name="website_product_variant_id" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"><option value="">Choose a product</option>@foreach($variants as $variant)<option value="{{ $variant->id }}" @selected(old('website_product_variant_id') == $variant->id)>{{ $variant->product->title }}{{ $variant->title !== 'Default' ? ' · '.$variant->title : '' }} · ${{ number_format($variant->price_cents / 100, 2) }}</option>@endforeach</select></label><label class="text-sm font-medium text-zinc-800">Quantity<input required name="quantity" type="number" min="1" max="100" value="{{ old('quantity', 1) }}" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"></label></div></section>
                        <section class="border-t border-zinc-200 pt-5"><h2 class="text-sm font-semibold text-zinc-950">3. Fulfillment</h2><label class="mt-3 block text-sm font-medium text-zinc-800">Method<select name="fulfillment_method" class="mt-1 block w-full rounded-md border-zinc-300 text-sm"><option value="pickup">Pickup</option><option value="local_delivery">Local delivery</option><option value="ship">Ship later</option></select></label><label class="mt-3 block text-sm font-medium text-zinc-800">Internal note<textarea name="note" rows="3" class="mt-1 block w-full rounded-md border-zinc-300 text-sm" placeholder="Visible to staff only">{{ old('note') }}</textarea></label></section>
                    </div>
                    <aside class="border-l border-zinc-200 pl-5 text-sm leading-5 text-zinc-600"><h2 class="font-semibold text-zinc-950">What happens next</h2><ol class="mt-3 space-y-3"><li><strong class="text-zinc-900">Save the draft.</strong> It stays in native Website Commerce.</li><li><strong class="text-zinc-900">Review it.</strong> A person can add notes and decide what comes next.</li><li><strong class="text-zinc-900">Nothing starts automatically.</strong> No payment, inventory reservation, carrier call, email, text, or Shopify action occurs.</li></ol></aside>
                </div>
                <div class="flex items-center justify-between border-t border-zinc-200 bg-zinc-50 px-5 py-3"><a class="text-sm font-medium text-zinc-700 hover:underline" href="{{ route('managed-website.orders.index') }}">Cancel</a><button class="fb-btn fb-btn-primary" type="submit">Save draft order</button></div>
            </form>
        </div>
    </flux:main>
</x-layouts::app.sidebar>
