<x-layouts::app.sidebar title="Native shipping">
    <flux:main>
        <div class="mx-auto max-w-6xl space-y-6 pb-12">
            <header><a class="text-sm font-semibold text-emerald-800 hover:underline" href="{{ route('managed-website.orders.index') }}">← Orders</a><p class="mt-6 text-xs font-bold uppercase tracking-[.14em] text-emerald-800">US domestic only</p><h1 class="mt-1 text-3xl font-bold tracking-tight text-zinc-950">Native shipping setup</h1><p class="mt-2 max-w-3xl text-sm leading-6 text-zinc-600">Rates, labels, and tracking use this tenant’s EasyPost connection. This never changes a Shopify carrier account, its shipping queue, or any connected-store fulfillment.</p></header>
            @if(session('status'))<div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-950">{{ session('status') }}</div>@endif
            @if($errors->any())<div class="rounded-xl border border-rose-200 bg-rose-50 px-4 py-3 text-sm font-semibold text-rose-950">{{ $errors->first() }}</div>@endif
            <div class="grid gap-6 lg:grid-cols-2"><section class="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-bold text-zinc-950">Ship-from locations</h2><div class="mt-4 space-y-3">@forelse($locations as $location)<div class="rounded-xl bg-zinc-50 p-3 text-sm"><strong>{{ $location->name }}</strong>@if($location->is_default)<span class="ml-2 rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-900">Default</span>@endif<p class="mt-1 text-zinc-600">{{ data_get($location->address, 'city') }}, {{ data_get($location->address, 'state') }} {{ data_get($location->address, 'zip') }}</p></div>@empty<p class="text-sm text-zinc-500">Add your first US ship-from location.</p>@endforelse</div><form method="POST" action="{{ route('managed-website.commerce.shipping.locations.store') }}" class="mt-6 grid gap-3 sm:grid-cols-2">@csrf<label class="text-sm font-semibold sm:col-span-2">Name<input required name="name" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="text-sm font-semibold sm:col-span-2">Street<input required name="street1" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="text-sm font-semibold sm:col-span-2">Suite / unit<input name="street2" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="text-sm font-semibold">City<input required name="city" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="text-sm font-semibold">State<input required name="state" maxlength="2" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="text-sm font-semibold">ZIP<input required name="zip" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="flex items-end gap-2 text-sm font-semibold"><input type="checkbox" name="is_default" value="1"> Default location</label><button class="fb-btn fb-btn-secondary sm:col-span-2 justify-center" type="submit">Save location</button></form></section>
            <section class="rounded-3xl border border-zinc-200 bg-white p-6 shadow-sm"><h2 class="text-lg font-bold text-zinc-950">Package presets</h2><div class="mt-4 space-y-3">@forelse($packages as $package)<div class="rounded-xl bg-zinc-50 p-3 text-sm"><strong>{{ $package->name }}</strong>@if($package->is_default)<span class="ml-2 rounded-full bg-emerald-100 px-2 py-0.5 text-xs font-bold text-emerald-900">Default</span>@endif<p class="mt-1 text-zinc-600">{{ $package->length_inches }} × {{ $package->width_inches }} × {{ $package->height_inches }} in · {{ $package->weight_ounces }} oz</p></div>@empty<p class="text-sm text-zinc-500">Add a package preset before requesting rates.</p>@endforelse</div><form method="POST" action="{{ route('managed-website.commerce.shipping.packages.store') }}" class="mt-6 grid gap-3 sm:grid-cols-2">@csrf<label class="text-sm font-semibold sm:col-span-2">Preset name<input required name="name" class="mt-1 block w-full rounded-xl border-zinc-300" placeholder="Standard parcel"></label><label class="text-sm font-semibold">Length (in)<input required name="length_inches" type="number" min="1" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="text-sm font-semibold">Width (in)<input required name="width_inches" type="number" min="1" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="text-sm font-semibold">Height (in)<input required name="height_inches" type="number" min="1" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="text-sm font-semibold">Weight (oz)<input required name="weight_ounces" type="number" min="1" class="mt-1 block w-full rounded-xl border-zinc-300"></label><label class="flex items-end gap-2 text-sm font-semibold"><input type="checkbox" name="is_default" value="1"> Default package</label><button class="fb-btn fb-btn-secondary sm:col-span-2 justify-center" type="submit">Save package</button></form></section></div>
        </div>
    </flux:main>
</x-layouts::app.sidebar>
