<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    public function up(): void
    {
        $scents = [
            'Almond Cream Cake',
            'Amber Fog',
            'Appalachian Maple Bourbon',
            'Autumn Leaves',
            'Beard',
            'Butter Pecan',
            'Campfire',
            'Christmas Garland',
            'Cinna Bakery',
            'Cinnamon Broom',
            'Citronella',
            'Coconut Glow',
            'Coffeehouse',
            'Cozy Cabin',
            'Cranberry Apple',
            'Enchanted Forest',
            'Eucalyptus Mint',
            'Fireside Flannel',
            'Forest Spice',
            'Garden Mint',
            'Harvest Apple',
            'Holiday at Sea',
            'Holiday Hike In',
            'Holly Wreath',
            'Honeysuckle',
            'Hot Apple Cider',
            'Lava Rock',
            'Lavender',
            'Magnolia Blossom',
            'Nightfall',
            'Orange Pomander',
            'Orange Sandalwood',
            "Papa's Pipe",
            'Patchouli Teakwood',
            'Peach Orchard',
            'Peppermint Milkshake',
            'Pomegranate Cider',
            'Pumpkin Chai',
            'Pumpkin Spice Latte',
            'Pumpkin Streusel',
            'River Birch',
            'Rosemary',
            "Sippin' Sunshine",
            'Snow Day',
            'Strawberry Jam',
            'Summer Linen',
            'Sunwashed',
            'Thru Hike',
            'Thundershowers',
            'Tomato Leaf',
            'Vanilla',
            'Vanilla Latte',
            'Watermelon',
            'White Tea',
        ];

        foreach ($scents as $scent) {
            DB::table('scents')->updateOrInsert(
                ['name' => $scent],
                [
                    'display_name' => $scent,
                    'is_active' => true,
                    'sort_order' => 0,
                    'updated_at' => now(),
                    'created_at' => now(),
                ]
            );
        }
    }

    public function down(): void
    {
        DB::table('scents')->whereIn('name', [
            'Almond Cream Cake',
            'Amber Fog',
            'Appalachian Maple Bourbon',
            'Autumn Leaves',
            'Beard',
            'Butter Pecan',
            'Campfire',
            'Christmas Garland',
            'Cinna Bakery',
            'Cinnamon Broom',
            'Citronella',
            'Coconut Glow',
            'Coffeehouse',
            'Cozy Cabin',
            'Cranberry Apple',
            'Enchanted Forest',
            'Eucalyptus Mint',
            'Fireside Flannel',
            'Forest Spice',
            'Garden Mint',
            'Harvest Apple',
            'Holiday at Sea',
            'Holiday Hike In',
            'Holly Wreath',
            'Honeysuckle',
            'Hot Apple Cider',
            'Lava Rock',
            'Lavender',
            'Magnolia Blossom',
            'Nightfall',
            'Orange Pomander',
            'Orange Sandalwood',
            "Papa's Pipe",
            'Patchouli Teakwood',
            'Peach Orchard',
            'Peppermint Milkshake',
            'Pomegranate Cider',
            'Pumpkin Chai',
            'Pumpkin Spice Latte',
            'Pumpkin Streusel',
            'River Birch',
            'Rosemary',
            "Sippin' Sunshine",
            'Snow Day',
            'Strawberry Jam',
            'Summer Linen',
            'Sunwashed',
            'Thru Hike',
            'Thundershowers',
            'Tomato Leaf',
            'Vanilla',
            'Vanilla Latte',
            'Watermelon',
            'White Tea',
        ])->delete();
    }
};
