<?php

return [
    'presets' => [
        'modern-forestry' => [
            'display_name' => 'Modern Forestry',
            'profile' => [
                'entity_type' => 's_corporation',
                'country_code' => 'US',
                'state_code' => 'SC',
                'tax_year_basis' => 'calendar',
                'accounting_basis' => 'accrual',
                'configuration' => [
                    'ledger' => 'quickbooks',
                    'payroll_provider' => 'quickbooks_payroll',
                    'income_streams' => ['wholesale', 'online', 'events'],
                    'processors' => ['shopify_payments', 'square'],
                    'expected_accounts' => [
                        'credit_cards' => 2,
                        'checking_and_debit' => null,
                        'lines_of_credit' => 2,
                    ],
                    'event_source' => [
                        'kind' => 'google_drive_spreadsheet',
                        'preferred_source' => 'google_drive',
                        'google_drive_file_id' => '1V9FAzTg6FA7tzEnGyDQDQ-OYgHqbxiBot9PWlj7txDw',
                        'source_url' => 'https://docs.google.com/spreadsheets/d/1V9FAzTg6FA7tzEnGyDQDQ-OYgHqbxiBot9PWlj7txDw/edit',
                        'fallback_filename' => 'Event Team Member Compensation.xlsx',
                        'verification_status' => 'mapping_required',
                    ],
                ],
            ],
            'compliance_tasks' => [
                ['key' => 'federal_payroll_deposits', 'name' => 'Confirm federal payroll-tax deposit schedule', 'jurisdiction' => 'United States', 'obligation' => 'Payroll tax deposits', 'destination_key' => 'eftps', 'quickbooks_expected' => true],
                ['key' => 'form_941', 'name' => 'Review quarterly Form 941 responsibility', 'jurisdiction' => 'United States', 'obligation' => 'Form 941', 'destination_key' => 'quickbooks_payroll', 'quickbooks_expected' => true],
                ['key' => 'form_940_futa', 'name' => 'Review Form 940 and FUTA deposits', 'jurisdiction' => 'United States', 'obligation' => 'Form 940 / FUTA', 'destination_key' => 'eftps', 'quickbooks_expected' => true],
                ['key' => 'federal_year_end', 'name' => 'Confirm W-2 and 1099 responsibilities', 'jurisdiction' => 'United States', 'obligation' => 'W-2 / 1099', 'destination_key' => 'quickbooks_payroll', 'quickbooks_expected' => true],
                ['key' => 'sc_withholding', 'name' => 'Confirm South Carolina withholding frequency', 'jurisdiction' => 'South Carolina', 'obligation' => 'SC withholding', 'destination_key' => 'mydorway', 'quickbooks_expected' => true],
                ['key' => 'sc_wh_1605', 'name' => 'Review WH-1605 quarterly returns', 'jurisdiction' => 'South Carolina', 'obligation' => 'WH-1605', 'destination_key' => 'mydorway', 'quickbooks_expected' => true],
                ['key' => 'sc_wh_1606', 'name' => 'Review WH-1606 annual reconciliation', 'jurisdiction' => 'South Carolina', 'obligation' => 'WH-1606', 'destination_key' => 'mydorway', 'quickbooks_expected' => true],
                ['key' => 'sc_unemployment', 'name' => 'Confirm SC unemployment wage reports and payments', 'jurisdiction' => 'South Carolina', 'obligation' => 'SC unemployment', 'destination_key' => 'suits', 'quickbooks_expected' => false],
                ['key' => 'sc_sales_tax', 'name' => 'Confirm South Carolina sales-tax filing frequency', 'jurisdiction' => 'South Carolina', 'obligation' => 'Sales tax', 'destination_key' => 'mydorway', 'quickbooks_expected' => false],
                ['key' => 'sc_s_corp', 'name' => 'Review South Carolina S-corporation return and license fee', 'jurisdiction' => 'South Carolina', 'obligation' => 'SC S-corporation return', 'destination_key' => 'mydorway', 'quickbooks_expected' => false],
                ['key' => 'owner_estimates', 'name' => 'Confirm federal and state owner estimated-tax reminders', 'jurisdiction' => 'Federal and South Carolina', 'obligation' => 'Owner estimated tax', 'destination_key' => 'irs_payments', 'quickbooks_expected' => false],
                ['key' => 'reasonable_compensation', 'name' => 'Schedule annual reasonable-compensation review', 'jurisdiction' => 'Internal review', 'obligation' => 'Owner compensation review', 'destination_key' => null, 'quickbooks_expected' => false],
            ],
        ],
    ],

    'destinations' => [
        'irs_payments' => ['name' => 'IRS payments', 'url' => 'https://www.irs.gov/payments'],
        'eftps' => ['name' => 'Electronic Federal Tax Payment System', 'url' => 'https://www.eftps.gov/eftps/'],
        'mydorway' => ['name' => 'South Carolina MyDORWAY', 'url' => 'https://mydorway.dor.sc.gov/'],
        'suits' => ['name' => 'South Carolina SUITS', 'url' => 'https://uitax.dew.sc.gov/'],
        'quickbooks_payroll' => ['name' => 'QuickBooks Payroll Tax Center guidance', 'url' => 'https://quickbooks.intuit.com/learn-support/en-us/help-article/electronic-filing/pay-file-payroll-taxes-forms-online-payroll/L8JqxhbaE_US_en_US'],
    ],

    'monthly_close' => [
        'sync_health' => 'Confirm QuickBooks, Shopify, and Square sync health.',
        'financial_accounts' => 'Confirm all bank and card accounts are present.',
        'uncategorised' => 'Review uncategorised transactions.',
        'duplicates' => 'Review duplicate-suspected transactions.',
        'checking_reconciliation' => 'Reconcile checking and debit accounts.',
        'credit_card_reconciliation' => 'Reconcile business credit cards.',
        'loc_reconciliation' => 'Reconcile business lines of credit.',
        'shopify_payouts' => 'Match Shopify Payments payouts to QuickBooks deposits.',
        'square_payouts' => 'Match Square payouts to QuickBooks deposits.',
        'shopify_adjustments' => 'Review Shopify refunds, disputes, gift cards, discounts, and processor fees.',
        'square_adjustments' => 'Review Square refunds, disputes, cash sales, discounts, tips, taxes, and processor fees.',
        'wholesale' => 'Review wholesale invoices, payments, credits, and open receivables.',
        'events' => 'Review event sales and event assignments.',
        'event_profitability' => 'Import or refresh event compensation and profitability data.',
        'payroll_expense' => 'Review payroll expense and payroll liabilities.',
        'payroll_taxes' => 'Confirm payroll taxes were paid or scheduled.',
        'sales_tax' => 'Review sales-tax liability against filed or scheduled returns.',
        'inventory_cogs' => 'Review inventory and cost-of-goods-sold reasonableness.',
        'accounts_payable' => 'Review accounts payable and unpaid bills.',
        'debt' => 'Review debt balances and interest charges.',
        'owner_activity' => 'Review owner draws, distributions, loans, and payroll.',
        'unusual_transactions' => 'Review unusual or material transactions.',
        'profit_loss' => 'Review profit and loss.',
        'balance_sheet' => 'Review balance sheet.',
        'cash_flow' => 'Review cash flow and upcoming obligations.',
        'supporting_documents' => 'Upload or link supporting close documents.',
        'owner_approval' => 'Owner approves the month.',
        'close_period' => 'Mark the period closed in Everbranch.',
    ],
];
