<?php

return [
    'templates' => [
        'retail_contact' => [
            'key' => 'retail_contact',
            'name' => 'Retail Contact',
            'description' => 'Retail customer contact form staged as a Storeify replacement.',
            'status' => 'draft',
            'visibility' => 'internal',
            'handler_key' => 'retail_contact',
            'schema' => ['version' => 1, 'fields' => []],
            'default_form' => [
                'slug' => 'retail-contact',
                'name' => 'Contact Us',
                'status' => 'draft',
                'channel' => 'retail_storefront_candidate',
                'destination' => ['notifications_enabled' => false],
                'settings' => ['candidate_only' => true],
            ],
        ],
        'retail_job_opportunity' => [
            'key' => 'retail_job_opportunity',
            'name' => 'Retail Job Opportunity',
            'description' => 'Job interest form staged as a Storeify replacement.',
            'status' => 'draft',
            'visibility' => 'internal',
            'handler_key' => 'retail_job_opportunity',
            'schema' => ['version' => 1, 'fields' => []],
            'default_form' => [
                'slug' => 'job-opportunity',
                'name' => 'Job Opportunity',
                'status' => 'draft',
                'channel' => 'retail_storefront_candidate',
                'destination' => ['notifications_enabled' => false],
                'settings' => ['candidate_only' => true],
            ],
        ],
        'legacy_forestry_weekend' => [
            'key' => 'legacy_forestry_weekend',
            'name' => 'Forestry Weekend (Archive)',
            'description' => 'Searchable Storeify history. This form cannot publish.',
            'status' => 'archived',
            'visibility' => 'internal',
            'handler_key' => 'archive_only',
            'schema' => ['version' => 1, 'fields' => []],
            'default_form' => [
                'slug' => 'legacy-forestry-weekend-2024',
                'name' => 'Forestry Weekend May 2024',
                'status' => 'archived',
                'channel' => 'history_only',
                'destination' => ['notifications_enabled' => false],
                'settings' => ['archive_only' => true, 'publishable' => false],
            ],
        ],
        'legacy_storeify_wholesale_application' => [
            'key' => 'legacy_storeify_wholesale_application',
            'name' => 'Retail Wholesale Application (Archive)',
            'description' => 'Searchable retail-store history. New wholesale traffic uses the wholesale gateway.',
            'status' => 'archived',
            'visibility' => 'internal',
            'handler_key' => 'archive_only',
            'schema' => ['version' => 1, 'fields' => []],
            'default_form' => [
                'slug' => 'legacy-storeify-wholesale-application',
                'name' => 'Wholesale Application (Retail Archive)',
                'status' => 'archived',
                'channel' => 'history_only',
                'destination' => ['gateway' => 'https://modernforestrywholesale.com', 'notifications_enabled' => false],
                'settings' => ['archive_only' => true, 'publishable' => false],
            ],
        ],
        'wholesale_application' => [
            'key' => 'wholesale_application',
            'name' => 'Wholesale Application',
            'description' => 'Wholesale-only intake form for prospective stockists and buyers.',
            'status' => 'active',
            'visibility' => 'internal',
            'handler_key' => 'wholesale_application',
            'schema' => [
                'version' => 1,
                'fields' => [
                    ['key' => 'name', 'type' => 'text', 'label' => 'Full name', 'required' => true],
                    ['key' => 'email', 'type' => 'email', 'label' => 'Email', 'required' => true],
                    ['key' => 'phone', 'type' => 'text', 'label' => 'Phone', 'required' => true],
                    ['key' => 'company', 'type' => 'text', 'label' => 'Company', 'required' => true],
                    ['key' => 'store_type', 'type' => 'text', 'label' => 'Store type', 'required' => false],
                    ['key' => 'website', 'type' => 'url', 'label' => 'Website', 'required' => false],
                    ['key' => 'address', 'type' => 'text', 'label' => 'Address', 'required' => false],
                    ['key' => 'address2', 'type' => 'text', 'label' => 'Address line 2', 'required' => false],
                    ['key' => 'city', 'type' => 'text', 'label' => 'City', 'required' => false],
                    ['key' => 'state', 'type' => 'text', 'label' => 'State', 'required' => false],
                    ['key' => 'zip', 'type' => 'text', 'label' => 'Postal / ZIP', 'required' => false],
                    ['key' => 'country', 'type' => 'text', 'label' => 'Country', 'required' => false],
                    ['key' => 'position', 'type' => 'text', 'label' => 'Position', 'required' => false],
                    ['key' => 'referral', 'type' => 'text', 'label' => 'Referral source', 'required' => false],
                    ['key' => 'current_suppliers', 'type' => 'text', 'label' => 'Current suppliers', 'required' => false],
                    ['key' => 'retail_license_number', 'type' => 'text', 'label' => 'Retail license / resale number', 'required' => false],
                    ['key' => 'contact_preference', 'type' => 'select', 'label' => 'Contact preference', 'required' => false],
                    ['key' => 'business_info', 'type' => 'textarea', 'label' => 'Business info', 'required' => false],
                    ['key' => 'agreement', 'type' => 'checkbox', 'label' => 'Agreement accepted', 'required' => true],
                ],
            ],
            'default_form' => [
                'slug' => 'wholesale-application',
                'name' => 'Wholesale Application',
                'description' => 'Modern Forestry Wholesale application intake.',
                'status' => 'active',
                'channel' => 'wholesale_storefront',
                'destination' => [
                    'review_email' => env('WHOLESALE_APPLICATION_REVIEW_EMAIL', 'modernforestryteam@gmail.com'),
                    'create_shopify_customer' => true,
                    'apply_wholesale_tag_on_submit' => false,
                ],
            ],
        ],
    ],
];
