<?php

$catalog = [
    'defaults' => [
        'plan' => env('TENANT_ENTITLEMENTS_DEFAULT_PLAN', 'starter'),
        'operating_mode' => env('TENANT_ENTITLEMENTS_DEFAULT_MODE', 'shopify'),
        'setup_statuses' => [
            'not_started',
            'in_progress',
            'configured',
            'blocked',
        ],
    ],

    'legacy' => [
        'plan_aliases' => [
            'shopify_proof_of_concept' => 'starter',
            'shopify_growth' => 'growth',
            'direct_starter' => 'base',
            'base_workspace' => 'base',
            'field_service_starter' => 'base',
        ],
        'addon_aliases' => [
            'advanced_reporting' => 'advanced_reporting',
            'referrals_pack' => 'referrals',
            'vip_pack' => 'vip_pack',
            'integrations_pack' => 'integrations_pack',
            'ai_brain' => 'future_niche_modules',
        ],
        'module_aliases' => [
            'advanced_reporting' => 'diagnostics_advanced',
            'marketing_email' => 'bulk_email_marketing',
            'extra_channels' => 'additional_channels',
            'future_modules' => 'future_niche_modules',
            'work' => 'field_service',
            'jobs' => 'field_service',
            'job_addresses' => 'field_service',
            'tasks' => 'field_service',
            'assignments' => 'field_service',
            'materials' => 'field_service',
            'parts' => 'field_service',
            'work_vans' => 'field_service',
            'vehicles' => 'field_service',
            'photos' => 'field_service',
            'files' => 'field_service',
        ],
    ],

    'alpha_overrides' => [
        // Protected alpha tenant override for AI Assistant access.
        'ai_assistant' => [
            'tenant_ids' => [],
            'tenant_slugs' => ['modern-forestry'],
            'tenant_names' => ['Modern Forestry'],
        ],
    ],

    'capabilities' => [
        'dashboard.overview' => [
            'display_name' => 'Overview dashboard',
            'description' => 'Baseline overview and shell access.',
            'module_key' => 'dashboard',
        ],
        'customers.manage' => [
            'display_name' => 'Customer management',
            'description' => 'Manage customer profiles, notes, and identity-linked data.',
            'module_key' => 'customers',
        ],
        'field_service.workspace' => [
            'display_name' => 'Field service workspace',
            'description' => 'Track customers, jobs, addresses, tasks, materials, photos, and work vehicles.',
            'module_key' => 'field_service',
        ],
        'field_service.jobs' => [
            'display_name' => 'Service jobs',
            'description' => 'Create and manage service jobs for customers.',
            'module_key' => 'field_service',
        ],
        'field_service.materials' => [
            'display_name' => 'Materials and parts',
            'description' => 'Track parts, materials, and simple job costs.',
            'module_key' => 'field_service',
        ],
        'field_service.vehicles' => [
            'display_name' => 'Vehicles',
            'description' => 'Track work vans and field vehicles.',
            'module_key' => 'field_service',
        ],
        'activity.timeline' => [
            'display_name' => 'Customer activity timeline',
            'description' => 'View customer activity and engagement context.',
            'module_key' => 'activity',
        ],
        'questions.queue' => [
            'display_name' => 'Questions queue',
            'description' => 'Internal workflow for unresolved questions and follow-up.',
            'module_key' => 'questions',
        ],
        'rewards.program' => [
            'display_name' => 'Rewards program',
            'description' => 'Configure and operate rewards earn and redeem behavior.',
            'module_key' => 'rewards',
        ],
        'birthdays.lifecycle' => [
            'display_name' => 'Birthday lifecycle',
            'description' => 'Run birthday-triggered messaging and reward flows.',
            'module_key' => 'birthdays',
        ],
        'reviews.collect' => [
            'display_name' => 'Review collection',
            'description' => 'Collect, moderate, and display product reviews.',
            'module_key' => 'reviews',
        ],
        'lead_capture.intake' => [
            'display_name' => 'Lead capture intake',
            'description' => 'Capture leads, intake submissions, and funnel entry points.',
            'module_key' => 'lead_capture',
        ],
        'wishlist.manage' => [
            'display_name' => 'Wishlist management',
            'description' => 'Store and manage customer wishlist activity.',
            'module_key' => 'wishlist',
        ],
        'referrals.program' => [
            'display_name' => 'Referrals program',
            'description' => 'Referral acquisition and reward tracking.',
            'module_key' => 'referrals',
        ],
        'vip.tiers' => [
            'display_name' => 'VIP tiers',
            'description' => 'Tiered loyalty and VIP customer programs.',
            'module_key' => 'vip',
        ],
        'notifications.messaging' => [
            'display_name' => 'Notifications',
            'description' => 'Notification templates and message triggers.',
            'module_key' => 'notifications',
        ],
        'campaigns.orchestration' => [
            'display_name' => 'Campaign orchestration',
            'description' => 'Create and manage audience and lifecycle campaigns.',
            'module_key' => 'campaigns',
        ],
        'reporting.analytics' => [
            'display_name' => 'Reporting analytics',
            'description' => 'Core reporting and analytics surfaces.',
            'module_key' => 'reporting',
        ],
        'diagnostics.advanced' => [
            'display_name' => 'Advanced diagnostics',
            'description' => 'Deeper troubleshooting and export diagnostics.',
            'module_key' => 'diagnostics_advanced',
        ],
        'integrations.registry' => [
            'display_name' => 'Integration registry',
            'description' => 'Read-only integration states and setup guidance.',
            'module_key' => 'integrations',
        ],
        'uploads.imports' => [
            'display_name' => 'Uploads and imports',
            'description' => 'Manual import and CSV-based onboarding utilities.',
            'module_key' => 'uploads',
        ],
        'documents.manage' => [
            'display_name' => 'Documents',
            'description' => 'Private tenant files that can be searched and linked to field jobs.',
            'module_key' => 'documents',
        ],
        'estimator.drafts' => [
            'display_name' => 'Estimator',
            'description' => 'Owner-reviewed price book items and persistent estimate drafts.',
            'module_key' => 'estimator',
        ],
        'onboarding.checklist' => [
            'display_name' => 'Onboarding checklist',
            'description' => 'Guided setup and module readiness checklist.',
            'module_key' => 'onboarding',
        ],
        'settings.tenant' => [
            'display_name' => 'Tenant settings',
            'description' => 'Tenant-level settings and configuration controls.',
            'module_key' => 'settings',
        ],
        'shopify.connection' => [
            'display_name' => 'Shopify connection',
            'description' => 'Shopify embedded and storefront-specific context.',
            'module_key' => 'shopify',
        ],
        'shopify.product_options' => [
            'display_name' => 'Shopify product options',
            'description' => 'Assign scent rulesets to Shopify bundle products and capture selections as line-item properties.',
            'module_key' => 'shopify_product_options',
        ],
        'quickbooks.sync' => [
            'display_name' => 'QuickBooks sync',
            'description' => 'Accounting connector and sync readiness.',
            'module_key' => 'quickbooks',
        ],
        'wix.sync' => [
            'display_name' => 'Wix sync',
            'description' => 'Wix channel connector and setup state.',
            'module_key' => 'wix',
        ],
        'square.sync' => [
            'display_name' => 'Square sync',
            'description' => 'Square commerce connection and data ingestion.',
            'module_key' => 'square',
        ],
        'workflow.automations' => [
            'display_name' => 'Workflow automations',
            'description' => 'Zap-style trigger/action automations powered by the first-party scheduler and queue.',
            'module_key' => 'workflow_automations',
        ],
        'email.channel' => [
            'display_name' => 'Email channel',
            'description' => 'Email provider readiness and messaging channel support.',
            'module_key' => 'email',
        ],
        'sms.channel' => [
            'display_name' => 'SMS channel',
            'description' => 'SMS messaging setup and provider readiness.',
            'module_key' => 'sms',
        ],
        'mobile.connection' => [
            'display_name' => 'Mobile connection',
            'description' => 'Future mobile channel connection surface.',
            'module_key' => 'mobile_connection',
        ],
        'ai.assistant' => [
            'display_name' => 'AI Assistant',
            'description' => 'Guided AI assistant workspace for opportunities, setup, and review-ready drafts.',
            'module_key' => 'ai',
            'minimum_plan' => 'growth',
            'status' => 'beta',
        ],
        'ai.start_here' => [
            'display_name' => 'Start Here',
            'description' => 'Get oriented with AI Assistant readiness and next steps.',
            'module_key' => 'ai',
            'minimum_plan' => 'growth',
            'status' => 'beta',
        ],
        'ai.opportunities' => [
            'display_name' => 'Top Opportunities',
            'description' => 'Review high-impact opportunities before preparing campaign drafts.',
            'module_key' => 'ai',
            'minimum_plan' => 'growth',
            'status' => 'beta',
        ],
        'ai.draft_campaigns' => [
            'display_name' => 'Draft Campaigns',
            'description' => 'Prepare draft campaigns that always require human review before sending.',
            'module_key' => 'ai',
            'minimum_plan' => 'pro',
            'status' => 'beta',
        ],
        'ai.setup' => [
            'display_name' => 'Setup',
            'description' => 'Track prerequisite setup states for AI-assisted workflows.',
            'module_key' => 'ai',
            'minimum_plan' => 'growth',
            'status' => 'beta',
        ],
        'ai.activity' => [
            'display_name' => 'Activity',
            'description' => 'Review recent AI-relevant workspace signals and trend context.',
            'module_key' => 'ai',
            'minimum_plan' => 'pro',
            'status' => 'beta',
        ],
        'bulk_email.campaigns' => [
            'display_name' => 'Bulk email marketing',
            'description' => 'Marketing email campaigns and higher-volume send workflows.',
            'module_key' => 'bulk_email_marketing',
        ],
        'channels.additional' => [
            'display_name' => 'Additional channels',
            'description' => 'Expand beyond the base store or channel allowance.',
            'module_key' => 'additional_channels',
        ],
        'subscriptions.manage' => [
            'display_name' => 'Subscriptions',
            'description' => 'Manage Shopify-backed subscription contracts, billing attempts, and customer lifecycle actions.',
            'module_key' => 'subscriptions',
        ],
        'subscriptions.migration' => [
            'display_name' => 'Subscription migration',
            'description' => 'Run Recharge dry-runs, reconciliations, and approved cutovers into Shopify subscriptions.',
            'module_key' => 'subscriptions',
        ],
        'subscriptions.candle_club' => [
            'display_name' => 'Subscription plan rules',
            'description' => 'Configure subscription commitments, pauses, gifts, swaps, cancellations, and rewards.',
            'module_key' => 'subscriptions',
        ],
        'subscriptions.voting' => [
            'display_name' => 'Subscription voting',
            'description' => 'Operate one-vote-per-active-contract polls across app, storefront, and verified public links.',
            'module_key' => 'subscriptions',
        ],
        'future.modules' => [
            'display_name' => 'Future niche modules',
            'description' => 'Reserved niche/vertical module packaging.',
            'module_key' => 'future_niche_modules',
        ],
        'messaging.workspace' => [
            'display_name' => 'Messaging workspace',
            'description' => 'Direct 1:1 and group messaging workspace for SMS and email outreach.',
            'module_key' => 'messaging',
        ],
        'messaging.analytics' => [
            'display_name' => 'Message analytics',
            'description' => 'Operational analytics for message opens, clicks, and attributed orders.',
            'module_key' => 'messaging',
        ],
        'wholesale.overview' => ['display_name' => 'Wholesale overview', 'description' => 'View wholesale-only operational metrics.', 'module_key' => 'wholesale_operations'],
        'wholesale.suggestions.view' => ['display_name' => 'View wholesale suggestions', 'description' => 'Review explainable wholesale recommendations.', 'module_key' => 'wholesale_operations'],
        'wholesale.suggestions.decide' => ['display_name' => 'Decide wholesale suggestions', 'description' => 'Accept, dismiss, snooze, or convert suggestions.', 'module_key' => 'wholesale_operations'],
        'wholesale.customers.view' => ['display_name' => 'View wholesale customers', 'description' => 'View qualified wholesale accounts and history.', 'module_key' => 'wholesale_operations'],
        'wholesale.customers.manage' => ['display_name' => 'Manage wholesale customers', 'description' => 'Manage wholesale relationship details.', 'module_key' => 'wholesale_operations'],
        'wholesale.orders.view' => ['display_name' => 'View wholesale orders', 'description' => 'View qualified wholesale order history.', 'module_key' => 'wholesale_operations'],
        'wholesale.follow_ups.manage' => ['display_name' => 'Manage wholesale follow-ups', 'description' => 'Create and complete wholesale follow-ups.', 'module_key' => 'wholesale_operations'],
        'wholesale.classification.resolve' => ['display_name' => 'Resolve wholesale classifications', 'description' => 'Confirm or reject ambiguous legacy classifications.', 'module_key' => 'wholesale_operations'],
        'wholesale.prospects.view' => ['display_name' => 'View wholesale prospects', 'description' => 'Review discovered wholesale prospects.', 'module_key' => 'wholesale_operations'],
        'wholesale.prospects.discover' => ['display_name' => 'Discover wholesale prospects', 'description' => 'Run controlled approved prospect searches.', 'module_key' => 'wholesale_operations'],
    ],

    'modules' => [
        'dashboard' => [
            'display_name' => 'Overview',
            'description' => 'Baseline overview, shell access, and account context.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['shopify'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shopify-only',
            'included_in_plans' => ['base', 'starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['dashboard.overview'],
            'mobile' => [
                'status' => 'ready',
                'display_name' => 'Home Branch',
                'renderer' => 'dashboard',
                'entry_screen' => 'home',
                'contract_version' => 2,
                'min_app_version' => '1.1.0',
                'navigation' => ['group' => 'home', 'icon' => 'house', 'position' => 0],
                'actions' => ['view'],
            ],
        ],
        'wholesale_operations' => [
            'display_name' => 'Wholesale Operations',
            'label' => 'Wholesale Operations',
            'description' => 'Wholesale-only decisions, customer history, follow-ups, classifications, and prospect review.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['shopify'],
            'shopify_embedded_surfaces' => ['wholesale'],
            'required_shopify_store_role' => 'wholesale',
            'classification' => 'shopify-only',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['shopify'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => true, 'mobile_store' => false],
            'cta_routing' => 'none',
            'short_description' => 'Run wholesale decisions from a dedicated Shopify store.',
            'long_description' => 'Review wholesale customers, orders, follow-ups, applications, suggestions, and prospect discovery without exposing retail-store data.',
            'category' => 'customer_operations',
            'setup_effort' => 'light',
            'required_integrations' => ['shopify'],
            'mobile_relevance' => 'not_mobile_specific',
            'buyer_setup' => [
                'outcome' => 'Keep wholesale customer decisions, order history, applications, follow-ups, and prospects in one tenant-owned workspace.',
                'best_for' => 'Shopify merchants that operate a separate store dedicated to wholesale orders.',
                'what_you_need' => [
                    'An existing Shopify connection owned by this tenant.',
                    'A tenant owner or admin who can confirm that the selected store is wholesale-only.',
                ],
                'next_step' => 'Choose and confirm the dedicated wholesale store from the Module Store setup screen.',
                'setup_steps' => [
                    'Connect the Shopify store through the established integration setup.',
                    'Confirm that the store is dedicated to wholesale orders.',
                    'Review the tenant discovery profile before running prospect searches.',
                ],
                'primary_action' => 'Set up module',
                'help_text' => 'Retail stores on the same tenant remain unable to reveal or open Wholesale Operations.',
            ],
            'capabilities' => [
                'wholesale.overview',
                'wholesale.suggestions.view',
                'wholesale.suggestions.decide',
                'wholesale.customers.view',
                'wholesale.customers.manage',
                'wholesale.orders.view',
                'wholesale.follow_ups.manage',
                'wholesale.classification.resolve',
                'wholesale.prospects.view',
                'wholesale.prospects.discover',
            ],
        ],
        'shopify_product_options' => [
            'display_name' => 'Product Options',
            'label' => 'Product Options',
            'description' => 'Control which scents appear on Shopify bundle products and how many selections each product requires.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['shopify'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shopify-only',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['shopify'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false, 'mobile_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['shopify.product_options'],
        ],
        'customers' => [
            'display_name' => 'Customers',
            'description' => 'Manage customer profiles, identity, and operator context.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shared-core',
            'included_in_plans' => ['base', 'starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['customers.manage'],
            'mobile' => [
                'status' => 'ready',
                'display_name' => 'Customers Branch',
                'renderer' => 'list',
                'entry_screen' => 'customers.index',
                'contract_version' => 2,
                'min_app_version' => '1.1.0',
                'navigation' => ['group' => 'work', 'icon' => 'users-round', 'position' => 10],
                'actions' => ['view', 'search'],
            ],
        ],
        'work_core' => [
            'display_name' => 'Work',
            'description' => 'Daily work for this team.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['base', 'starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false, 'mobile_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['mobile.work'],
            'mobile' => [
                'status' => 'ready',
                'display_name' => 'Work Branch',
                'renderer' => 'vertical_work',
                'entry_screen' => 'work.index',
                'contract_version' => 2,
                'min_app_version' => '1.1.0',
                'navigation' => ['group' => 'work', 'icon' => 'briefcase-business', 'position' => 5],
                'actions' => ['view', 'search', 'capture_photo'],
            ],
        ],
        'field_service' => [
            'display_name' => 'Field Service',
            'description' => 'Keep customers, service jobs, addresses, tasks, materials, photos, and work vans together.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['backstage'],
            'classification' => 'shared-core',
            'included_in_plans' => ['base'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'none',
            'short_description' => 'Run service work without Shopify.',
            'long_description' => 'A simple field-service workspace for customers, job addresses, work orders, materials, tasks, photos, and vehicles.',
            'category' => 'customer_operations',
            'setup_effort' => 'light',
            'required_integrations' => [],
            'mobile_relevance' => 'mobile_ready',
            'buyer_setup' => [
                'outcome' => 'Keep service jobs, customers, materials, photos, and vehicles in one shared workspace.',
                'best_for' => 'Service businesses that need a simple operating hub without depending on Shopify.',
                'what_you_need' => [
                    'A list of the jobs, addresses, or service requests you want to track first.',
                    'A team owner who can confirm job statuses and daily follow-up habits.',
                ],
                'next_step' => 'Start by adding the first active jobs and assigning who owns each next step.',
                'setup_steps' => [
                    'Confirm the customer records you want to manage.',
                    'Add or import the first jobs and addresses.',
                    'Review materials, photos, and vehicle tracking with the people doing the work.',
                ],
                'primary_action' => 'Open field service',
                'help_text' => 'This module can be used as a standalone workspace for service teams.',
            ],
            'capabilities' => [
                'field_service.workspace',
                'field_service.jobs',
                'field_service.materials',
                'field_service.vehicles',
            ],
            'mobile' => [
                'status' => 'ready',
                'display_name' => 'Field Service',
                'renderer' => 'field_service',
                'entry_screen' => 'field-service.index',
                'contract_version' => 3,
                'min_app_version' => '1.3.0',
                'navigation' => ['group' => 'work', 'icon' => 'calendar-days', 'position' => 5],
                'actions' => ['view', 'create_job', 'capture_photo', 'add_note', 'assign', 'comment'],
            ],
        ],
        'class_scheduling' => [
            'display_name' => 'Class Scheduling',
            'description' => 'Publish classes, manage a calendar, enroll customers, and schedule class reminders.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['backstage'],
            'classification' => 'shared-core',
            'included_in_plans' => ['base', 'starter', 'growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'none',
            'short_description' => 'Turn classes and workshops into a customer-ready calendar.',
            'long_description' => 'Create scheduled class sessions, publish available seats, collect customer signups, open attendee records, and schedule email or SMS reminders through the tenant messaging layer.',
            'category' => 'customer_operations',
            'setup_effort' => 'light',
            'required_integrations' => [],
            'mobile_relevance' => 'mobile_ready',
            'buyer_setup' => [
                'outcome' => 'Keep the public class calendar, enrollment list, customer records, and reminders together.',
                'best_for' => 'Educators, consultants, makers, food businesses, and service teams that run scheduled classes or workshops.',
                'what_you_need' => [
                    'The class names, dates, capacities, locations, and prices you want to publish.',
                    'A verified email or SMS provider before live reminders are sent.',
                ],
                'next_step' => 'Create the first class, review the public signup page, and confirm reminder timing.',
                'setup_steps' => [
                    'Set the public signup branding and contact details.',
                    'Add upcoming classes with dates, capacity, and registration status.',
                    'Verify messaging providers and customer consent before enabling live deliveries.',
                ],
                'primary_action' => 'Open class calendar',
                'help_text' => 'Signups create or update tenant-scoped customer profiles; reminder delivery still follows tenant provider and consent rules.',
            ],
            'capabilities' => [
                'class_scheduling.calendar',
                'class_scheduling.classes',
                'class_scheduling.enrollments',
                'class_scheduling.reminders',
                'class_scheduling.public_signup',
            ],
            'mobile' => [
                'status' => 'beta',
                'display_name' => 'Class Scheduling',
                'renderer' => 'class_scheduling',
                'entry_screen' => 'class-scheduling.index',
                'contract_version' => 2,
                'min_app_version' => '2.0.0',
                'navigation' => ['group' => 'work', 'icon' => 'calendar-days', 'position' => 8],
                'actions' => ['view', 'open_customer', 'message_customer', 'schedule_reminder'],
            ],
        ],
        'activity' => [
            'display_name' => 'Activity',
            'description' => 'Customer activity timeline and engagement feed.',
            'status' => 'placeholder',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shared-core',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'request_access',
            'capabilities' => ['activity.timeline'],
        ],
        'questions' => [
            'display_name' => 'Questions',
            'description' => 'Internal support and follow-up workflow.',
            'status' => 'placeholder',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['backstage'],
            'classification' => 'internal-admin',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['questions.queue'],
        ],
        'rewards' => [
            'display_name' => 'Rewards',
            'description' => 'Operate the loyalty and rewards program.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shared-core',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'upgrade_plan',
            'buyer_setup' => [
                'outcome' => 'Give customers a clear loyalty program and keep reward rules in one place.',
                'best_for' => 'Stores that want repeat customers to earn, redeem, and understand rewards without manual tracking.',
                'what_you_need' => [
                    'A decision on how customers earn points or credit.',
                    'A decision on the reward values customers can redeem.',
                ],
                'next_step' => 'Review the reward rules you want customers to see, then enable the module on an eligible plan.',
                'setup_steps' => [
                    'Confirm earn and redeem rules.',
                    'Review customer-facing reward language.',
                    'Test one customer journey before announcing the program.',
                ],
                'primary_action' => 'Review rewards',
                'help_text' => 'Rewards setup should be simple enough for a business owner to approve before launch.',
            ],
            'capabilities' => ['rewards.program'],
        ],
        'birthdays' => [
            'display_name' => 'Birthdays / Lifecycle',
            'description' => 'Birthday-triggered lifecycle messaging and rewards.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shared-core',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers', 'rewards'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'upgrade_plan',
            'buyer_setup' => [
                'outcome' => 'Turn birthdays and lifecycle moments into timely customer follow-up.',
                'best_for' => 'Teams that want automatic birthday or lifecycle nudges tied to customer records and rewards.',
                'what_you_need' => [
                    'Customer birthday or lifecycle data where available.',
                    'A decision on the offer or message customers should receive.',
                ],
                'next_step' => 'Confirm the lifecycle moment you want to start with and connect it to the right customer message.',
                'setup_steps' => [
                    'Review the customer date fields available in the workspace.',
                    'Choose the birthday or lifecycle message.',
                    'Test the workflow with a small customer sample.',
                ],
                'primary_action' => 'Plan lifecycle setup',
                'help_text' => 'Start with one simple lifecycle moment before adding more automation.',
            ],
            'capabilities' => ['birthdays.lifecycle'],
        ],
        'reviews' => [
            'display_name' => 'Reviews',
            'description' => 'Collect, moderate, and display native reviews.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['reviews.collect'],
        ],
        'lead_capture' => [
            'display_name' => 'Lead Capture / Intake',
            'description' => 'Capture leads and intake requests into the customer system.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['lead_capture.intake'],
        ],
        'wishlist' => [
            'display_name' => 'Wishlist',
            'description' => 'Track and activate wishlist-driven retention workflows.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['pro'],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'upgrade_plan',
            'buyer_setup' => [
                'outcome' => 'See what customers save for later and turn that interest into follow-up.',
                'best_for' => 'Stores that want a practical way to recover saved-product interest without guessing.',
                'what_you_need' => [
                    'Wishlist or saved-item data from your storefront or import path.',
                    'A simple outreach plan for products customers saved.',
                ],
                'next_step' => 'Review saved-item activity, then decide which customers should receive the first follow-up.',
                'setup_steps' => [
                    'Confirm wishlist data is flowing or imported.',
                    'Review the most saved products and customer candidates.',
                    'Prepare one small outreach batch before scaling up.',
                ],
                'primary_action' => 'Review wishlist',
                'help_text' => 'Wishlist follow-up works best when the first campaign is small and easy to verify.',
            ],
            'capabilities' => ['wishlist.manage'],
        ],
        'referrals' => [
            'display_name' => 'Referrals',
            'description' => 'Referral acquisition and reward workflows.',
            'status' => 'placeholder',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['rewards'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'request_access',
            'capabilities' => ['referrals.program'],
        ],
        'vip' => [
            'display_name' => 'VIP',
            'description' => 'Tier-based loyalty and VIP configuration.',
            'status' => 'placeholder',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['rewards'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['vip.tiers'],
        ],
        'notifications' => [
            'display_name' => 'Notifications',
            'description' => 'Notification templates and customer messaging triggers.',
            'status' => 'placeholder',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['notifications.messaging'],
        ],
        'campaigns' => [
            'display_name' => 'Campaigns',
            'description' => 'Audience and lifecycle campaign management.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'upgrade_plan',
            'buyer_setup' => [
                'outcome' => 'Build focused customer campaigns from the audiences already in the workspace.',
                'best_for' => 'Teams that want planned customer outreach without juggling lists across multiple tools.',
                'what_you_need' => [
                    'A customer segment or audience idea.',
                    'A message goal, such as winback, launch, review request, or lifecycle follow-up.',
                ],
                'next_step' => 'Choose the first audience and draft the campaign goal before sending anything.',
                'setup_steps' => [
                    'Pick the customer audience.',
                    'Draft the message and call to action.',
                    'Review send readiness and approval rules.',
                ],
                'primary_action' => 'Plan campaign',
                'help_text' => 'Campaigns should stay human-reviewed until the buyer is confident in the workflow.',
            ],
            'capabilities' => ['campaigns.orchestration'],
        ],
        'reporting' => [
            'display_name' => 'Reporting',
            'description' => 'Core reporting and analytics surfaces.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['reporting.analytics'],
            'mobile' => [
                'status' => 'ready',
                'display_name' => 'Reporting Branch',
                'renderer' => 'dashboard',
                'entry_screen' => 'reporting.overview',
                'contract_version' => 2,
                'min_app_version' => '1.1.0',
                'navigation' => ['group' => 'work', 'icon' => 'chart-no-axes-combined', 'position' => 40],
                'actions' => ['view'],
            ],
        ],
        'diagnostics_advanced' => [
            'display_name' => 'Advanced Diagnostics',
            'description' => 'Advanced diagnostics, exports, and troubleshooting.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['pro'],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['reporting'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'upgrade_plan',
            'buyer_setup' => [
                'outcome' => 'Give operators deeper troubleshooting and export tools when something needs investigation.',
                'best_for' => 'Teams that need clearer answers around data quality, sync health, or support questions.',
                'what_you_need' => [
                    'A workspace owner who can review diagnostics.',
                    'A clear question or issue you want to investigate first.',
                ],
                'next_step' => 'Use diagnostics when the team needs proof, exports, or a clear support handoff.',
                'setup_steps' => [
                    'Confirm who is allowed to review diagnostic data.',
                    'Open the first report or export needed for the issue.',
                    'Document the result before making operational changes.',
                ],
                'primary_action' => 'Review diagnostics',
                'help_text' => 'This module is for support clarity and operational confidence, not daily customer work.',
            ],
            'capabilities' => ['diagnostics.advanced'],
        ],
        'integrations' => [
            'display_name' => 'Integrations',
            'description' => 'Integration setup states and fallback-first connector guidance.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'integration-layer',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'not_started',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['integrations.registry'],
        ],
        'uploads' => [
            'display_name' => 'Uploads / Imports',
            'description' => 'CSV and manual import workflows.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'not_started',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['uploads.imports'],
        ],
        'onboarding' => [
            'display_name' => 'Onboarding',
            'description' => 'Tenant onboarding and setup guidance.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'not_started',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['onboarding.checklist'],
        ],
        'settings' => [
            'display_name' => 'Settings',
            'description' => 'Tenant settings and environment configuration.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['settings.tenant'],
        ],
        'shopify' => [
            'display_name' => 'Shopify',
            'description' => 'Shopify embedded, proxy, and store-linked surfaces.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['shopify'],
            'classification' => 'shopify-only',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['shopify.connection'],
        ],
        'quickbooks' => [
            'display_name' => 'QuickBooks',
            'description' => 'Read-only QuickBooks connection, guided import, and accounting insight for workspace owners.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['integrations'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => false],
            'cta_routing' => 'add_module',
            'buyer_setup' => [
                'outcome' => 'Bring QuickBooks customers, estimates, invoices, notes, and service items into an operational workspace.',
                'best_for' => 'Owners who want field work and accounting context connected without giving employees access to financial reports.',
                'what_you_need' => [
                    'QuickBooks Online administrator access.',
                    'An Everbranch workspace owner or administrator to approve the connection.',
                ],
                'next_step' => 'Enable the Branch, connect the correct QuickBooks company, and review a dry-run audit before importing.',
                'setup_steps' => [
                    'Confirm the target Everbranch workspace and QuickBooks company.',
                    'Authorize a read-only accounting connection.',
                    'Review the dry-run counts and mappings before the first import.',
                ],
                'primary_action' => 'Connect QuickBooks',
                'help_text' => 'QuickBooks access is owner/admin only, tenant-scoped, and imported on demand during beta.',
            ],
            'capabilities' => ['quickbooks.sync'],
        ],
        'documents' => [
            'display_name' => 'Documents',
            'description' => 'Searchable private files, photos, and job-linked assets.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['uploads'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'add_module',
            'buyer_setup' => [
                'outcome' => 'Keep job photos and business files searchable and attached to the work they support.',
                'best_for' => 'Teams replacing shared photo albums and scattered folders with tenant-owned job records.',
                'what_you_need' => ['A workspace administrator to choose file visibility and retention rules.'],
                'next_step' => 'Enable Documents, upload or select the first files, and link them to jobs.',
                'setup_steps' => ['Confirm team and owner-only visibility.', 'Upload files or select photos from the device library.', 'Link each asset to one or more jobs.'],
                'primary_action' => 'Open Documents',
                'help_text' => 'Selected iCloud photos are copied into private Everbranch storage; Everbranch does not crawl shared albums.',
            ],
            'capabilities' => ['documents.manage'],
            'mobile' => [
                'status' => 'ready',
                'display_name' => 'Documents Branch',
                'renderer' => 'dashboard',
                'entry_screen' => 'documents.overview',
                'contract_version' => 2,
                'min_app_version' => '1.2.0',
                'navigation' => ['group' => 'work', 'icon' => 'folder-open', 'position' => 35],
                'actions' => ['upload_assets'],
            ],
        ],
        'estimator' => [
            'display_name' => 'Estimator',
            'description' => 'Build fast estimate drafts from an owner-reviewed service price book.',
            'status' => 'beta',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['backstage'],
            'classification' => 'shared-core',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['field_service'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'request_module',
            'buyer_setup' => [
                'outcome' => 'Prepare consistent estimates from recent invoiced work without writing back to QuickBooks.',
                'best_for' => 'Owners with repeated service descriptions and pricing history that can be curated.',
                'what_you_need' => ['An owner-approved price book and at least one field-service customer or job.'],
                'next_step' => 'Review suggested price items before enabling estimate drafts.',
                'setup_steps' => ['Review repeated invoice descriptions.', 'Approve or edit reusable prices.', 'Create the first Everbranch estimate draft.'],
                'primary_action' => 'Review price book',
                'help_text' => 'Estimator drafts stay in Everbranch and never create QuickBooks transactions.',
            ],
            'capabilities' => ['estimator.drafts'],
            'mobile' => [
                'status' => 'beta',
                'display_name' => 'Estimator',
                'renderer' => 'estimator',
                'entry_screen' => 'estimator.index',
                'contract_version' => 3,
                'min_app_version' => '1.3.0',
                'navigation' => ['group' => 'work', 'icon' => 'calculator', 'position' => 30],
                'actions' => ['view', 'create_draft', 'edit_draft'],
            ],
        ],
        'wix' => [
            'display_name' => 'Wix',
            'description' => 'Wix connector placeholder.',
            'status' => 'roadmap',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['backstage'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['integrations'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'contact_sales',
            'capabilities' => ['wix.sync'],
        ],
        'square' => [
            'display_name' => 'Square',
            'description' => 'Square ingestion and connector readiness.',
            'status' => 'beta',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['backstage'],
            'classification' => 'integration-layer',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'not_started',
            'dependencies' => ['integrations'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'request_access',
            'capabilities' => ['square.sync'],
        ],
        'workflow_automations' => [
            'display_name' => 'Workflow Automations',
            'description' => 'Zap-style workflow automations with event triggers and action steps managed in Everbranch.',
            'status' => 'beta',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['integrations'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['workflow.automations'],
        ],
        'email' => [
            'display_name' => 'Email',
            'description' => 'Email channel readiness and tenant provider configuration.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['integrations'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['email.channel'],
        ],
        'sms' => [
            'display_name' => 'SMS',
            'description' => 'SMS channel and provider readiness.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['integrations', 'customers', 'messaging'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'add_module',
            'buyer_setup' => [
                'outcome' => 'Send customer text messages through a tenant-controlled SMS provider setup.',
                'best_for' => 'Teams that need timely customer reminders, lifecycle nudges, or operational messages by text.',
                'what_you_need' => [
                    'A sending provider or approval to use the configured provider.',
                    'A clear opt-in and compliance process for customer phone numbers.',
                ],
                'next_step' => 'Confirm SMS readiness and decide which message type should be enabled first.',
                'setup_steps' => [
                    'Review provider and sender readiness.',
                    'Confirm opt-in rules and customer phone data.',
                    'Test one internal or low-risk message before expanding.',
                ],
                'primary_action' => 'Configure SMS',
                'help_text' => 'SMS should be enabled carefully because customer consent and sender setup matter.',
            ],
            'capabilities' => ['sms.channel'],
        ],
        'mobile_connection' => [
            'display_name' => 'Mobile Connection',
            'description' => 'Future mobile channel support.',
            'status' => 'roadmap',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['integrations'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'contact_sales',
            'capabilities' => ['mobile.connection'],
        ],
        'ai' => [
            'display_name' => 'AI Assistant',
            'description' => 'Tenant-aware AI assistant workspace for guided opportunities and human-reviewed campaign drafts.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'shared-core',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'upgrade_plan',
            'buyer_setup' => [
                'outcome' => 'Use AI to surface opportunities and prepare review-ready campaign drafts.',
                'best_for' => 'Business owners who want help spotting useful next steps without giving up approval control.',
                'what_you_need' => [
                    'Customer and activity data in the workspace.',
                    'A human reviewer who approves recommendations before action.',
                ],
                'next_step' => 'Start with opportunities, then review any draft before it becomes customer-facing.',
                'setup_steps' => [
                    'Confirm the workspace has enough customer context.',
                    'Review top opportunities for accuracy.',
                    'Approve, edit, or reject draft campaign ideas before use.',
                ],
                'primary_action' => 'Review AI Assistant',
                'help_text' => 'AI suggestions are advisory and should stay human-reviewed.',
            ],
            'capabilities' => [
                'ai.assistant',
                'ai.start_here',
                'ai.opportunities',
                'ai.draft_campaigns',
                'ai.setup',
                'ai.activity',
            ],
        ],
        'bulk_email_marketing' => [
            'display_name' => 'Bulk Email Marketing',
            'description' => 'Higher-volume marketing email campaigns and send controls.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['email', 'campaigns', 'messaging'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'add_module',
            'buyer_setup' => [
                'outcome' => 'Prepare higher-volume marketing email while keeping send controls clear.',
                'best_for' => 'Teams that are ready to move from occasional messages into planned marketing email.',
                'what_you_need' => [
                    'A ready email provider or sending plan.',
                    'Audience rules and approval for marketing sends.',
                ],
                'next_step' => 'Confirm email readiness and choose the first campaign type before enabling volume sends.',
                'setup_steps' => [
                    'Review provider, sender, and audience readiness.',
                    'Define who approves marketing email.',
                    'Send a small, reviewed campaign before scaling volume.',
                ],
                'primary_action' => 'Plan email setup',
                'help_text' => 'Bulk email should stay controlled until sender reputation and audience rules are clear.',
            ],
            'capabilities' => ['bulk_email.campaigns'],
        ],
        'messaging' => [
            'display_name' => 'Messaging',
            'description' => 'Operational workspace for direct customer and group messaging.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'add_module',
            'buyer_setup' => [
                'outcome' => 'Keep direct customer and group conversations connected to the workspace.',
                'best_for' => 'Teams that want customer communication history and follow-up in one place.',
                'what_you_need' => [
                    'A communication owner or team inbox process.',
                    'A decision on which customers or groups should be messaged first.',
                ],
                'next_step' => 'Set up the first messaging workflow and confirm who responds to incoming replies.',
                'setup_steps' => [
                    'Confirm the team owner for messages.',
                    'Review the first audience or group.',
                    'Send a small test message and verify the response path.',
                ],
                'primary_action' => 'Set up messaging',
                'help_text' => 'Messaging works best when ownership is clear before customers start replying.',
            ],
            'capabilities' => ['messaging.workspace', 'messaging.analytics'],
            'mobile' => [
                'status' => 'ready',
                'display_name' => 'Messaging Branch',
                'renderer' => 'list',
                'entry_screen' => 'messaging.inbox',
                'contract_version' => 2,
                'min_app_version' => '1.1.0',
                'purchase_key' => 'addon.messaging',
                'navigation' => ['group' => 'work', 'icon' => 'messages-square', 'position' => 30],
                'actions' => ['view', 'search', 'compose', 'reply', 'manage_thread'],
            ],
        ],
        'subscriptions' => [
            'display_name' => 'Subscriptions',
            'description' => 'Shopify-native recurring subscriptions with migration, billing operations, plan rules, and verified voting.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['shopify'],
            'shopify_embedded_surfaces' => ['retail'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers', 'shopify'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'add_module',
            'buyer_setup' => [
                'outcome' => 'Run recurring subscriptions with migration support, billing operations, customer actions, and voting when needed.',
                'best_for' => 'Shopify businesses that need recurring orders without leaving subscription operations scattered across tools.',
                'what_you_need' => [
                    'Shopify access for the store that will own subscription contracts.',
                    'A plan for migration, billing rules, and customer-facing subscription policies.',
                ],
                'next_step' => 'Review the subscription rules and migration plan before enabling customer-facing workflows.',
                'setup_steps' => [
                    'Confirm Shopify subscription prerequisites.',
                    'Review migration and billing operation needs.',
                    'Test plan rules, customer actions, and voting before launch.',
                ],
                'primary_action' => 'Plan subscriptions',
                'help_text' => 'Tenant-specific subscription names and examples can be configured without changing the generic module.',
            ],
            'capabilities' => [
                'subscriptions.manage',
                'subscriptions.migration',
                'subscriptions.candle_club',
                'subscriptions.voting',
            ],
        ],
        'additional_channels' => [
            'display_name' => 'Additional Channels',
            'description' => 'Expand beyond the base included store or channel allowance.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['shopify'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true, 'mobile_store' => true],
            'cta_routing' => 'add_module',
            'buyer_setup' => [
                'outcome' => 'Add another store, sales channel, or operating channel without forking the workspace.',
                'best_for' => 'Businesses expanding beyond the first connected storefront or operating channel.',
                'what_you_need' => [
                    'The channel you want to add and who owns it.',
                    'A decision on whether data should be synced, imported, or managed manually first.',
                ],
                'next_step' => 'Confirm the channel and owner, then decide whether setup starts with sync or manual intake.',
                'setup_steps' => [
                    'Identify the new channel and access owner.',
                    'Confirm what customer or order data should be shared.',
                    'Start with the safest import or sync path for that channel.',
                ],
                'primary_action' => 'Add channel',
                'help_text' => 'Additional channels should expand the same workspace instead of creating a separate operating island.',
            ],
            'capabilities' => ['channels.additional'],
        ],
        'future_niche_modules' => [
            'display_name' => 'Future Niche Modules',
            'description' => 'Reserved packaging for future vertical or specialty modules.',
            'status' => 'roadmap',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => [],
            'billing_mode' => 'custom',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'contact_sales',
            'capabilities' => ['future.modules'],
        ],
    ],

    'plans' => [
        'base' => [
            'display_name' => 'Base Workspace',
            'label' => 'Base Workspace',
            'purchase_key' => 'plan.base',
            'track' => 'direct',
            'is_public' => true,
            'position' => 5,
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 9900, 'setup_price_cents' => 2900],
            'stripe' => [
                'product_lookup_key' => 'tier_base',
                'recurring_price_lookup_key' => 'tier_base_monthly',
                'setup_price_lookup_key' => 'tier_base_setup',
            ],
            'included_modules' => [
                'work_core',
                'customers',
                'field_service',
                'reporting',
                'uploads',
                'onboarding',
                'settings',
            ],
            'eligible_addons' => [
                'sms',
                'messaging',
                'additional_channels',
                'bulk_email_marketing',
                'future_niche_modules',
            ],
        ],
        'starter' => [
            'display_name' => 'Starter',
            'label' => 'Starter',
            'purchase_key' => 'plan.starter',
            'track' => 'shopify',
            'is_public' => true,
            'position' => 10,
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 14900, 'setup_price_cents' => 4900],
            'stripe' => [
                'product_lookup_key' => 'tier_starter',
                'recurring_price_lookup_key' => 'tier_starter_monthly',
                'setup_price_lookup_key' => 'tier_starter_setup',
            ],
            'included_modules' => [
                'dashboard',
                'wholesale_operations',
                'work_core',
                'customers',
                'reviews',
                'lead_capture',
                'reporting',
                'integrations',
                'uploads',
                'onboarding',
                'settings',
                'shopify',
                'square',
            ],
            'eligible_addons' => [
                'referrals',
                'sms',
                'messaging',
                'additional_channels',
                'bulk_email_marketing',
                'subscriptions',
                'future_niche_modules',
            ],
        ],
        'growth' => [
            'display_name' => 'Growth',
            'label' => 'Growth',
            'purchase_key' => 'plan.growth',
            'track' => 'shopify',
            'is_public' => true,
            'position' => 20,
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 29900, 'setup_price_cents' => 7900],
            'stripe' => [
                'product_lookup_key' => 'tier_growth',
                'recurring_price_lookup_key' => 'tier_growth_monthly',
                'setup_price_lookup_key' => 'tier_growth_setup',
            ],
            'included_modules' => [
                'dashboard',
                'wholesale_operations',
                'work_core',
                'customers',
                'reviews',
                'lead_capture',
                'reporting',
                'integrations',
                'uploads',
                'onboarding',
                'settings',
                'shopify',
                'square',
                'rewards',
                'birthdays',
                'campaigns',
                'email',
                'ai',
            ],
            'eligible_addons' => [
                'referrals',
                'sms',
                'messaging',
                'additional_channels',
                'bulk_email_marketing',
                'subscriptions',
                'future_niche_modules',
            ],
        ],
        'pro' => [
            'display_name' => 'Pro',
            'label' => 'Pro',
            'purchase_key' => 'plan.pro',
            'track' => 'shopify',
            'is_public' => true,
            'position' => 30,
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 39900, 'setup_price_cents' => 9900],
            'stripe' => [
                'product_lookup_key' => 'tier_pro',
                'recurring_price_lookup_key' => 'tier_pro_monthly',
                'setup_price_lookup_key' => 'tier_pro_setup',
            ],
            'included_modules' => [
                'dashboard',
                'wholesale_operations',
                'work_core',
                'customers',
                'reviews',
                'lead_capture',
                'reporting',
                'diagnostics_advanced',
                'integrations',
                'uploads',
                'onboarding',
                'settings',
                'shopify',
                'square',
                'rewards',
                'birthdays',
                'campaigns',
                'email',
                'wishlist',
                'ai',
            ],
            'eligible_addons' => [
                'referrals',
                'sms',
                'messaging',
                'additional_channels',
                'bulk_email_marketing',
                'subscriptions',
                'future_niche_modules',
            ],
        ],
    ],

    'addons' => [
        'referrals' => [
            'display_name' => 'Referrals',
            'label' => 'Referrals',
            'purchase_key' => 'addon.referrals',
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 7900, 'setup_price_cents' => 0],
            'stripe' => ['product_lookup_key' => 'addon_referrals', 'recurring_price_lookup_key' => 'addon_referrals_monthly'],
            'modules' => ['referrals'],
            'legacy_grants' => ['referrals'],
            'billing_mode' => 'add_on',
        ],
        'sms' => [
            'display_name' => 'SMS',
            'label' => 'SMS',
            'purchase_key' => 'addon.sms',
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 9900, 'setup_price_cents' => 9900],
            'stripe' => ['product_lookup_key' => 'addon_sms', 'recurring_price_lookup_key' => 'addon_sms_monthly'],
            'modules' => ['messaging', 'sms'],
            'legacy_grants' => ['messaging', 'sms'],
            'billing_mode' => 'add_on',
        ],
        'messaging' => [
            'display_name' => 'Messaging',
            'label' => 'Messaging',
            'purchase_key' => 'addon.messaging',
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 1999, 'setup_price_cents' => 0],
            'stripe' => ['product_lookup_key' => 'addon_messaging', 'recurring_price_lookup_key' => 'addon_messaging_monthly'],
            'modules' => ['messaging'],
            'legacy_grants' => ['messaging'],
            'billing_mode' => 'add_on',
        ],
        'additional_channels' => [
            'display_name' => 'Additional Channels',
            'label' => 'Additional Stores/Channels',
            'purchase_key' => 'addon.additional_channels',
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 5900, 'setup_price_cents' => 0],
            'stripe' => ['product_lookup_key' => 'addon_additional_channels', 'recurring_price_lookup_key' => 'addon_additional_channels_monthly'],
            'modules' => ['additional_channels'],
            'legacy_grants' => ['shopify'],
            'billing_mode' => 'add_on',
        ],
        'bulk_email_marketing' => [
            'display_name' => 'Bulk Email Marketing',
            'label' => 'Bulk Marketing Email',
            'purchase_key' => 'addon.bulk_email_marketing',
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 12900, 'setup_price_cents' => 0],
            'stripe' => ['product_lookup_key' => 'addon_bulk_email_marketing', 'recurring_price_lookup_key' => 'addon_bulk_email_marketing_monthly'],
            'modules' => ['messaging', 'email', 'campaigns', 'bulk_email_marketing'],
            'legacy_grants' => ['messaging', 'email'],
            'billing_mode' => 'add_on',
        ],
        'subscriptions' => [
            'display_name' => 'Subscriptions',
            'label' => 'Subscriptions',
            'purchase_key' => 'addon.subscriptions',
            'modules' => ['subscriptions'],
            'legacy_grants' => ['subscriptions'],
            'billing_mode' => 'add_on',
        ],
        'future_niche_modules' => [
            'display_name' => 'Future Niche Modules',
            'label' => 'Future Niche Modules',
            'purchase_key' => 'addon.future_niche_modules',
            'pricing' => ['currency' => 'USD', 'recurring_price_cents' => 0, 'setup_price_cents' => 0],
            'stripe' => ['product_lookup_key' => 'addon_future_niche_modules', 'recurring_price_lookup_key' => 'addon_future_niche_modules_monthly'],
            'modules' => ['future_niche_modules'],
            'legacy_grants' => ['ai'],
            'billing_mode' => 'custom',
        ],
        'advanced_reporting' => [
            'display_name' => 'Advanced Reporting (Legacy Alias)',
            'label' => 'Advanced Reporting (Legacy Alias)',
            'purchase_key' => 'addon.advanced_reporting',
            'modules' => ['diagnostics_advanced'],
            'legacy_grants' => ['diagnostics_advanced', 'reporting'],
            'billing_mode' => 'add_on',
        ],
        'vip_pack' => [
            'display_name' => 'VIP (Legacy Alias)',
            'label' => 'VIP (Legacy Alias)',
            'purchase_key' => 'addon.vip_pack',
            'modules' => ['vip'],
            'legacy_grants' => ['vip', 'notifications'],
            'billing_mode' => 'custom',
        ],
        'integrations_pack' => [
            'display_name' => 'Integrations (Legacy Alias)',
            'label' => 'Integrations (Legacy Alias)',
            'purchase_key' => 'addon.integrations_pack',
            'modules' => ['integrations'],
            'legacy_grants' => ['integrations', 'quickbooks', 'wix', 'mobile_connection'],
            'billing_mode' => 'custom',
        ],
    ],
];

$mobileDefaults = [
    'status' => 'hidden',
    'renderer' => 'none',
    'entry_screen' => null,
    'contract_version' => 1,
    'min_app_version' => '1.0.0',
    'purchase_key' => null,
    'navigation' => ['group' => 'work', 'icon' => 'grid-2x2', 'position' => 999],
    'actions' => [],
];

foreach ($catalog['modules'] as &$module) {
    $module['visibility'] = array_replace(
        ['mobile_store' => false],
        is_array($module['visibility'] ?? null) ? $module['visibility'] : []
    );
    $module['mobile'] = array_replace_recursive(
        $mobileDefaults,
        is_array($module['mobile'] ?? null) ? $module['mobile'] : []
    );
}
unset($module);

return $catalog;
