<?php

return [
    'defaults' => [
        'plan' => env('TENANT_ENTITLEMENTS_DEFAULT_PLAN', 'starter'),
        'operating_mode' => env('TENANT_ENTITLEMENTS_DEFAULT_MODE', 'shopify'),
        'setup_statuses' => [
            'not_started',
            'in_progress',
            'configured',
            'blocked',
        ],
    ],

    'legacy' => [
        'plan_aliases' => [
            'shopify_proof_of_concept' => 'starter',
            'shopify_growth' => 'growth',
            'direct_starter' => 'starter',
        ],
        'addon_aliases' => [
            'advanced_reporting' => 'advanced_reporting',
            'referrals_pack' => 'referrals',
            'vip_pack' => 'vip_pack',
            'integrations_pack' => 'integrations_pack',
            'ai_brain' => 'future_niche_modules',
        ],
        'module_aliases' => [
            'advanced_reporting' => 'diagnostics_advanced',
            'marketing_email' => 'bulk_email_marketing',
            'extra_channels' => 'additional_channels',
            'future_modules' => 'future_niche_modules',
        ],
    ],

    'capabilities' => [
        'dashboard.overview' => [
            'display_name' => 'Overview dashboard',
            'description' => 'Baseline overview and shell access.',
            'module_key' => 'dashboard',
        ],
        'customers.manage' => [
            'display_name' => 'Customer management',
            'description' => 'Manage customer profiles, notes, and identity-linked data.',
            'module_key' => 'customers',
        ],
        'activity.timeline' => [
            'display_name' => 'Customer activity timeline',
            'description' => 'View customer activity and engagement context.',
            'module_key' => 'activity',
        ],
        'questions.queue' => [
            'display_name' => 'Questions queue',
            'description' => 'Internal workflow for unresolved questions and follow-up.',
            'module_key' => 'questions',
        ],
        'rewards.program' => [
            'display_name' => 'Rewards program',
            'description' => 'Configure and operate rewards earn and redeem behavior.',
            'module_key' => 'rewards',
        ],
        'birthdays.lifecycle' => [
            'display_name' => 'Birthday lifecycle',
            'description' => 'Run birthday-triggered messaging and reward flows.',
            'module_key' => 'birthdays',
        ],
        'reviews.collect' => [
            'display_name' => 'Review collection',
            'description' => 'Collect, moderate, and display product reviews.',
            'module_key' => 'reviews',
        ],
        'lead_capture.intake' => [
            'display_name' => 'Lead capture intake',
            'description' => 'Capture leads, intake submissions, and funnel entry points.',
            'module_key' => 'lead_capture',
        ],
        'wishlist.manage' => [
            'display_name' => 'Wishlist management',
            'description' => 'Store and manage customer wishlist activity.',
            'module_key' => 'wishlist',
        ],
        'referrals.program' => [
            'display_name' => 'Referrals program',
            'description' => 'Referral acquisition and reward tracking.',
            'module_key' => 'referrals',
        ],
        'vip.tiers' => [
            'display_name' => 'VIP tiers',
            'description' => 'Tiered loyalty and VIP customer programs.',
            'module_key' => 'vip',
        ],
        'notifications.messaging' => [
            'display_name' => 'Notifications',
            'description' => 'Notification templates and message triggers.',
            'module_key' => 'notifications',
        ],
        'campaigns.orchestration' => [
            'display_name' => 'Campaign orchestration',
            'description' => 'Create and manage audience and lifecycle campaigns.',
            'module_key' => 'campaigns',
        ],
        'reporting.analytics' => [
            'display_name' => 'Reporting analytics',
            'description' => 'Core reporting and analytics surfaces.',
            'module_key' => 'reporting',
        ],
        'diagnostics.advanced' => [
            'display_name' => 'Advanced diagnostics',
            'description' => 'Deeper troubleshooting and export diagnostics.',
            'module_key' => 'diagnostics_advanced',
        ],
        'integrations.registry' => [
            'display_name' => 'Integration registry',
            'description' => 'Read-only integration states and setup guidance.',
            'module_key' => 'integrations',
        ],
        'uploads.imports' => [
            'display_name' => 'Uploads and imports',
            'description' => 'Manual import and CSV-based onboarding utilities.',
            'module_key' => 'uploads',
        ],
        'onboarding.checklist' => [
            'display_name' => 'Onboarding checklist',
            'description' => 'Guided setup and module readiness checklist.',
            'module_key' => 'onboarding',
        ],
        'settings.tenant' => [
            'display_name' => 'Tenant settings',
            'description' => 'Tenant-level settings and configuration controls.',
            'module_key' => 'settings',
        ],
        'shopify.connection' => [
            'display_name' => 'Shopify connection',
            'description' => 'Shopify embedded and storefront-specific context.',
            'module_key' => 'shopify',
        ],
        'quickbooks.sync' => [
            'display_name' => 'QuickBooks sync',
            'description' => 'Accounting connector and sync readiness.',
            'module_key' => 'quickbooks',
        ],
        'wix.sync' => [
            'display_name' => 'Wix sync',
            'description' => 'Wix channel connector and setup state.',
            'module_key' => 'wix',
        ],
        'square.sync' => [
            'display_name' => 'Square sync',
            'description' => 'Square commerce connection and data ingestion.',
            'module_key' => 'square',
        ],
        'email.channel' => [
            'display_name' => 'Email channel',
            'description' => 'Email provider readiness and messaging channel support.',
            'module_key' => 'email',
        ],
        'sms.channel' => [
            'display_name' => 'SMS channel',
            'description' => 'SMS messaging setup and provider readiness.',
            'module_key' => 'sms',
        ],
        'mobile.connection' => [
            'display_name' => 'Mobile connection',
            'description' => 'Future mobile channel connection surface.',
            'module_key' => 'mobile_connection',
        ],
        'ai.assistant' => [
            'display_name' => 'AI Assistant',
            'description' => 'Guided AI assistant workspace for opportunities, setup, and review-ready drafts.',
            'module_key' => 'ai',
        ],
        'ai.start_here' => [
            'display_name' => 'AI Assistant Start Here',
            'description' => 'Get oriented with tenant-aware AI readiness and next steps.',
            'module_key' => 'ai',
        ],
        'ai.opportunities' => [
            'display_name' => 'AI Assistant top opportunities',
            'description' => 'Review high-impact opportunities before preparing campaign drafts.',
            'module_key' => 'ai',
        ],
        'ai.draft_campaigns' => [
            'display_name' => 'AI Assistant draft campaigns',
            'description' => 'Prepare draft campaigns that always require human review before sending.',
            'module_key' => 'ai',
        ],
        'ai.setup' => [
            'display_name' => 'AI Assistant setup',
            'description' => 'Track prerequisite setup states for AI-assisted workflows.',
            'module_key' => 'ai',
        ],
        'ai.activity' => [
            'display_name' => 'AI Assistant activity',
            'description' => 'Review recent AI-relevant workspace signals and trend context.',
            'module_key' => 'ai',
        ],
        'bulk_email.campaigns' => [
            'display_name' => 'Bulk email marketing',
            'description' => 'Marketing email campaigns and higher-volume send workflows.',
            'module_key' => 'bulk_email_marketing',
        ],
        'channels.additional' => [
            'display_name' => 'Additional channels',
            'description' => 'Expand beyond the base store or channel allowance.',
            'module_key' => 'additional_channels',
        ],
        'future.modules' => [
            'display_name' => 'Future niche modules',
            'description' => 'Reserved niche/vertical module packaging.',
            'module_key' => 'future_niche_modules',
        ],
        'messaging.workspace' => [
            'display_name' => 'Messaging workspace',
            'description' => 'Direct 1:1 and group messaging workspace for SMS and email outreach.',
            'module_key' => 'messaging',
        ],
        'messaging.analytics' => [
            'display_name' => 'Message analytics',
            'description' => 'Operational analytics for message opens, clicks, and attributed orders.',
            'module_key' => 'messaging',
        ],
    ],

    'modules' => [
        'dashboard' => [
            'display_name' => 'Overview',
            'description' => 'Baseline overview, shell access, and account context.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['shopify'],
            'classification' => 'shopify-only',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['dashboard.overview'],
        ],
        'customers' => [
            'display_name' => 'Customers',
            'description' => 'Manage customer profiles, identity, and operator context.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['customers.manage'],
        ],
        'activity' => [
            'display_name' => 'Activity',
            'description' => 'Customer activity timeline and engagement feed.',
            'status' => 'placeholder',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'request_access',
            'capabilities' => ['activity.timeline'],
        ],
        'questions' => [
            'display_name' => 'Questions',
            'description' => 'Internal support and follow-up workflow.',
            'status' => 'placeholder',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['backstage'],
            'classification' => 'internal-admin',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['questions.queue'],
        ],
        'rewards' => [
            'display_name' => 'Rewards',
            'description' => 'Operate the loyalty and rewards program.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'upgrade_plan',
            'capabilities' => ['rewards.program'],
        ],
        'birthdays' => [
            'display_name' => 'Birthdays / Lifecycle',
            'description' => 'Birthday-triggered lifecycle messaging and rewards.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers', 'rewards'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'upgrade_plan',
            'capabilities' => ['birthdays.lifecycle'],
        ],
        'reviews' => [
            'display_name' => 'Reviews',
            'description' => 'Collect, moderate, and display native reviews.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['reviews.collect'],
        ],
        'lead_capture' => [
            'display_name' => 'Lead Capture / Intake',
            'description' => 'Capture leads and intake requests into the customer system.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['lead_capture.intake'],
        ],
        'wishlist' => [
            'display_name' => 'Wishlist',
            'description' => 'Track and activate wishlist-driven retention workflows.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['pro'],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'upgrade_plan',
            'capabilities' => ['wishlist.manage'],
        ],
        'referrals' => [
            'display_name' => 'Referrals',
            'description' => 'Referral acquisition and reward workflows.',
            'status' => 'placeholder',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['rewards'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'request_access',
            'capabilities' => ['referrals.program'],
        ],
        'vip' => [
            'display_name' => 'VIP',
            'description' => 'Tier-based loyalty and VIP configuration.',
            'status' => 'placeholder',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['rewards'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['vip.tiers'],
        ],
        'notifications' => [
            'display_name' => 'Notifications',
            'description' => 'Notification templates and customer messaging triggers.',
            'status' => 'placeholder',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['notifications.messaging'],
        ],
        'campaigns' => [
            'display_name' => 'Campaigns',
            'description' => 'Audience and lifecycle campaign management.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'upgrade_plan',
            'capabilities' => ['campaigns.orchestration'],
        ],
        'reporting' => [
            'display_name' => 'Reporting',
            'description' => 'Core reporting and analytics surfaces.',
            'status' => 'live',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['reporting.analytics'],
        ],
        'diagnostics_advanced' => [
            'display_name' => 'Advanced Diagnostics',
            'description' => 'Advanced diagnostics, exports, and troubleshooting.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['pro'],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['reporting'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'upgrade_plan',
            'capabilities' => ['diagnostics.advanced'],
        ],
        'integrations' => [
            'display_name' => 'Integrations',
            'description' => 'Integration setup states and fallback-first connector guidance.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'not_started',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['integrations.registry'],
        ],
        'uploads' => [
            'display_name' => 'Uploads / Imports',
            'description' => 'CSV and manual import workflows.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'not_started',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['uploads.imports'],
        ],
        'onboarding' => [
            'display_name' => 'Onboarding',
            'description' => 'Tenant onboarding and setup guidance.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'not_started',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['onboarding.checklist'],
        ],
        'settings' => [
            'display_name' => 'Settings',
            'description' => 'Tenant settings and environment configuration.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'classification' => 'shared-core',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['settings.tenant'],
        ],
        'shopify' => [
            'display_name' => 'Shopify',
            'description' => 'Shopify embedded, proxy, and store-linked surfaces.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['shopify'],
            'classification' => 'shopify-only',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'configured',
            'dependencies' => [],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['shopify.connection'],
        ],
        'quickbooks' => [
            'display_name' => 'QuickBooks',
            'description' => 'Accounting connector placeholder.',
            'status' => 'roadmap',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['backstage'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['integrations'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'contact_sales',
            'capabilities' => ['quickbooks.sync'],
        ],
        'wix' => [
            'display_name' => 'Wix',
            'description' => 'Wix connector placeholder.',
            'status' => 'roadmap',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['backstage'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['integrations'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'contact_sales',
            'capabilities' => ['wix.sync'],
        ],
        'square' => [
            'display_name' => 'Square',
            'description' => 'Square ingestion and connector readiness.',
            'status' => 'beta',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['backstage'],
            'classification' => 'integration-layer',
            'included_in_plans' => ['starter', 'growth', 'pro'],
            'default_enabled' => true,
            'default_setup_status' => 'not_started',
            'dependencies' => ['integrations'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'request_access',
            'capabilities' => ['square.sync'],
        ],
        'email' => [
            'display_name' => 'Email',
            'description' => 'Email channel readiness and tenant provider configuration.',
            'status' => 'live',
            'market_state' => 'INTERNAL_ONLY',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => ['growth', 'pro'],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['integrations'],
            'billing_mode' => 'included',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'none',
            'capabilities' => ['email.channel'],
        ],
        'sms' => [
            'display_name' => 'SMS',
            'description' => 'SMS channel and provider readiness.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['integrations', 'customers'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'add_module',
            'capabilities' => ['sms.channel'],
        ],
        'mobile_connection' => [
            'display_name' => 'Mobile Connection',
            'description' => 'Future mobile channel support.',
            'status' => 'roadmap',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'integration-layer',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['integrations'],
            'billing_mode' => 'unavailable',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'contact_sales',
            'capabilities' => ['mobile.connection'],
        ],
        'ai' => [
            'display_name' => 'AI Assistant',
            'description' => 'Tenant-aware AI assistant workspace for guided opportunities and human-reviewed campaign drafts.',
            'status' => 'roadmap',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['customers'],
            'billing_mode' => 'custom',
            'visibility' => ['public_site' => false, 'app_store' => false],
            'cta_routing' => 'contact_sales',
            'capabilities' => [
                'ai.assistant',
                'ai.start_here',
                'ai.opportunities',
                'ai.draft_campaigns',
                'ai.setup',
                'ai.activity',
            ],
        ],
        'bulk_email_marketing' => [
            'display_name' => 'Bulk Email Marketing',
            'description' => 'Higher-volume marketing email campaigns and send controls.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => ['email', 'campaigns'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'add_module',
            'capabilities' => ['bulk_email.campaigns'],
        ],
        'messaging' => [
            'display_name' => 'Messaging',
            'description' => 'Operational workspace for direct customer and group messaging.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['shopify'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['customers'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'add_module',
            'capabilities' => ['messaging.workspace', 'messaging.analytics'],
        ],
        'additional_channels' => [
            'display_name' => 'Additional Channels',
            'description' => 'Expand beyond the base included store or channel allowance.',
            'status' => 'beta',
            'market_state' => 'SAFE_TO_MARKET',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'configured',
            'dependencies' => ['shopify'],
            'billing_mode' => 'add_on',
            'visibility' => ['public_site' => true, 'app_store' => true],
            'cta_routing' => 'add_module',
            'capabilities' => ['channels.additional'],
        ],
        'future_niche_modules' => [
            'display_name' => 'Future Niche Modules',
            'description' => 'Reserved packaging for future vertical or specialty modules.',
            'status' => 'roadmap',
            'market_state' => 'PLACEHOLDER',
            'channels' => ['both'],
            'classification' => 'add-on',
            'included_in_plans' => [],
            'default_enabled' => false,
            'default_setup_status' => 'not_started',
            'dependencies' => [],
            'billing_mode' => 'custom',
            'visibility' => ['public_site' => true, 'app_store' => false],
            'cta_routing' => 'contact_sales',
            'capabilities' => ['future.modules'],
        ],
    ],

    'plans' => [
        'starter' => [
            'display_name' => 'Starter',
            'label' => 'Starter',
            'track' => 'shopify',
            'is_public' => true,
            'position' => 10,
            'included_modules' => [
                'dashboard',
                'customers',
                'reviews',
                'lead_capture',
                'reporting',
                'integrations',
                'uploads',
                'onboarding',
                'settings',
                'shopify',
                'square',
            ],
            'eligible_addons' => [
                'referrals',
                'sms',
                'messaging',
                'additional_channels',
                'bulk_email_marketing',
                'future_niche_modules',
            ],
        ],
        'growth' => [
            'display_name' => 'Growth',
            'label' => 'Growth',
            'track' => 'shopify',
            'is_public' => true,
            'position' => 20,
            'included_modules' => [
                'dashboard',
                'customers',
                'reviews',
                'lead_capture',
                'reporting',
                'integrations',
                'uploads',
                'onboarding',
                'settings',
                'shopify',
                'square',
                'rewards',
                'birthdays',
                'campaigns',
                'email',
            ],
            'eligible_addons' => [
                'referrals',
                'sms',
                'messaging',
                'additional_channels',
                'bulk_email_marketing',
                'future_niche_modules',
            ],
        ],
        'pro' => [
            'display_name' => 'Pro',
            'label' => 'Pro',
            'track' => 'shopify',
            'is_public' => true,
            'position' => 30,
            'included_modules' => [
                'dashboard',
                'customers',
                'reviews',
                'lead_capture',
                'reporting',
                'diagnostics_advanced',
                'integrations',
                'uploads',
                'onboarding',
                'settings',
                'shopify',
                'square',
                'rewards',
                'birthdays',
                'campaigns',
                'email',
                'wishlist',
            ],
            'eligible_addons' => [
                'referrals',
                'sms',
                'messaging',
                'additional_channels',
                'bulk_email_marketing',
                'future_niche_modules',
            ],
        ],
    ],

    'addons' => [
        'referrals' => [
            'display_name' => 'Referrals',
            'label' => 'Referrals',
            'modules' => ['referrals'],
            'legacy_grants' => ['referrals'],
            'billing_mode' => 'add_on',
        ],
        'sms' => [
            'display_name' => 'SMS',
            'label' => 'SMS',
            'modules' => ['sms'],
            'legacy_grants' => ['sms'],
            'billing_mode' => 'add_on',
        ],
        'messaging' => [
            'display_name' => 'Messaging',
            'label' => 'Messaging',
            'modules' => ['messaging'],
            'legacy_grants' => ['messaging'],
            'billing_mode' => 'add_on',
        ],
        'additional_channels' => [
            'display_name' => 'Additional Channels',
            'label' => 'Additional Stores/Channels',
            'modules' => ['additional_channels'],
            'legacy_grants' => ['shopify'],
            'billing_mode' => 'add_on',
        ],
        'bulk_email_marketing' => [
            'display_name' => 'Bulk Email Marketing',
            'label' => 'Bulk Marketing Email',
            'modules' => ['bulk_email_marketing'],
            'legacy_grants' => ['email'],
            'billing_mode' => 'add_on',
        ],
        'future_niche_modules' => [
            'display_name' => 'Future Niche Modules',
            'label' => 'Future Niche Modules',
            'modules' => ['future_niche_modules'],
            'legacy_grants' => ['ai'],
            'billing_mode' => 'custom',
        ],
        'advanced_reporting' => [
            'display_name' => 'Advanced Reporting (Legacy Alias)',
            'label' => 'Advanced Reporting (Legacy Alias)',
            'modules' => ['diagnostics_advanced'],
            'legacy_grants' => ['diagnostics_advanced', 'reporting'],
            'billing_mode' => 'add_on',
        ],
        'vip_pack' => [
            'display_name' => 'VIP (Legacy Alias)',
            'label' => 'VIP (Legacy Alias)',
            'modules' => ['vip'],
            'legacy_grants' => ['vip', 'notifications'],
            'billing_mode' => 'custom',
        ],
        'integrations_pack' => [
            'display_name' => 'Integrations (Legacy Alias)',
            'label' => 'Integrations (Legacy Alias)',
            'modules' => ['integrations'],
            'legacy_grants' => ['integrations', 'quickbooks', 'wix', 'mobile_connection'],
            'billing_mode' => 'custom',
        ],
    ],
];
