<?php

return [
    'production_formulation_reference_v1' => [
        'canonical' => true,
        'do_not_override' => true,
        'measurements' => [
            'candle_16oz' => [
                1 => ['wax_grams' => 357, 'oil_grams' => 23],
                2 => ['wax_grams' => 714, 'oil_grams' => 46],
                3 => ['wax_grams' => 1072, 'oil_grams' => 68],
                4 => ['wax_grams' => 1429, 'oil_grams' => 91],
                5 => ['wax_grams' => 1786, 'oil_grams' => 114],
                6 => ['wax_grams' => 2143, 'oil_grams' => 137],
                7 => ['wax_grams' => 2500, 'oil_grams' => 160],
                8 => ['wax_grams' => 2857, 'oil_grams' => 183],
                9 => ['wax_grams' => 3215, 'oil_grams' => 205],
                10 => ['wax_grams' => 3572, 'oil_grams' => 228],
                12 => ['wax_grams' => 4286, 'oil_grams' => 274],
                15 => ['wax_grams' => 5358, 'oil_grams' => 342],
                24 => ['wax_grams' => 8572, 'oil_grams' => 548],
            ],
            'candle_16oz_top_off' => [
                1 => ['wax_grams' => 42, 'oil_grams' => 3],
                2 => ['wax_grams' => 85, 'oil_grams' => 5],
                3 => ['wax_grams' => 127, 'oil_grams' => 8],
                4 => ['wax_grams' => 169, 'oil_grams' => 11],
                5 => ['wax_grams' => 211, 'oil_grams' => 14],
                6 => ['wax_grams' => 254, 'oil_grams' => 16],
                7 => ['wax_grams' => 296, 'oil_grams' => 19],
                8 => ['wax_grams' => 338, 'oil_grams' => 22],
                9 => ['wax_grams' => 381, 'oil_grams' => 24],
                10 => ['wax_grams' => 423, 'oil_grams' => 27],
                12 => ['wax_grams' => 508, 'oil_grams' => 32],
                15 => ['wax_grams' => 635, 'oil_grams' => 40],
                24 => ['wax_grams' => 1016, 'oil_grams' => 64],
            ],
            'candle_8oz' => [
                1 => ['wax_grams' => 158, 'oil_grams' => 10],
                2 => ['wax_grams' => 316, 'oil_grams' => 20],
                3 => ['wax_grams' => 474, 'oil_grams' => 30],
                4 => ['wax_grams' => 632, 'oil_grams' => 40],
                5 => ['wax_grams' => 790, 'oil_grams' => 50],
                6 => ['wax_grams' => 948, 'oil_grams' => 60],
                7 => ['wax_grams' => 1106, 'oil_grams' => 70],
                8 => ['wax_grams' => 1264, 'oil_grams' => 80],
                9 => ['wax_grams' => 1421, 'oil_grams' => 91],
                10 => ['wax_grams' => 1579, 'oil_grams' => 101],
                12 => ['wax_grams' => 1895, 'oil_grams' => 121],
                15 => ['wax_grams' => 2369, 'oil_grams' => 151],
                24 => ['wax_grams' => 3790, 'oil_grams' => 242],
            ],
            'candle_8oz_top_off' => [
                1 => ['wax_grams' => 28, 'oil_grams' => 2],
                2 => ['wax_grams' => 56, 'oil_grams' => 4],
                3 => ['wax_grams' => 84, 'oil_grams' => 6],
                4 => ['wax_grams' => 113, 'oil_grams' => 7],
                5 => ['wax_grams' => 141, 'oil_grams' => 9],
                6 => ['wax_grams' => 169, 'oil_grams' => 11],
                7 => ['wax_grams' => 197, 'oil_grams' => 13],
                8 => ['wax_grams' => 225, 'oil_grams' => 15],
                9 => ['wax_grams' => 254, 'oil_grams' => 16],
                10 => ['wax_grams' => 282, 'oil_grams' => 18],
                12 => ['wax_grams' => 338, 'oil_grams' => 22],
                15 => ['wax_grams' => 422, 'oil_grams' => 28],
                24 => ['wax_grams' => 676, 'oil_grams' => 44],
            ],
            'candle_4oz' => [
                1 => ['wax_grams' => 81, 'oil_grams' => 5],
                2 => ['wax_grams' => 162, 'oil_grams' => 10],
                3 => ['wax_grams' => 243, 'oil_grams' => 15],
                4 => ['wax_grams' => 323, 'oil_grams' => 21],
                5 => ['wax_grams' => 404, 'oil_grams' => 26],
                6 => ['wax_grams' => 484, 'oil_grams' => 31],
                7 => ['wax_grams' => 565, 'oil_grams' => 36],
                8 => ['wax_grams' => 646, 'oil_grams' => 41],
                9 => ['wax_grams' => 727, 'oil_grams' => 47],
                10 => ['wax_grams' => 808, 'oil_grams' => 52],
                12 => ['wax_grams' => 969, 'oil_grams' => 62],
                15 => ['wax_grams' => 1212, 'oil_grams' => 77],
                24 => ['wax_grams' => 1938, 'oil_grams' => 124],
            ],
            'wax_melts' => [
                1 => ['wax_grams' => 75, 'oil_grams' => 5],
                2 => ['wax_grams' => 150, 'oil_grams' => 10],
                3 => ['wax_grams' => 226, 'oil_grams' => 14],
                4 => ['wax_grams' => 301, 'oil_grams' => 19],
                5 => ['wax_grams' => 376, 'oil_grams' => 24],
                6 => ['wax_grams' => 451, 'oil_grams' => 29],
                7 => ['wax_grams' => 526, 'oil_grams' => 34],
                8 => ['wax_grams' => 601, 'oil_grams' => 39],
                9 => ['wax_grams' => 677, 'oil_grams' => 43],
                10 => ['wax_grams' => 752, 'oil_grams' => 48],
                12 => ['wax_grams' => 902, 'oil_grams' => 58],
                15 => ['wax_grams' => 1128, 'oil_grams' => 72],
                24 => ['wax_grams' => 1804, 'oil_grams' => 116],
            ],
            'room_spray' => [
                1 => ['alcohol_grams' => 28, 'oil_grams' => 3, 'water_grams' => 81],
                2 => ['alcohol_grams' => 56, 'oil_grams' => 6, 'water_grams' => 162],
                3 => ['alcohol_grams' => 84, 'oil_grams' => 10, 'water_grams' => 245],
                6 => ['alcohol_grams' => 168, 'oil_grams' => 20, 'water_grams' => 490],
            ],
        ],
    ],
];
