import type { DashboardData } from "./types";

export const mockDashboardData: DashboardData = {
  metrics: [
    {
      key: "rewards-sales",
      label: "Rewards Sales",
      value: "$48,620",
      delta: "+12.4%",
      tone: "positive",
      caption: "Orders influenced by loyalty or post-purchase reward journeys.",
    },
    {
      key: "returning-customer-rate",
      label: "Returning Customer Rate",
      value: "43.8%",
      delta: "+3.1%",
      tone: "positive",
      caption: "Repeat purchasing rate across loyalty-active customers.",
    },
    {
      key: "candle-cash-used",
      label: "Candle Cash Used",
      value: "$9,280",
      delta: "+8.7%",
      tone: "positive",
      caption: "Value redeemed through Candle Cash in the selected window.",
    },
    {
      key: "net-profit-created",
      label: "Net Profit Created",
      value: "$17,940",
      delta: "-1.8%",
      tone: "negative",
      caption: "Mock contribution estimate after reward cost and discount pressure.",
    },
  ],
  chart: {
    title: "Performance trend",
    subtitle: "Mocked revenue lift and loyalty engagement trend for the selected timeframe.",
    benchmarkLabel: "Best day",
    benchmarkValue: "$8.4k",
    series: [
      { label: "Mar 1", value: 32 },
      { label: "Mar 5", value: 44 },
      { label: "Mar 9", value: 40 },
      { label: "Mar 13", value: 58 },
      { label: "Mar 17", value: 71 },
      { label: "Mar 21", value: 62 },
      { label: "Mar 25", value: 84 },
      { label: "Mar 29", value: 77 },
    ],
  },
  locations: [
    { name: "Shopify checkout", share: 42, orders: 312 },
    { name: "Email journeys", share: 21, orders: 157 },
    { name: "Instagram bio", share: 15, orders: 109 },
    { name: "Homepage reward banner", share: 12, orders: 88 },
    { name: "Referral landing pages", share: 10, orders: 73 },
  ],
  attribution: [
    {
      key: "text",
      label: "Text",
      revenue: "$12,460",
      change: "+14.8%",
      tone: "positive",
      description: "Fastest repeat conversion path across loyalty-first reminders.",
    },
    {
      key: "email",
      label: "Email",
      revenue: "$15,920",
      change: "+6.2%",
      tone: "positive",
      description: "Lifecycle sends continue to drive the largest total influenced revenue.",
    },
    {
      key: "instagram",
      label: "Instagram",
      revenue: "$5,340",
      change: "+2.1%",
      tone: "positive",
      description: "Social traffic remains efficient for new reward program discovery.",
    },
    {
      key: "facebook",
      label: "Facebook",
      revenue: "$3,890",
      change: "-4.6%",
      tone: "negative",
      description: "Creative fatigue is starting to show in repeat audience segments.",
    },
    {
      key: "google",
      label: "Google",
      revenue: "$10,740",
      change: "+9.3%",
      tone: "positive",
      description: "High-intent search continues to convert well into loyalty-aware orders.",
    },
  ],
  financialSummary: [
    {
      label: "Gross revenue touched",
      value: "$72,180",
      detail: "Orders with any reward, redemption, or attributed loyalty influence.",
    },
    {
      label: "Reward cost absorbed",
      value: "$11,430",
      detail: "Mock cost basis for issued discounts, gifts, and Candle Cash redemptions.",
    },
    {
      label: "Incremental retained revenue",
      value: "$28,660",
      detail: "Repeat revenue preserved through reward-triggered follow-up activity.",
    },
  ],
};
