import type { DashboardPayload } from "./types";

export const dashboardMockData: DashboardPayload = {
  meta: {
    generatedAt: new Date().toISOString(),
    currencyCode: "USD",
    partialData: {
      attribution: true,
      locations: true,
      profit: true,
    },
  },
  query: {
    timeframe: "last_30_days",
    comparison: "previous_period",
    locationGrouping: "state",
    chartMetric: "rewards_sales",
    customStartDate: null,
    customEndDate: null,
    primary: {
      from: new Date().toISOString(),
      to: new Date().toISOString(),
      label: "Last 30 days",
    },
    comparisonWindow: null,
    interval: {
      unit: "day",
      displayFormat: "M j",
      bucketCount: 30,
    },
    visualization: "line",
  },
  config: {
    defaultTimeframe: "last_30_days",
    defaultComparison: "previous_period",
    chartDefaultMetric: "rewards_sales",
    locationGroupingPreference: "state",
    timeframeOptions: [],
    comparisonOptions: [],
    locationGroupingOptions: [],
    visibleWidgets: {
      metricCards: true,
      candleCashEngagement: true,
      performanceChart: true,
      locationOrigins: true,
      attribution: true,
      financialSummary: true,
    },
    visibleAttributionSources: ["text", "email", "instagram", "facebook", "google", "other"],
    widgetRegistry: {},
  },
  topMetrics: [
    {
      key: "rewards_sales",
      label: "Rewards Sales",
      value: 48620,
      formattedValue: "$48,620.00",
      comparisonValue: 0,
      deltaPct: 12.4,
      deltaLabel: "+12.4%",
      tone: "positive",
      caption: "Fallback fixture for local design work.",
    },
    {
      key: "returning_customer_rate",
      label: "Returning Customer Rate",
      value: 43.8,
      formattedValue: "43.8%",
      comparisonValue: 0,
      deltaPct: 3.1,
      deltaLabel: "+3.1%",
      tone: "positive",
      caption: "Fallback fixture for local design work.",
    },
    {
      key: "candle_cash_used",
      label: "Candle Cash Used",
      value: 9280,
      formattedValue: "$9,280.00",
      comparisonValue: 0,
      deltaPct: 8.7,
      deltaLabel: "+8.7%",
      tone: "positive",
      caption: "Fallback fixture for local design work.",
    },
    {
      key: "net_profit_created",
      label: "Net Profit Created",
      value: 17940,
      formattedValue: "$17,940.00",
      comparisonValue: 0,
      deltaPct: -1.8,
      deltaLabel: "-1.8%",
      tone: "negative",
      caption: "Fallback fixture for local design work.",
    },
  ],
  chart: {
    title: "Performance trend",
    subtitle: "Fallback multi-series chart for local development only.",
    metric: {
      key: "rewards_sales",
      label: "Rewards Sales",
    },
    visualization: "line",
    series: [
      {
        label: "Mar 1",
        primary: 32,
        comparison: 28,
        values: {
          rewards_sales: 32,
          birthday_redemption_revenue: 10,
          referral_revenue: 8,
          candle_cash_earned: 16,
          candle_cash_redeemed: 9,
        },
        comparisonValues: {
          rewards_sales: 28,
          birthday_redemption_revenue: 8,
          referral_revenue: 7,
          candle_cash_earned: 13,
          candle_cash_redeemed: 7,
        },
      },
      {
        label: "Mar 5",
        primary: 44,
        comparison: 31,
        values: {
          rewards_sales: 44,
          birthday_redemption_revenue: 12,
          referral_revenue: 9,
          candle_cash_earned: 18,
          candle_cash_redeemed: 10,
        },
        comparisonValues: {
          rewards_sales: 31,
          birthday_redemption_revenue: 7,
          referral_revenue: 8,
          candle_cash_earned: 15,
          candle_cash_redeemed: 8,
        },
      },
      {
        label: "Mar 9",
        primary: 40,
        comparison: 35,
        values: {
          rewards_sales: 40,
          birthday_redemption_revenue: 11,
          referral_revenue: 7,
          candle_cash_earned: 17,
          candle_cash_redeemed: 11,
        },
        comparisonValues: {
          rewards_sales: 35,
          birthday_redemption_revenue: 9,
          referral_revenue: 9,
          candle_cash_earned: 16,
          candle_cash_redeemed: 9,
        },
      },
      {
        label: "Mar 13",
        primary: 58,
        comparison: 39,
        values: {
          rewards_sales: 58,
          birthday_redemption_revenue: 16,
          referral_revenue: 11,
          candle_cash_earned: 21,
          candle_cash_redeemed: 12,
        },
        comparisonValues: {
          rewards_sales: 39,
          birthday_redemption_revenue: 10,
          referral_revenue: 9,
          candle_cash_earned: 17,
          candle_cash_redeemed: 11,
        },
      },
      {
        label: "Mar 17",
        primary: 71,
        comparison: 47,
        values: {
          rewards_sales: 71,
          birthday_redemption_revenue: 22,
          referral_revenue: 15,
          candle_cash_earned: 24,
          candle_cash_redeemed: 14,
        },
        comparisonValues: {
          rewards_sales: 47,
          birthday_redemption_revenue: 12,
          referral_revenue: 10,
          candle_cash_earned: 18,
          candle_cash_redeemed: 12,
        },
      },
      {
        label: "Mar 21",
        primary: 62,
        comparison: 44,
        values: {
          rewards_sales: 62,
          birthday_redemption_revenue: 17,
          referral_revenue: 12,
          candle_cash_earned: 22,
          candle_cash_redeemed: 13,
        },
        comparisonValues: {
          rewards_sales: 44,
          birthday_redemption_revenue: 11,
          referral_revenue: 10,
          candle_cash_earned: 17,
          candle_cash_redeemed: 11,
        },
      },
      {
        label: "Mar 25",
        primary: 84,
        comparison: 56,
        values: {
          rewards_sales: 84,
          birthday_redemption_revenue: 24,
          referral_revenue: 18,
          candle_cash_earned: 29,
          candle_cash_redeemed: 17,
        },
        comparisonValues: {
          rewards_sales: 56,
          birthday_redemption_revenue: 14,
          referral_revenue: 12,
          candle_cash_earned: 20,
          candle_cash_redeemed: 13,
        },
      },
      {
        label: "Mar 29",
        primary: 77,
        comparison: 51,
        values: {
          rewards_sales: 77,
          birthday_redemption_revenue: 21,
          referral_revenue: 16,
          candle_cash_earned: 25,
          candle_cash_redeemed: 16,
        },
        comparisonValues: {
          rewards_sales: 51,
          birthday_redemption_revenue: 13,
          referral_revenue: 11,
          candle_cash_earned: 19,
          candle_cash_redeemed: 12,
        },
      },
    ],
    seriesOptions: [
      {
        key: "rewards_sales",
        label: "Rewards Sales",
        description: "Fallback fixture.",
        color: "#15803d",
        selected: true,
        formattedPrimaryTotal: "$468.00",
        formattedComparisonTotal: "$331.00",
      },
      {
        key: "birthday_redemption_revenue",
        label: "Birthday Redemption Revenue",
        description: "Fallback fixture.",
        color: "#d97706",
        selected: false,
        formattedPrimaryTotal: "$133.00",
        formattedComparisonTotal: "$84.00",
      },
      {
        key: "referral_revenue",
        label: "Referral Revenue",
        description: "Fallback fixture.",
        color: "#2563eb",
        selected: false,
        formattedPrimaryTotal: "$96.00",
        formattedComparisonTotal: "$76.00",
      },
      {
        key: "candle_cash_earned",
        label: "Candle Cash Earned",
        description: "Fallback fixture.",
        color: "#0f766e",
        selected: true,
        formattedPrimaryTotal: "$172.00",
        formattedComparisonTotal: "$135.00",
      },
      {
        key: "candle_cash_redeemed",
        label: "Candle Cash Redeemed",
        description: "Fallback fixture.",
        color: "#7c3aed",
        selected: true,
        formattedPrimaryTotal: "$102.00",
        formattedComparisonTotal: "$83.00",
      },
    ],
    benchmarkLabel: "Best period",
    benchmarkValue: "$8.4k",
    empty: false,
  },
  attribution: {
    title: "Attribution",
    subtitle: "Fallback source mix for development.",
    sources: [
      {
        key: "text",
        label: "Text",
        revenue: 12460,
        formattedRevenue: "$12,460.00",
        profit: 4130,
        formattedProfit: "$4,130.00",
        orders: 84,
        deltaPct: 14.8,
        deltaLabel: "+14.8%",
        tone: "positive",
        description: "Fallback SMS source card.",
        live: false,
      },
    ],
    empty: false,
  },
  locationOrigins: {
    title: "Location origins",
    subtitle: "Fallback origin mix for development.",
    grouping: "state",
    items: [
      {
        name: "Tennessee",
        orders: 48,
        revenue: 12460,
        formattedRevenue: "$12,460.00",
        share: 42,
        partial: false,
      },
    ],
    empty: false,
  },
  financialSummary: {
    title: "Financial summary",
    subtitle: "Fallback financial summary for development.",
    items: [
      {
        label: "Gross revenue touched",
        value: 72180,
        formattedValue: "$72,180.00",
        detail: "Fallback fixture.",
      },
      {
        label: "Reward cost absorbed",
        value: 11430,
        formattedValue: "$11,430.00",
        detail: "Fallback fixture.",
      },
      {
        label: "Incremental retained revenue",
        value: 28660,
        formattedValue: "$28,660.00",
        detail: "Fallback fixture.",
      },
    ],
    netProfit: {
      value: 17940,
      formattedValue: "$17,940.00",
      comparisonValue: 0,
      label: "Net profit created",
      confidenceLevel: "medium",
      detail: "Medium confidence · fallback fixture uses stored-cost style data plus conservative fee assumptions.",
    },
  },
  candleCashEngagement: {
    title: "Candle Cash earn activity",
    subtitle: "Fallback engagement section for local development.",
    earned: {
      amount: 42,
      formattedAmount: "$42.00",
      eventCount: 18,
      customerCount: 12,
      sourceSummary: "Signup / Welcome earn $16.00 (38.1%) · Referral earn $14.00 (33.3%) · Birthday earn $8.00 (19.0%)",
    },
    breakdown: {
      rows: [
        {
          key: "signup_welcome_earn",
          label: "Signup / Welcome earn",
          definition: "Fallback fixture.",
          amount: 16,
          formattedAmount: "$16.00",
          sharePct: 38.1,
          eventCount: 7,
          customerCount: 7,
        },
      ],
      sourceDefinitions: {
        signup_welcome_earn: {
          label: "Signup / Welcome earn",
          definition: "Fallback fixture.",
        },
      },
    },
    outstanding: {
      amount: 70,
      formattedAmount: "$70.00",
      customerCount: 19,
      excludedGrandfatheredAmount: 30,
      helperText: "Fallback fixture for local development.",
    },
    timeToFirstRedemption: {
      averageDays: 8.25,
      medianDays: 6.5,
      formattedAverageDays: "8.25 days",
      formattedMedianDays: "6.50 days",
      sampleCount: 11,
      approximation: "Fallback approximation note.",
    },
    customersWithOutstandingEarned: {
      count: 19,
    },
    reminderEligibility: {
      eligibleCustomers: 17,
      missingEmailCustomers: 2,
      expirationPolicy: "No fixed expiration date is currently stored for earned Candle Cash buckets in this ledger.",
      emailReadiness: {
        status: "ready_for_live_send",
        enabled: true,
        dryRun: false,
        missingReasons: [],
      },
    },
    comparison: {
      earnedAmount: 31,
      timeToFirstRedemptionAverageDays: 9.8,
    },
  },
  flags: {
    hasAnyData: true,
    usesFallbackAttribution: true,
    usesEstimatedOrderRevenue: true,
  },
};
