import React, { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { createRoot } from "react-dom/client";
import "../../css/managed-website-editor.css";

type Item = Record<string, string>;
type Block = Record<string, string | Item[] | undefined> & { id: string; type: string; items?: Item[] };
type Page = { id: number; title: string; slug: string; blocks: Block[]; seo: Record<string, string> };
type PageLink = Pick<Page, "id" | "title" | "slug"> & { url: string };
type NavigationItem = { label: string; url: string; type: "page" | "link" };
type Media = { id: number; name: string; url: string; alt_text?: string; mime_type: string };
type Theme = Record<string, unknown> & { announcement?: { enabled?: boolean; text?: string; url?: string }; theme_palette?: Record<string, string>; footer?: { copyright?: string; tagline?: string } };
type ThemeTarget = "global" | "announcement" | "header" | "footer" | "navigation";
type PreviewSelection = { type?: string; kind?: string; blockIndex?: string | null; itemIndex?: string | null; navigationIndex?: string | null; field?: string | null };

const labels: Record<string, string> = { hero: "Hero", text: "Text", image: "Image", image_with_text: "Image with text", service_cards: "Service cards", trust_bar: "Trust bar", gallery: "Gallery", faq_list: "FAQ", testimonial: "Testimonial", cta: "Call to action", contact_form: "Contact form" };
const sectionDescriptions: Record<string, string> = { hero: "A prominent first impression with one next step.", text: "A simple, readable content section.", image_with_text: "Pair an image with a helpful explanation.", cta: "Guide visitors to one clear action.", service_cards: "Group services or offerings into cards.", trust_bar: "Highlight short proof points.", testimonial: "Feature approved customer feedback.", image: "Add a single visual moment.", gallery: "Show a collection of public images.", faq_list: "Answer common customer questions.", contact_form: "Collect a tenant-owned inquiry." };
const categories = [["Story", ["hero", "text", "image_with_text", "cta"]], ["Services", ["service_cards", "trust_bar", "testimonial"]], ["Media", ["image", "gallery"]], ["Contact", ["faq_list", "contact_form"]]] as const;

function parse<T>(value: string | undefined, fallback: T): T { try { return value ? JSON.parse(value) as T : fallback; } catch { return fallback; } }
function newBlock(type: string): Block { return { id: crypto.randomUUID(), type, heading: labels[type] || "Section", body: type === "hero" ? "Add a clear message and one useful next step." : "Add useful, customer-friendly detail.", items: ["service_cards", "trust_bar", "faq_list", "gallery"].includes(type) ? [] : undefined }; }
function asIndex(value: string | null | undefined): number | null { const index = Number(value); return Number.isInteger(index) && index >= 0 ? index : null; }

function Editor({ root }: { root: HTMLElement }) {
  const initial = parse<Page>(root.dataset.page, { id: 0, title: "", slug: "", blocks: [], seo: {} });
  const pages = parse<PageLink[]>(root.dataset.pages, []);
  const initialSite = parse<{ name: string; status: string; theme: Theme; navigation: NavigationItem[]; preview_url: string; preview_site_url: string }>(root.dataset.site, { name: "Website", status: "draft", theme: {}, navigation: [], preview_url: "", preview_site_url: "" });
  const csrf = document.querySelector<HTMLMetaElement>('meta[name="csrf-token"]')?.content || "";
  const [page, setPage] = useState<Page>(initial);
  const [site, setSite] = useState(initialSite);
  const [selected, setSelected] = useState(0);
  const [selectedItem, setSelectedItem] = useState<number | null>(null);
  const [selectedField, setSelectedField] = useState<string | null>(null);
  const [mode, setMode] = useState<"sections" | "theme">("sections");
  const [themeTarget, setThemeTarget] = useState<ThemeTarget>("global");
  const [selectedNavigation, setSelectedNavigation] = useState<number | null>(null);
  const [selectedThemeField, setSelectedThemeField] = useState<string | null>(null);
  const [device, setDevice] = useState<"desktop" | "mobile">("desktop");
  const [saveState, setSaveState] = useState("Saved");
  const [media, setMedia] = useState<Media[]>([]);
  const [iframeKey, setIframeKey] = useState(0);
  const [history, setHistory] = useState<Page[]>([]);
  const [future, setFuture] = useState<Page[]>([]);
  const [sectionLibraryOpen, setSectionLibraryOpen] = useState(false);
  const [sectionSearch, setSectionSearch] = useState("");
  const pageDirty = useRef(false);
  const themeDirty = useRef(false);
  const previewFrame = useRef<HTMLIFrameElement>(null);
  const selectedBlock = page.blocks[selected];
  const mediaByUrl = useMemo(() => new Map(media.map((item) => [item.url, item])), [media]);

  const selectBlock = (index: number, itemIndex: number | null = null, field: string | null = null) => { if (!page.blocks[index]) return; setMode("sections"); setSelected(index); setSelectedItem(itemIndex); setSelectedField(field); setSelectedThemeField(null); };
  const selectTheme = (target: ThemeTarget, navigationIndex: number | null = null, field: string | null = null) => { setMode("theme"); setThemeTarget(target); setSelectedNavigation(navigationIndex); setSelectedThemeField(field); setSelectedField(null); setSelectedItem(null); };
  const commit = (next: Page) => { pageDirty.current = true; setHistory((items) => [...items.slice(-29), page]); setFuture([]); setPage(next); setSaveState("Unsaved changes"); };
  const updateBlock = (key: string, value: string) => { if (!selectedBlock) return; commit({ ...page, blocks: page.blocks.map((block, index) => index === selected ? { ...block, [key]: value } : block) }); };
  const updateItems = (items: Item[]) => { if (!selectedBlock) return; commit({ ...page, blocks: page.blocks.map((block, index) => index === selected ? { ...block, items } : block) }); };
  const move = (from: number, to: number) => { if (from === to) return; const blocks = [...page.blocks]; const [block] = blocks.splice(from, 1); blocks.splice(to, 0, block); commit({ ...page, blocks }); selectBlock(to); };
  const insertSection = (type: string) => { commit({ ...page, blocks: [...page.blocks, newBlock(type)] }); selectBlock(page.blocks.length); setSectionLibraryOpen(false); setSectionSearch(""); };
  const savePage = async (): Promise<boolean> => {
    if (!pageDirty.current) return true;
    setSaveState("Saving page…");
    const response = await fetch(root.dataset.saveUrl || "", { method: "PUT", headers: { "Content-Type": "application/json", Accept: "application/json", "X-CSRF-TOKEN": csrf }, body: JSON.stringify({ title: page.title, blocks: page.blocks, seo: page.seo }) });
    if (!response.ok) { setSaveState("Could not save page"); return false; }
    pageDirty.current = false; setSaveState("Saved"); setIframeKey((key) => key + 1); return true;
  };
  const saveTheme = async (): Promise<boolean> => {
    if (!themeDirty.current) return true;
    setSaveState("Saving theme…");
    const response = await fetch(root.dataset.themeSaveUrl || "", { method: "PUT", headers: { "Content-Type": "application/json", Accept: "application/json", "X-CSRF-TOKEN": csrf }, body: JSON.stringify({ settings: site.theme, navigation: site.navigation, seo: {} }) });
    if (!response.ok) { setSaveState("Could not save theme"); return false; }
    themeDirty.current = false; setSaveState("Saved"); setIframeKey((key) => key + 1); return true;
  };
  const updateTheme = (next: Theme) => { themeDirty.current = true; setSite((current) => ({ ...current, theme: next })); setSaveState("Unsaved changes"); };
  const updateNavigation = (next: NavigationItem[]) => { themeDirty.current = true; setSite((current) => ({ ...current, navigation: next })); setSaveState("Unsaved changes"); };
  const saveAll = async (): Promise<boolean> => (await savePage()) && (await saveTheme());
  const previewSite = async () => { const tab = window.open("about:blank", "_blank"); if (!await saveAll()) { tab?.close(); return; } if (!site.preview_site_url) { tab?.close(); return; } if (tab) { tab.opener = null; tab.location.replace(site.preview_site_url); } else window.open(site.preview_site_url, "_blank", "noopener,noreferrer"); };
  const publish = async () => { if (root.dataset.publishingEnabled !== "true" || !await saveAll()) return; setSaveState("Publishing…"); const response = await fetch(root.dataset.publishUrl || "", { method: "POST", headers: { Accept: "application/json", "X-CSRF-TOKEN": csrf } }); setSaveState(response.ok ? "Published" : "Could not publish"); };
  const loadMedia = async () => { const response = await fetch(root.dataset.mediaUrl || "", { headers: { Accept: "application/json" } }); if (response.ok) { const payload = await response.json() as { media: Media[] }; setMedia(payload.media); } };
  const upload = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.currentTarget.files?.[0]; if (!file) return; const data = new FormData(); data.append("image", file); data.append("alt_text", ""); setSaveState("Uploading image…"); const response = await fetch(root.dataset.mediaUploadUrl || "", { method: "POST", headers: { Accept: "application/json", "X-CSRF-TOKEN": csrf }, body: data }); if (response.ok) { const payload = await response.json() as { media: Media }; setMedia((items) => [payload.media, ...items]); if (selectedItem !== null && selectedField === "item_image" && selectedBlock) { updateItems((selectedBlock.items || []).map((item, index) => index === selectedItem ? { ...item, image_url: payload.media.url, image_alt: payload.media.alt_text || "" } : item)); } else { updateBlock("image_url", payload.media.url); updateBlock("image_alt", payload.media.alt_text || ""); } } else setSaveState("Could not upload image"); event.currentTarget.value = ""; };

  useEffect(() => { void loadMedia(); }, []);
  useEffect(() => { if (!pageDirty.current) return; const timer = window.setTimeout(() => void savePage(), 900); return () => window.clearTimeout(timer); }, [page]);
  useEffect(() => { if (!themeDirty.current) return; const timer = window.setTimeout(() => void saveTheme(), 900); return () => window.clearTimeout(timer); }, [site.theme, site.navigation]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "s") { event.preventDefault(); void saveAll(); } }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); });
  useEffect(() => {
    const field = mode === "sections" ? selectedField : selectedThemeField;
    if (!field) return;
    const timer = window.setTimeout(() => {
      const selector = mode === "sections" && selectedItem !== null
        ? `[data-eb-inspector-field="${field}"][data-eb-item-index="${selectedItem}"]`
        : `[data-eb-inspector-field="${field}"]`;
      document.querySelector<HTMLElement>(selector)?.focus();
    });
    return () => window.clearTimeout(timer);
  }, [mode, selected, selectedField, selectedItem, selectedThemeField]);
  useEffect(() => {
    const receiveSelection = (event: MessageEvent<PreviewSelection>) => {
      if (event.origin !== window.location.origin || event.source !== previewFrame.current?.contentWindow || event.data?.type !== "everbranch.website.editor.select") return;
      const blockIndex = asIndex(event.data.blockIndex); const itemIndex = asIndex(event.data.itemIndex); const navigationIndex = asIndex(event.data.navigationIndex);
      if (event.data.kind === "section" && blockIndex !== null) selectBlock(blockIndex, itemIndex, event.data.field || null);
      if (event.data.kind === "announcement") selectTheme("announcement", null, event.data.field || null);
      if (event.data.kind === "header") selectTheme("header", null, event.data.field || null);
      if (event.data.kind === "footer") selectTheme("footer", null, event.data.field || null);
      if (event.data.kind === "navigation" && navigationIndex !== null && site.navigation[navigationIndex]) selectTheme("navigation", navigationIndex, event.data.field || "navigation_label");
    };
    window.addEventListener("message", receiveSelection); return () => window.removeEventListener("message", receiveSelection);
  }, [page.blocks, site.navigation]);

  return <div className="eb-editor">
    <header className="eb-editor-top"><div className="eb-editor-top__left"><a className="eb-icon" href={root.dataset.indexUrl} aria-label="Back to Website">←</a><div className="eb-editor-title"><strong>{site.name}</strong><span className={site.status === "published" ? "is-live" : ""}>{site.status === "published" ? "Live" : "Draft"}</span></div><label className="eb-page-picker"><span className="sr-only">Page</span><select value={page.id} onChange={(event) => { const next = pages.find((item) => item.id === Number(event.target.value)); if (next) window.location.assign(next.url); }}>{pages.map((item) => <option key={item.id} value={item.id}>{item.slug === "/" ? "Home" : item.title}</option>)}</select></label></div><div className="eb-editor-top__right"><span className="eb-save" aria-live="polite">{saveState}</span><button className="eb-icon" onClick={() => { const previous = history.at(-1); if (!previous) return; setFuture((items) => [page, ...items]); setHistory((items) => items.slice(0, -1)); setPage(previous); pageDirty.current = true; }} disabled={!history.length} aria-label="Undo">↶</button><button className="eb-icon" onClick={() => { const next = future[0]; if (!next) return; setHistory((items) => [...items, page]); setFuture((items) => items.slice(1)); setPage(next); pageDirty.current = true; }} disabled={!future.length} aria-label="Redo">↷</button><button className="eb-button eb-button--quiet" onClick={() => void previewSite()}>Preview site</button><button className="eb-button eb-button--quiet" onClick={() => void saveAll()}>Save</button><button className="eb-button eb-button--primary" disabled={root.dataset.publishingEnabled !== "true"} onClick={() => void publish()}>Publish</button></div></header>
    <div className="eb-editor-layout"><aside className="eb-tree"><div className="eb-tabs"><button className={mode === "sections" ? "active" : ""} onClick={() => setMode("sections")}>Sections</button><button className={mode === "theme" ? "active" : ""} onClick={() => selectTheme("global")}>Theme</button></div>{mode === "sections" ? <><div className="eb-tree__heading">{page.title}</div><button className="eb-tree__fixed" onClick={() => selectTheme("announcement")}>Announcement</button><button className="eb-tree__fixed" onClick={() => selectTheme("header")}>Header & menu</button><div className="eb-tree__sections">{page.blocks.map((block, index) => <button key={block.id || `${block.type}-${index}`} draggable onDragStart={(event) => event.dataTransfer.setData("text/plain", String(index))} onDragOver={(event) => event.preventDefault()} onDrop={(event) => { const from = Number(event.dataTransfer.getData("text/plain")); if (Number.isFinite(from)) move(from, index); }} className={selected === index ? "is-selected" : ""} onClick={() => selectBlock(index)}><span className="eb-grip">⋮⋮</span><span>{labels[block.type] || block.type}</span><small>{block.hidden === "true" ? "Hidden" : ""}</small></button>)}</div><button className="eb-add-section" onClick={() => setSectionLibraryOpen(true)}><span aria-hidden="true">＋</span> Add section</button><button className="eb-tree__fixed" onClick={() => selectTheme("footer")}>Footer</button></> : <ThemeTree site={site} pages={pages} updateTheme={updateTheme} updateNavigation={updateNavigation} />}</aside><main className="eb-canvas"><div className="eb-device-toggle"><button className={device === "desktop" ? "active" : ""} onClick={() => setDevice("desktop")}>Desktop</button><button className={device === "mobile" ? "active" : ""} onClick={() => setDevice("mobile")}>Mobile</button></div><div className={`eb-preview-frame ${device}`}><iframe ref={previewFrame} key={iframeKey} title="Draft website editor canvas" src={site.preview_url} /></div><p className="eb-canvas__hint">Select a sentence, button, image, card, or menu item to edit that exact element. Use Preview site to test customer navigation.</p></main><aside className="eb-inspector">{mode === "sections" ? <SectionInspector block={selectedBlock} media={media} selectedMedia={selectedBlock?.image_url ? mediaByUrl.get(String(selectedBlock.image_url)) : undefined} selectedItem={selectedItem} selectedField={selectedField} update={updateBlock} updateItems={updateItems} upload={upload} remove={() => { if (page.blocks.length <= 1) return; commit({ ...page, blocks: page.blocks.filter((_, index) => index !== selected) }); selectBlock(Math.max(0, selected - 1)); }} /> : <ThemeInspector theme={site.theme} navigation={site.navigation} pages={pages} target={themeTarget} selectedNavigation={selectedNavigation} updateTheme={updateTheme} updateNavigation={updateNavigation} />}</aside></div>
    {sectionLibraryOpen && <SectionLibrary search={sectionSearch} updateSearch={setSectionSearch} add={insertSection} close={() => setSectionLibraryOpen(false)} />}
  </div>;
}

function SectionLibrary({ search, updateSearch, add, close }: { search: string; updateSearch: (value: string) => void; add: (type: string) => void; close: () => void }) { const normalized = search.trim().toLowerCase(); const filtered = categories.map(([category, types]) => [category, types.filter((type) => !normalized || `${category} ${labels[type]}`.toLowerCase().includes(normalized))] as const).filter(([, types]) => types.length > 0); return <div className="eb-library-backdrop" role="presentation" onMouseDown={close}><section className="eb-section-library" role="dialog" aria-modal="true" aria-label="Add a section" onMouseDown={(event) => event.stopPropagation()}><div className="eb-library__top"><strong>Add a section</strong><button onClick={close} aria-label="Close section library">×</button></div><label className="eb-library__search"><span aria-hidden="true">⌕</span><input autoFocus value={search} onChange={(event) => updateSearch(event.target.value)} placeholder="Search sections" /></label><p className="eb-library__hint">Choose a structured section, then tailor its content in the inspector.</p><div className="eb-library__list">{filtered.map(([category, types]) => <section key={category}><h2>{category}</h2>{types.map((type) => <button key={type} onClick={() => add(type)}><span className="eb-library__icon" aria-hidden="true">{type === "image" || type === "gallery" ? "▧" : type === "faq_list" ? "?" : type === "contact_form" ? "✉" : "▤"}</span><span><strong>{labels[type]}</strong><small>{sectionDescriptions[type]}</small></span></button>)}</section>)}</div>{!filtered.length && <p className="eb-library__empty">No section matches “{search}”.</p>}</section></div>; }

function ThemeTree({ site, pages, updateTheme, updateNavigation }: { site: { theme: Theme; navigation: NavigationItem[] }; pages: PageLink[]; updateTheme: (theme: Theme) => void; updateNavigation: (items: NavigationItem[]) => void }) { const announcement = site.theme.announcement || {}; return <div className="eb-theme-tree"><div className="eb-tree__heading">Theme settings</div><label><input type="checkbox" checked={Boolean(announcement.enabled)} onChange={(event) => updateTheme({ ...site.theme, announcement: { ...announcement, enabled: event.target.checked } })} /> Show announcement</label><label>Announcement<input value={String(announcement.text || "")} onChange={(event) => updateTheme({ ...site.theme, announcement: { ...announcement, text: event.target.value } })} /></label><label>Announcement link<input value={String(announcement.url || "")} onChange={(event) => updateTheme({ ...site.theme, announcement: { ...announcement, url: event.target.value } })} /></label><div className="eb-menu-heading">Menu</div>{site.navigation.map((item, index) => <div className="eb-menu-row" key={`${item.url}-${index}`}><input value={item.label} aria-label={`Menu label ${index + 1}`} onChange={(event) => updateNavigation(site.navigation.map((candidate, itemIndex) => itemIndex === index ? { ...candidate, label: event.target.value } : candidate))} /><select value={item.url} aria-label={`Menu destination ${index + 1}`} onChange={(event) => updateNavigation(site.navigation.map((candidate, itemIndex) => itemIndex === index ? { ...candidate, url: event.target.value, type: "page" } : candidate))}>{pages.map((candidate) => <option key={candidate.id} value={candidate.slug === "/" ? "/" : `/${candidate.slug}`}>{candidate.title}</option>)}</select><button onClick={() => updateNavigation(site.navigation.filter((_, itemIndex) => itemIndex !== index))} aria-label="Remove menu item">×</button></div>)}<button className="eb-text-button" onClick={() => { const first = pages.find((candidate) => !site.navigation.some((item) => item.url === (candidate.slug === "/" ? "/" : `/${candidate.slug}`))); if (first) updateNavigation([...site.navigation, { label: first.title, url: first.slug === "/" ? "/" : `/${first.slug}`, type: "page" }]); }}>Add a page to menu</button></div>; }

function ThemeInspector({ theme, navigation, pages, target, selectedNavigation, updateTheme, updateNavigation }: { theme: Theme; navigation: NavigationItem[]; pages: PageLink[]; target: ThemeTarget; selectedNavigation: number | null; updateTheme: (theme: Theme) => void; updateNavigation: (items: NavigationItem[]) => void }) {
  const palette = theme.theme_palette || {}; const footer = theme.footer || {}; const announcement = theme.announcement || {};
  const setPalette = (key: string, value: string) => updateTheme({ ...theme, theme_palette: { ...palette, [key]: value } });
  const updateItem = (index: number, patch: Partial<NavigationItem>) => updateNavigation(navigation.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  if (target === "announcement") return <div className="eb-inspector__body"><InspectorHead title="Announcement" detail="This bar appears above the site header." /><label className="eb-toggle"><input type="checkbox" checked={Boolean(announcement.enabled)} onChange={(event) => updateTheme({ ...theme, announcement: { ...announcement, enabled: event.target.checked } })} /> Show announcement</label><label>Message<input data-eb-inspector-field="announcement_text" value={String(announcement.text || "")} onChange={(event) => updateTheme({ ...theme, announcement: { ...announcement, text: event.target.value } })} /></label><label>Link<input data-eb-inspector-field="announcement_url" value={String(announcement.url || "")} onChange={(event) => updateTheme({ ...theme, announcement: { ...announcement, url: event.target.value } })} placeholder="/contact or https://" /></label></div>;
  if (target === "navigation" && selectedNavigation !== null && navigation[selectedNavigation]) { const item = navigation[selectedNavigation]; return <div className="eb-inspector__body"><InspectorHead title="Menu item" detail="This link stays inside your Website preview when it points to one of your pages." /><label>Label<input data-eb-inspector-field="navigation_label" value={item.label} onChange={(event) => updateItem(selectedNavigation, { label: event.target.value })} /></label><label>Destination<select data-eb-inspector-field="navigation_url" value={item.url} onChange={(event) => updateItem(selectedNavigation, { url: event.target.value, type: "page" })}>{pages.map((candidate) => <option key={candidate.id} value={candidate.slug === "/" ? "/" : `/${candidate.slug}`}>{candidate.title}</option>)}</select></label><button className="eb-delete" onClick={() => updateNavigation(navigation.filter((_, index) => index !== selectedNavigation))}>Remove menu item</button></div>; }
  if (target === "footer") return <div className="eb-inspector__body"><InspectorHead title="Footer" detail="Shown at the bottom of every page." /><label>Footer line<input data-eb-inspector-field="footer_tagline" value={String(footer.tagline || "")} onChange={(event) => updateTheme({ ...theme, footer: { ...footer, tagline: event.target.value } })} /></label><label>Copyright<input data-eb-inspector-field="footer_copyright" value={String(footer.copyright || "")} onChange={(event) => updateTheme({ ...theme, footer: { ...footer, copyright: event.target.value } })} /></label></div>;
  return <div className="eb-inspector__body"><InspectorHead title={target === "header" ? "Header & menu" : "Theme settings"} detail={target === "header" ? "Your site name and menus are shared across pages." : "Applied to the entire website draft."} /><label>Theme name<input data-eb-inspector-field="theme_name" value={String(theme.theme_name || "")} onChange={(event) => updateTheme({ ...theme, theme_name: event.target.value })} /></label>{target === "global" && <><label>Typography<select value={String(theme.typography || "sans")} onChange={(event) => updateTheme({ ...theme, typography: event.target.value })}><option value="sans">Modern sans</option><option value="serif">Editorial serif</option><option value="system">System</option></select></label><label>Corner style<select value={String(theme.corners || "soft")} onChange={(event) => updateTheme({ ...theme, corners: event.target.value })}><option value="square">Square</option><option value="soft">Soft</option><option value="rounded">Rounded</option></select></label><div className="eb-colors">{["brand", "accent", "ink", "surface", "soft"].map((key) => <label key={key}>{key}<input type="color" value={String(palette[key] || "#ffffff")} onChange={(event) => setPalette(key, event.target.value)} /></label>)}</div></>}<div className="eb-items"><strong>Menu</strong>{navigation.map((item, index) => <div className="eb-item" key={`${item.url}-${index}`}><label>Label<input value={item.label} onChange={(event) => updateItem(index, { label: event.target.value })} /></label><label>Destination<select value={item.url} onChange={(event) => updateItem(index, { url: event.target.value, type: "page" })}>{pages.map((candidate) => <option key={candidate.id} value={candidate.slug === "/" ? "/" : `/${candidate.slug}`}>{candidate.title}</option>)}</select></label></div>)}</div></div>;
}
function InspectorHead({ title, detail }: { title: string; detail: string }) { return <div className="eb-inspector__head"><strong>{title}</strong><span>{detail}</span></div>; }

function SectionInspector({ block, media, selectedMedia, selectedItem, selectedField, update, updateItems, upload, remove }: { block?: Block; media: Media[]; selectedMedia?: Media; selectedItem: number | null; selectedField: string | null; update: (key: string, value: string) => void; updateItems: (items: Item[]) => void; upload: (event: ChangeEvent<HTMLInputElement>) => void; remove: () => void }) {
  if (!block) return <div className="eb-inspector__empty">Select an element in the canvas to edit that exact content.</div>;
  const items = block.items || [];
  const hasItems = ["service_cards", "trust_bar", "faq_list", "gallery"].includes(block.type);
  const selectedCard = selectedItem !== null ? items[selectedItem] : undefined;
  const updateItem = (key: string, value: string) => { if (selectedItem === null) return; updateItems(items.map((item, index) => index === selectedItem ? { ...item, [key]: value } : item)); };
  const activeMedia = selectedCard && selectedField === "item_image" ? media.find((item) => item.url === selectedCard.image_url) : selectedMedia;
  const chooseImage = (item: Media) => { if (selectedCard && selectedItem !== null) { updateItems(items.map((candidate, index) => index === selectedItem ? { ...candidate, image_url: item.url, image_alt: item.alt_text || "" } : candidate)); } else { update("image_url", item.url); update("image_alt", item.alt_text || ""); } };
  if (selectedCard) return <div className="eb-inspector__body"><InspectorHead title={block.type === "faq_list" ? "Question" : block.type === "gallery" ? "Gallery image" : "Card"} detail="Editing this individual element." />{block.type !== "gallery" && <><label>Heading<input data-eb-inspector-field="item_heading" data-eb-item-index={selectedItem} value={selectedCard.heading || ""} onChange={(event) => updateItem("heading", event.target.value)} /></label><label>Text<textarea data-eb-inspector-field="item_body" data-eb-item-index={selectedItem} value={selectedCard.body || ""} onChange={(event) => updateItem("body", event.target.value)} /></label></>}<div className="eb-media-picker"><strong>Image</strong><label className="eb-upload">Upload image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={upload} /></label><div className="eb-media-grid">{media.slice(0, 12).map((item) => <button key={item.id} className={activeMedia?.id === item.id ? "is-selected" : ""} onClick={() => chooseImage(item)}><img src={item.url} alt="" /></button>)}</div><label>Image URL<input data-eb-inspector-field="item_image" data-eb-item-index={selectedItem} value={String(selectedCard.image_url || "")} onChange={(event) => updateItem("image_url", event.target.value)} /></label><label>Image description<input value={String(selectedCard.image_alt || "")} onChange={(event) => updateItem("image_alt", event.target.value)} /></label></div><button className="eb-delete" onClick={() => updateItems(items.filter((_, index) => index !== selectedItem))}>Remove {block.type === "faq_list" ? "question" : "item"}</button></div>;
  return <div className="eb-inspector__body"><InspectorHead title={labels[block.type] || block.type} detail={selectedField === "cta_label" ? "Button selected in the canvas." : selectedField ? "Element selected in the canvas." : "Section settings"} /><label>Eyebrow<input data-eb-inspector-field="label" value={String(block.label || "")} onChange={(event) => update("label", event.target.value)} /></label><label>Heading<input data-eb-inspector-field="heading" value={String(block.heading || "")} onChange={(event) => update("heading", event.target.value)} /></label><label>Text<textarea data-eb-inspector-field="body" value={String(block.body || "")} onChange={(event) => update("body", event.target.value)} /></label><label>Button label<input data-eb-inspector-field="cta_label" value={String(block.cta_label || "")} onChange={(event) => update("cta_label", event.target.value)} /></label><label>Button link<input data-eb-inspector-field="cta_url" value={String(block.cta_url || "")} onChange={(event) => update("cta_url", event.target.value)} placeholder="/contact, https://, tel:" /></label><label className="eb-toggle"><input type="checkbox" checked={block.hidden === "true"} onChange={(event) => update("hidden", event.target.checked ? "true" : "false")} /> Hide this section</label><div className="eb-media-picker"><strong>Image</strong><label className="eb-upload">Upload image<input type="file" accept="image/jpeg,image/png,image/webp,image/avif" onChange={upload} /></label><div className="eb-media-grid">{media.slice(0, 12).map((item) => <button key={item.id} className={selectedMedia?.id === item.id ? "is-selected" : ""} onClick={() => chooseImage(item)}><img src={item.url} alt="" /></button>)}</div><label>Image URL<input data-eb-inspector-field="image" value={String(block.image_url || "")} onChange={(event) => update("image_url", event.target.value)} /></label><label>Image description<input value={String(block.image_alt || "")} onChange={(event) => update("image_alt", event.target.value)} /></label></div>{hasItems && <div className="eb-items"><strong>{block.type === "faq_list" ? "Questions" : block.type === "gallery" ? "Images" : "Cards"}</strong><p className="eb-items__hint">Select an individual item in the canvas to edit only that item.</p><button className="eb-text-button" onClick={() => updateItems([...items, { heading: "New item", body: "Add a useful detail." }])}>Add item</button></div>}<button className="eb-delete" onClick={remove}>Remove section</button></div>;
}

export function mountManagedWebsiteEditorNow() { const root = document.getElementById("managed-website-editor-root"); if (!root || root.dataset.mounted) return; root.dataset.mounted = "true"; createRoot(root).render(<Editor root={root} />); }
mountManagedWebsiteEditorNow();
