<x-layouts::app.sidebar title="Equipment maintenance">
    <flux:main><div class="fb-workflow-shell space-y-6">
        <header class="flex flex-wrap items-start justify-between gap-4 border-b border-zinc-200 pb-5"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-emerald-700">{{ $tenant->name }} · Field service</p><h1 class="mt-1 text-3xl font-semibold text-zinc-950">Equipment maintenance</h1><p class="mt-2 text-sm text-zinc-600">Customer-linked generators, service intervals, work tasks, notes, technicians, and photos.</p></div><div class="flex gap-2"><a href="{{ route('field-service.calendar') }}" class="fb-btn fb-btn-secondary">Work calendar</a><a href="{{ route('field-service.payroll-hours') }}" class="fb-btn fb-btn-secondary">Payroll hours</a></div></header>
        @if(session('status'))<div class="fb-state fb-state-success">{{ session('status') }}</div>@endif
        @if($canManage)<section class="fb-panel"><div class="fb-panel-head"><div><div class="fb-panel-title">Add customer equipment</div><div class="fb-panel-copy">The next due date is calculated from last service or installation when left blank.</div></div></div><div class="fb-panel-body"><form method="POST" action="{{ route('field-service.equipment.store') }}" class="grid gap-3 md:grid-cols-3">@csrf
            <label class="text-sm font-semibold">Customer<select name="marketing_profile_id" required class="mt-1 w-full rounded-lg border-zinc-300"><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ trim($customer->first_name.' '.$customer->last_name) ?: $customer->email }}</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Responsible technician<select name="assigned_user_id" required class="mt-1 w-full rounded-lg border-zinc-300"><option value="">Select technician</option>@foreach($team as $member)<option value="{{ $member->id }}">{{ $member->name ?: $member->email }}</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Equipment name<input name="name" required placeholder="Home standby generator" class="mt-1 w-full rounded-lg border-zinc-300"></label>
            <label class="text-sm font-semibold">Type<input name="equipment_type" value="generator" required class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Manufacturer<input name="manufacturer" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Model<input name="model_number" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Serial number<input name="serial_number" class="mt-1 w-full rounded-lg border-zinc-300"></label>
            <label class="text-sm font-semibold">Installed<input type="date" name="installed_at" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Last serviced<input type="date" name="last_serviced_at" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Interval (days)<input type="number" name="maintenance_interval_days" value="365" min="1" max="3650" required class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Next due (optional)<input type="date" name="next_service_due_at" class="mt-1 w-full rounded-lg border-zinc-300"></label>
            <label class="text-sm font-semibold md:col-span-2">Notes<textarea name="notes" rows="2" class="mt-1 w-full rounded-lg border-zinc-300"></textarea></label><div class="flex items-end"><button class="fb-btn fb-btn-primary w-full justify-center">Add equipment</button></div>
        </form></div></section>@endif
        <section class="fb-panel"><div class="fb-panel-head"><div class="fb-panel-title">Maintenance board</div><div class="fb-panel-copy">Equipment due within 30 days is converted into an idempotent field-service job and assigned task by the daily scanner.</div></div><div class="fb-panel-body grid gap-3 lg:grid-cols-2">
            @forelse($equipment as $item)@php $due=$item->next_service_due_at; $overdue=$due?->isPast(); $smsConsented=(bool)$item->customer?->accepts_sms_marketing && !$item->customer?->sms_opted_out_at && filled($item->customer?->phone ?: $item->customer?->normalized_phone); @endphp<a href="{{ route('field-service.equipment.show', $item) }}" class="rounded-xl border {{ $overdue ? 'border-rose-300 bg-rose-50' : 'border-zinc-200 bg-white' }} p-4 transition hover:border-emerald-500"><div class="flex justify-between gap-3"><div><div class="font-semibold text-zinc-950">{{ $item->name }}</div><div class="mt-1 text-sm text-zinc-600">{{ trim(($item->customer?->first_name ?? '').' '.($item->customer?->last_name ?? '')) ?: 'Customer' }} · {{ $item->manufacturer }} {{ $item->model_number }}</div></div><span class="text-xs font-semibold {{ $overdue ? 'text-rose-700' : 'text-zinc-600' }}">{{ $due ? ($overdue ? 'Overdue '.$due->format('M j') : 'Due '.$due->format('M j, Y')) : 'No due date' }}</span></div><div class="mt-3 flex flex-wrap gap-3 text-xs text-zinc-600"><span>{{ $item->assignedUser?->name ?? 'Unassigned' }}</span><span>{{ $item->maintenance_interval_days }}-day interval</span><span>{{ $item->open_service_jobs_count }} open work item(s)</span><span class="font-semibold {{ $smsConsented ? 'text-emerald-700' : 'text-amber-700' }}">{{ $smsConsented ? 'Customer SMS consent recorded' : 'Customer SMS consent/phone needed' }}</span></div></a>@empty<p class="text-sm text-zinc-600">No equipment yet.</p>@endforelse
        </div></section>
    </div></flux:main>
</x-layouts::app.sidebar>
