<x-layouts::app.sidebar title="Equipment maintenance">
    <flux:main><div class="fb-workflow-shell space-y-6">
        <header class="flex flex-wrap items-start justify-between gap-4 border-b border-zinc-200 pb-5"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-emerald-700">{{ $tenant->name }} · Field service</p><h1 class="mt-1 text-3xl font-semibold text-zinc-950">Equipment maintenance</h1><p class="mt-2 text-sm text-zinc-600">Customer-linked generators, service intervals, work tasks, notes, technicians, and photos.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('field-service.equipment.calendar') }}" class="fb-btn fb-btn-secondary">Maintenance calendar</a><a href="{{ route('field-service.calendar') }}" class="fb-btn fb-btn-secondary">Work calendar</a><a href="{{ route('field-service.payroll-hours') }}" class="fb-btn fb-btn-secondary">Payroll hours</a></div></header>
        @if(session('status'))<div class="fb-state fb-state-success">{{ session('status') }}</div>@endif
        @if($canManage)<section class="fb-panel"><div class="fb-panel-head"><div><div class="fb-panel-title">Add customer equipment</div><div class="fb-panel-copy">The next due date is calculated from last service or installation when left blank.</div></div></div><div class="fb-panel-body"><form method="POST" action="{{ route('field-service.equipment.store') }}" class="grid gap-3 md:grid-cols-3">@csrf
            <label class="text-sm font-semibold">Customer<select name="marketing_profile_id" required class="mt-1 w-full rounded-lg border-zinc-300"><option value="">Select customer</option>@foreach($customers as $customer)<option value="{{ $customer->id }}">{{ trim($customer->first_name.' '.$customer->last_name) ?: $customer->email }}</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Responsible technician<select name="assigned_user_id" required class="mt-1 w-full rounded-lg border-zinc-300"><option value="">Select technician</option>@foreach($team as $member)<option value="{{ $member->id }}">{{ $member->name ?: $member->email }}</option>@endforeach</select></label>
            <label class="text-sm font-semibold">Equipment name<input name="name" required placeholder="Home standby generator" class="mt-1 w-full rounded-lg border-zinc-300"></label>
            <label class="text-sm font-semibold">Type<input name="equipment_type" value="generator" required class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Manufacturer<input name="manufacturer" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Model<input name="model_number" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Serial number<input name="serial_number" class="mt-1 w-full rounded-lg border-zinc-300"></label>
            <label class="text-sm font-semibold">Installed<input type="date" name="installed_at" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Last serviced<input type="date" name="last_serviced_at" class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Interval (days)<input type="number" name="maintenance_interval_days" value="365" min="1" max="3650" required class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Next due (optional)<input type="date" name="next_service_due_at" class="mt-1 w-full rounded-lg border-zinc-300"></label>
            <label class="text-sm font-semibold md:col-span-2">Notes<textarea name="notes" rows="2" class="mt-1 w-full rounded-lg border-zinc-300"></textarea></label><div class="flex items-end"><button class="fb-btn fb-btn-primary w-full justify-center">Add equipment</button></div>
        </form></div></section>@endif
        <section class="fb-panel"><div class="fb-panel-head"><div><div class="fb-panel-title">Generator inventory</div><div class="fb-panel-copy">{{ $equipment->count() }} imported record{{ $equipment->count() === 1 ? '' : 's' }}, organized by installation year. Open a year to review its spreadsheet. Equipment due within 30 days is converted into an idempotent field-service job and assigned task by the daily scanner.</div></div></div><div class="fb-panel-body space-y-3">
            @forelse($equipmentByInstallationYear as $year => $items)
                <details class="overflow-hidden rounded-lg border border-zinc-200 bg-white" @if($loop->first) open @endif>
                    <summary class="flex cursor-pointer items-center justify-between gap-4 px-4 py-3 text-sm font-semibold text-zinc-900 marker:text-emerald-700 hover:bg-zinc-50">
                        <span>Installed {{ $year }}</span><span class="text-xs font-medium text-zinc-500">{{ $items->count() }} generator{{ $items->count() === 1 ? '' : 's' }}</span>
                    </summary>
                    <div class="overflow-x-auto border-t border-zinc-200"><table class="min-w-[980px] w-full text-left text-sm"><thead class="bg-zinc-50 text-xs font-semibold uppercase tracking-wide text-zinc-600"><tr><th scope="col" class="px-4 py-3">Installed</th><th scope="col" class="px-4 py-3">Customer</th><th scope="col" class="px-4 py-3">Generator</th><th scope="col" class="px-4 py-3">Make / model</th><th scope="col" class="px-4 py-3">Last service</th><th scope="col" class="px-4 py-3">Next service</th><th scope="col" class="px-4 py-3">Work</th></tr></thead><tbody class="divide-y divide-zinc-200">
                        @foreach($items as $item)@php $due=$item->next_service_due_at; $overdue=$due?->isPast(); @endphp<tr class="transition hover:bg-emerald-50/40"><td class="whitespace-nowrap px-4 py-3 text-zinc-700">{{ $item->installed_at?->format('M j, Y') ?? 'Not recorded' }}</td><td class="px-4 py-3 font-medium text-zinc-900">{{ trim(($item->customer?->first_name ?? '').' '.($item->customer?->last_name ?? '')) ?: 'Customer' }}</td><td class="px-4 py-3"><a href="{{ route('field-service.equipment.show', $item) }}" class="font-semibold text-emerald-800 underline-offset-2 hover:underline">{{ $item->name }}</a><div class="mt-0.5 text-xs text-zinc-500">{{ $item->assignedUser?->name ?? 'Unassigned' }} · {{ $item->maintenance_interval_days }}-day interval</div></td><td class="px-4 py-3 text-zinc-700">{{ trim(($item->manufacturer ?? '').' '.($item->model_number ?? '')) ?: 'Not recorded' }}</td><td class="whitespace-nowrap px-4 py-3 text-zinc-700">{{ $item->last_serviced_at?->format('M j, Y') ?? 'Not recorded' }}</td><td class="whitespace-nowrap px-4 py-3 font-medium {{ $overdue ? 'text-rose-700' : 'text-zinc-800' }}">{{ $due ? ($overdue ? 'Overdue · '.$due->format('M j, Y') : $due->format('M j, Y')) : 'Not scheduled' }}</td><td class="whitespace-nowrap px-4 py-3 text-zinc-700">{{ $item->open_service_jobs_count }} open</td></tr>@endforeach
                    </tbody></table></div>
                </details>
            @empty<p class="text-sm text-zinc-600">No equipment yet.</p>@endforelse
        </div></section>
    </div></flux:main>
</x-layouts::app.sidebar>
