<x-layouts::app.sidebar title="Equipment service history"><flux:main><div class="fb-workflow-shell space-y-6">
    <header class="border-b border-zinc-200 pb-5"><a href="{{ route('field-service.equipment.index') }}" class="text-sm font-semibold text-emerald-800">← Equipment maintenance</a><div class="mt-3 flex flex-wrap justify-between gap-4"><div><p class="text-xs font-semibold uppercase tracking-[.18em] text-zinc-500">{{ trim(($equipment->customer?->first_name ?? '').' '.($equipment->customer?->last_name ?? '')) ?: 'Customer' }}</p><h1 class="mt-1 text-3xl font-semibold text-zinc-950">{{ $equipment->name }}</h1><p class="mt-2 text-sm text-zinc-600">{{ $equipment->manufacturer }} {{ $equipment->model_number }} @if($equipment->serial_number)· Serial {{ $equipment->serial_number }}@endif</p></div><div class="rounded-xl border border-zinc-200 bg-zinc-50 px-4 py-3 text-sm"><div><strong>Installed:</strong> {{ $equipment->installed_at?->format('M j, Y') ?? 'Not recorded' }}</div><div><strong>Last service:</strong> {{ $equipment->last_serviced_at?->format('M j, Y') ?? 'Not recorded' }}</div><div><strong>Next due:</strong> {{ $equipment->next_service_due_at?->format('M j, Y') ?? 'Not scheduled' }}</div><div><strong>Assigned:</strong> {{ $equipment->assignedUser?->name ?? 'Unassigned' }}</div></div></div></header>
    @if(session('status'))<div class="fb-state fb-state-success">{{ session('status') }}</div>@endif
    @if($equipment->notes)<div class="rounded-xl border border-zinc-200 bg-zinc-50 p-4 text-sm text-zinc-700"><strong>Equipment notes:</strong> {{ $equipment->notes }}</div>@endif
    @if($canManage)<section class="fb-panel"><div class="fb-panel-head"><div class="fb-panel-title">Schedule maintenance work</div></div><div class="fb-panel-body"><form method="POST" action="{{ route('field-service.equipment.service-jobs.store', $equipment) }}" class="grid gap-3 md:grid-cols-[1fr_1fr_2fr_auto]">@csrf<label class="text-sm font-semibold">Date/time<input name="scheduled_for" type="datetime-local" required class="mt-1 w-full rounded-lg border-zinc-300"></label><label class="text-sm font-semibold">Technician<select name="assigned_user_id" required class="mt-1 w-full rounded-lg border-zinc-300">@foreach($team as $member)<option value="{{ $member->id }}" @selected($equipment->assigned_user_id===$member->id)>{{ $member->name ?: $member->email }}</option>@endforeach</select></label><label class="text-sm font-semibold">Work notes<input name="notes" class="mt-1 w-full rounded-lg border-zinc-300" placeholder="Requested maintenance or reported issue"></label><div class="flex items-end"><button class="fb-btn fb-btn-primary">Create work task</button></div></form></div></section>@endif
    <section class="fb-panel"><div class="fb-panel-head"><div><div class="fb-panel-title">Service history</div><div class="fb-panel-copy">Each record is a field-service job; its technician, updates, tasks, notes, and images remain together.</div></div></div><div class="fb-panel-body space-y-4">@forelse($equipment->serviceJobs as $job)<article class="rounded-xl border border-zinc-200 p-4"><div class="flex flex-wrap justify-between gap-3"><div><a href="{{ route('field-service.jobs.show', $job) }}" class="font-semibold text-emerald-800 hover:underline">{{ $job->title }}</a><div class="mt-1 text-sm text-zinc-600">{{ $job->assignedUser?->name ?? 'Unassigned' }} · {{ $job->scheduled_for?->format('M j, Y g:ia') ?? 'Unscheduled' }}</div></div><span class="rounded-full bg-zinc-100 px-3 py-1 text-xs font-semibold">{{ str_replace('_',' ', $job->operational_status ?: $job->status) }}</span></div>
        @if($job->notes->isNotEmpty())<div class="mt-3 space-y-2">@foreach($job->notes as $note)<div class="rounded-lg bg-zinc-50 p-3 text-sm"><strong>{{ $note->createdBy?->name ?? 'Technician' }}:</strong> {{ $note->body }}</div>@endforeach</div>@endif
        @if($job->photos->isNotEmpty())<div class="mt-3 grid grid-cols-4 gap-2">@foreach($job->photos as $photo)<a href="{{ $photo->file_path }}" class="aspect-square overflow-hidden rounded-lg border"><img src="{{ $photo->file_path }}" alt="{{ $photo->caption ?: 'Service photo' }}" class="h-full w-full object-cover"></a>@endforeach</div>@endif
    </article>@empty<p class="text-sm text-zinc-600">No service history yet.</p>@endforelse</div></section>
</div></flux:main></x-layouts::app.sidebar>
