<x-app-layout>
    <x-slot name="header"><div><h1 class="text-xl font-semibold text-zinc-950">Account Help</h1><p class="mt-1 text-sm text-zinc-600">Search first, then start a conversation with the Everbranch team.</p></div></x-slot>
    <div class="mx-auto max-w-6xl space-y-6">
        @if(session('success'))<div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-900">{{ session('success') }}</div>@endif
        <section class="rounded-3xl border border-blue-200 bg-gradient-to-br from-blue-50 via-white to-sky-50 p-6 shadow-sm"><p class="text-xs font-semibold uppercase tracking-[.2em] text-blue-800">Everbranch support</p><h2 class="mt-2 text-2xl font-semibold text-zinc-950">What do you need help with?</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-zinc-700">Search open conversations, ask Bud, or send the team a clear ticket.</p><input id="ticket-search" type="search" placeholder="Search tickets, subjects, or status…" class="mt-5 w-full rounded-2xl border border-zinc-300 bg-white px-4 py-3 text-zinc-950 placeholder:text-zinc-500 shadow-sm focus:border-blue-500 focus:ring-4 focus:ring-blue-200/60"></section>
        <div class="grid gap-6 lg:grid-cols-[1.1fr_.9fr]">
            <section class="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><div class="flex items-center justify-between gap-3"><div><h2 class="text-lg font-semibold">Your conversations</h2><p class="text-sm text-zinc-600">Replies, status, and resolution stay in one thread.</p></div><span class="rounded-full bg-zinc-100 px-3 py-1 text-xs font-semibold text-zinc-600">{{ $tickets->count() }}</span></div><div id="ticket-list" class="mt-5 space-y-3">@forelse($tickets as $ticket)<a data-ticket href="{{ route('account-help.show', $ticket['id']) }}" class="block rounded-2xl border border-zinc-200 p-4 transition hover:border-emerald-300 hover:bg-emerald-50/50"><div class="flex items-start justify-between gap-3"><div><p class="font-semibold text-zinc-950">{{ $ticket['subject'] }}</p><p class="mt-1 text-xs text-zinc-500">{{ ucfirst(str_replace('_', ' ', $ticket['status'])) }} · {{ ucfirst($ticket['priority']) }} priority · {{ $ticket['messages_count'] }} messages</p></div><span class="text-xs font-semibold text-emerald-800">Open →</span></div></a>@empty<div class="rounded-2xl border border-dashed border-zinc-300 bg-zinc-50 p-6 text-sm text-zinc-600">No conversations yet. Start with a short description of what you were trying to do.</div>@endforelse</div></section>
            <div class="space-y-6">
                <section class="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><div><h2 class="text-lg font-semibold">Ask Bud</h2><p class="mt-1 text-sm text-zinc-600">Included workspace help. Bud can explain what is available and point you to the next useful step.</p></div><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $budCoreEnabled ? 'bg-emerald-100 text-emerald-800' : 'bg-zinc-100 text-zinc-600' }}">{{ $budCoreEnabled ? 'Included' : 'Temporarily unavailable' }}</span></div>@if($budCoreEnabled)<form method="post" action="{{ route('account-help.bud.ask') }}" class="mt-4 space-y-3">@csrf<textarea name="question" required rows="3" placeholder="Ask about your workspace…" class="w-full rounded-xl border-zinc-300 text-sm"></textarea><button class="rounded-xl bg-zinc-950 px-4 py-2 text-sm font-semibold text-white">Ask Bud</button></form>@else<div class="mt-4 rounded-xl bg-zinc-50 px-4 py-3 text-sm text-zinc-600">Bud is temporarily unavailable. You can still send the Everbranch team a support ticket below.</div>@endif@if(session('bud_answer'))<div class="mt-4 rounded-2xl bg-emerald-50 p-4 text-sm leading-6 text-emerald-950 whitespace-pre-line">{{ session('bud_answer.reply') }}@if(session('bud_answer.ticket_id'))<a class="mt-2 block font-semibold underline" href="{{ route('account-help.show', session('bud_answer.ticket_id')) }}">Open the support ticket →</a>@endif</div>@endif</section>
                <section class="rounded-3xl border border-violet-200 bg-violet-50 p-5 shadow-sm"><div class="flex items-start justify-between gap-3"><div><p class="text-xs font-semibold uppercase tracking-[.16em] text-violet-800">Paid add-on</p><h2 class="mt-1 text-lg font-semibold text-zinc-950">Bud AI</h2><p class="mt-1 text-sm leading-6 text-zinc-700">A model-backed drafting assistant, only after Everbranch confirms the plan and a hard monthly workspace cap. It will never send or publish without a person confirming.</p></div><span class="rounded-full bg-white px-3 py-1 text-xs font-semibold text-violet-800">{{ ucfirst(str_replace('_', ' ', $budSetting->ai_status ?? 'disabled')) }}</span></div>@if(($budSetting->ai_status ?? 'disabled') !== 'approved')<form method="post" action="{{ route('account-help.bud.ai.request') }}" class="mt-4">@csrf<button class="rounded-xl bg-violet-800 px-4 py-2 text-sm font-semibold text-white">Request Bud AI</button></form>@else<div class="mt-4 rounded-xl bg-white px-4 py-3 text-sm text-zinc-700">Approved cap: ${{ number_format(($budSetting->ai_monthly_budget_cents ?? 0) / 100, 2) }} per month. Provider activation is still required before usage begins.</div>@endif</section>
                <section class="rounded-3xl border border-zinc-200 bg-white p-5 shadow-sm"><h2 class="text-lg font-semibold">Send a support ticket</h2><form method="post" action="{{ route('account-help.store') }}" class="mt-4 space-y-3">@csrf<input name="subject" required maxlength="180" placeholder="A short, clear subject" class="w-full rounded-xl border-zinc-300 text-sm"><div class="grid grid-cols-2 gap-3"><select name="category" class="rounded-xl border-zinc-300 text-sm"><option value="help">Help</option><option value="bug">Something is broken</option><option value="billing">Billing</option><option value="feature">Feature idea</option><option value="account">Account</option></select><select name="priority" class="rounded-xl border-zinc-300 text-sm"><option value="normal">Normal</option><option value="high">High</option><option value="urgent">Urgent</option><option value="low">Low</option></select></div><textarea name="body" required rows="4" placeholder="What happened, what you expected, and what you need next." class="w-full rounded-xl border-zinc-300 text-sm"></textarea><button class="w-full rounded-xl bg-emerald-800 px-4 py-2.5 text-sm font-semibold text-white">Send to Everbranch</button></form></section>
            </div>
        </div>
    </div>
    <script>document.getElementById('ticket-search')?.addEventListener('input',e=>document.querySelectorAll('[data-ticket]').forEach(x=>x.hidden=!x.textContent.toLowerCase().includes(e.target.value.toLowerCase())));</script>
</x-app-layout>
