@php
    $selectedReminders = (array) old('reminders', ['service', 'seasonal']);
@endphp
<!DOCTYPE html>
<html lang="en">
<head>
    @include('partials.head', [
        'title' => 'Green Shield Pest Control | A fictional Everbranch demo',
        'description' => 'A fictional pest-control customer website demonstrating reminders, service requests, and route-aware field operations in Everbranch.',
    ])
    <style>
        :root { --ink:#123b32; --leaf:#18765c; --lime:#cde85f; --sand:#f8f5ed; --clay:#c86b48; --line:rgba(18,59,50,.13); }
        * { box-sizing:border-box; }
        body { margin:0; color:var(--ink); background:var(--sand); font-family:Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif; }
        a { color:inherit; }
        .gs-site { overflow:hidden; }
        .gs-site__wrap { width:min(1160px,calc(100% - 40px)); margin:0 auto; }
        .gs-site__notice { background:var(--ink); color:#dcebdd; font-size:12px; line-height:1.45; text-align:center; padding:9px 20px; }
        .gs-site__nav { min-height:82px; display:flex; align-items:center; justify-content:space-between; gap:24px; }
        .gs-site__brand { display:flex; align-items:center; gap:10px; font-weight:850; font-size:17px; text-decoration:none; letter-spacing:-.04em; }
        .gs-site__mark { width:36px; height:36px; border-radius:12px 12px 12px 4px; display:grid; place-items:center; background:var(--leaf); color:#fff; box-shadow:inset 0 -7px 0 rgba(0,0,0,.1); font-size:20px; }
        .gs-site__navlinks { display:flex; align-items:center; gap:22px; font-weight:700; font-size:14px; }
        .gs-site__navlinks a { text-decoration:none; }
        .gs-site__navlinks a:hover { color:var(--leaf); }
        .gs-site__button { display:inline-flex; align-items:center; justify-content:center; gap:8px; border:0; border-radius:999px; padding:13px 18px; font:inherit; font-weight:800; font-size:14px; text-decoration:none; cursor:pointer; background:var(--ink); color:#fff; box-shadow:0 10px 22px rgba(18,59,50,.16); transition:transform .18s ease,box-shadow .18s ease; }
        .gs-site__button:hover { transform:translateY(-2px); box-shadow:0 14px 28px rgba(18,59,50,.2); }
        .gs-site__button--lime { background:var(--lime); color:var(--ink); }
        .gs-site__button--line { background:transparent; border:1px solid var(--line); color:var(--ink); box-shadow:none; }
        .gs-site__hero { position:relative; min-height:555px; display:grid; align-items:center; padding:68px 0 76px; }
        .gs-site__hero:before { content:""; position:absolute; z-index:-2; inset:0; background:linear-gradient(118deg,#e9f0d6 0%,#f8f5ed 52%,#dce8cc 100%); }
        .gs-site__hero:after { content:""; position:absolute; z-index:-1; right:-85px; top:-100px; width:535px; height:535px; border-radius:44% 56% 41% 59%; background:radial-gradient(circle at 36% 35%,#f5fbcc 0 17%,transparent 17.5%),linear-gradient(135deg,#7cb28f,#356e5c); opacity:.88; transform:rotate(-10deg); }
        .gs-site__hero-grid { display:grid; grid-template-columns:minmax(0,1.05fr) minmax(280px,.75fr); gap:65px; align-items:end; }
        .gs-site__eyebrow { margin:0 0 15px; color:var(--leaf); text-transform:uppercase; letter-spacing:.15em; font-size:11px; font-weight:900; }
        .gs-site h1 { max-width:700px; margin:0; font-family:Fraunces,Georgia,serif; font-size:clamp(47px,6.5vw,80px); line-height:.94; letter-spacing:-.065em; font-weight:500; }
        .gs-site__lede { max-width:595px; margin:23px 0 27px; color:#547067; font-size:18px; line-height:1.6; }
        .gs-site__actions { display:flex; flex-wrap:wrap; gap:11px; }
        .gs-site__route-card { position:relative; border:1px solid rgba(255,255,255,.58); background:rgba(255,255,255,.83); border-radius:25px; padding:22px; box-shadow:0 23px 48px rgba(24,72,58,.16); backdrop-filter:blur(14px); }
        .gs-site__route-top { display:flex; align-items:center; justify-content:space-between; gap:12px; font-size:12px; font-weight:850; }
        .gs-site__live { display:inline-flex; align-items:center; gap:6px; color:#18765c; }
        .gs-site__live i { width:8px; height:8px; border-radius:50%; background:#4dbf6b; box-shadow:0 0 0 5px rgba(77,191,107,.16); }
        .gs-site__map { position:relative; height:185px; margin:18px 0; overflow:hidden; border-radius:17px; background:#dce8d2; }
        .gs-site__map:before,.gs-site__map:after { content:""; position:absolute; background:rgba(255,255,255,.55); border-radius:999px; transform:rotate(-34deg); }
        .gs-site__map:before { width:270px; height:24px; left:-35px; top:83px; }.gs-site__map:after { width:250px; height:18px; right:-35px; top:42px; transform:rotate(32deg); }
        .gs-site__route-line { position:absolute; left:36px; top:130px; width:220px; height:94px; border-top:4px dashed var(--clay); border-radius:60% 30% 0 0; transform:rotate(-28deg); }
        .gs-site__pin { position:absolute; display:grid; place-items:center; width:31px; height:31px; border-radius:50% 50% 50% 6px; background:var(--ink); color:#fff; font-size:12px; font-weight:900; transform:rotate(-45deg); box-shadow:0 5px 11px rgba(18,59,50,.22); }.gs-site__pin span { transform:rotate(45deg); }.gs-site__pin--one { left:39px; bottom:23px; }.gs-site__pin--two { left:130px; top:82px; }.gs-site__pin--three { right:30px; top:25px; background:var(--clay); }
        .gs-site__route-bottom { display:flex; justify-content:space-between; padding-top:14px; border-top:1px solid var(--line); color:#63766f; font-size:12px; }.gs-site__route-bottom strong { color:var(--ink); }
        .gs-site__proof { display:grid; grid-template-columns:repeat(3,1fr); border-bottom:1px solid var(--line); }.gs-site__proof div { padding:25px 8px; text-align:center; border-right:1px solid var(--line); }.gs-site__proof div:last-child { border:0; }.gs-site__proof b { display:block; font-family:Fraunces,Georgia,serif; font-size:31px; font-weight:500; letter-spacing:-.05em; }.gs-site__proof span { display:block; margin-top:5px; color:#66776f; font-size:12px; font-weight:700; }
        .gs-site__section { padding:92px 0; }.gs-site__section--white { background:#fff; }.gs-site__section--green { color:#fff; background:var(--ink); }.gs-site__section-heading { display:flex; justify-content:space-between; align-items:end; gap:30px; margin-bottom:36px; }.gs-site__section-heading h2 { max-width:660px; margin:0; font-family:Fraunces,Georgia,serif; font-size:clamp(35px,4vw,54px); font-weight:500; line-height:.98; letter-spacing:-.055em; }.gs-site__section-heading p { max-width:340px; margin:0; color:#63766f; font-size:15px; line-height:1.55; }.gs-site__section--green .gs-site__section-heading p { color:#b8d0c5; }
        .gs-site__feature-grid { display:grid; grid-template-columns:repeat(3,1fr); gap:17px; }.gs-site__feature { min-height:235px; padding:25px; border:1px solid var(--line); border-radius:20px; background:var(--sand); }.gs-site__feature-icon { display:grid; place-items:center; width:44px; height:44px; border-radius:14px; background:#e2efd5; font-size:21px; }.gs-site__feature h3 { margin:23px 0 9px; font-size:19px; letter-spacing:-.04em; }.gs-site__feature p { margin:0; color:#687a72; font-size:14px; line-height:1.55; }
        .gs-site__plans { display:grid; grid-template-columns:repeat(3,1fr); gap:17px; }.gs-site__plan { position:relative; padding:27px; border:1px solid rgba(255,255,255,.17); border-radius:21px; background:rgba(255,255,255,.055); }.gs-site__plan--featured { color:var(--ink); background:var(--lime); border-color:var(--lime); }.gs-site__plan span { font-size:11px; font-weight:900; text-transform:uppercase; letter-spacing:.13em; color:#acd8bd; }.gs-site__plan--featured span { color:#51743c; }.gs-site__plan h3 { margin:13px 0 8px; font-family:Fraunces,Georgia,serif; font-size:29px; font-weight:500; letter-spacing:-.05em; }.gs-site__plan p { margin:0; color:#c4d5cd; font-size:14px; line-height:1.55; }.gs-site__plan--featured p { color:#45613b; }.gs-site__plan ul { min-height:79px; padding:0; margin:21px 0; list-style:none; font-size:13px; line-height:1.8; }.gs-site__plan li:before { content:"✓"; margin-right:8px; color:var(--lime); font-weight:900; }.gs-site__plan--featured li:before { color:var(--leaf); }
        .gs-site__reminders { display:grid; grid-template-columns:minmax(0,.9fr) minmax(360px,1.1fr); gap:75px; align-items:start; }.gs-site__reminders-copy h2 { margin:0; font-family:Fraunces,Georgia,serif; font-size:clamp(39px,5vw,62px); line-height:.95; font-weight:500; letter-spacing:-.06em; }.gs-site__reminders-copy p { max-width:430px; color:#61746c; font-size:16px; line-height:1.62; }.gs-site__note { display:flex; gap:10px; margin-top:25px; padding:15px; border-radius:14px; background:#e8f2e1; color:#426153; font-size:12px; line-height:1.45; }.gs-site__note b { color:var(--leaf); }.gs-site__form { padding:28px; border:1px solid var(--line); border-radius:24px; background:#fff; box-shadow:0 18px 38px rgba(18,59,50,.08); }.gs-site__form h3 { margin:0; font-size:22px; letter-spacing:-.045em; }.gs-site__form p { margin:8px 0 18px; color:#687a72; font-size:13px; line-height:1.48; }.gs-site__form-grid { display:grid; grid-template-columns:1fr 1fr; gap:13px; }.gs-site__field { display:grid; gap:6px; color:#38544a; font-size:12px; font-weight:800; }.gs-site__field--wide { grid-column:1/-1; }.gs-site__field input,.gs-site__field select,.gs-site__field textarea { width:100%; border:1px solid #d9e1da; border-radius:11px; padding:11px 12px; color:var(--ink); background:#fcfdfb; font:inherit; font-size:14px; outline:0; }.gs-site__field textarea { min-height:78px; resize:vertical; }.gs-site__field input:focus,.gs-site__field select:focus,.gs-site__field textarea:focus { border-color:var(--leaf); box-shadow:0 0 0 3px rgba(24,118,92,.12); }.gs-site__checks { display:grid; gap:9px; margin:18px 0; }.gs-site__check { display:flex; align-items:flex-start; gap:9px; color:#536c62; font-size:13px; line-height:1.35; }.gs-site__check input { width:16px; height:16px; margin:1px 0 0; accent-color:var(--leaf); }.gs-site__form .gs-site__button { width:100%; }.gs-site__success { margin:0 0 17px; padding:14px; border-radius:12px; color:#236448; background:#e4f5dc; font-size:13px; line-height:1.45; }.gs-site__error { margin-top:5px; color:#bd3e25; font-size:11px; font-weight:700; }
        .gs-site__ready { display:grid; grid-template-columns:1fr 1fr; gap:20px; }.gs-site__ready-card { padding:30px; border-radius:23px; background:#e2edd6; }.gs-site__ready-card:last-child { color:#fff; background:#346c5a; }.gs-site__ready-card h3 { margin:0 0 13px; font-family:Fraunces,Georgia,serif; font-size:31px; letter-spacing:-.05em; font-weight:500; }.gs-site__ready-card p { margin:0; color:#577267; font-size:14px; line-height:1.55; }.gs-site__ready-card:last-child p { color:#c8ddd3; }.gs-site__ready-card a { display:inline-block; margin-top:18px; font-size:13px; font-weight:850; text-decoration-thickness:2px; text-underline-offset:4px; }
        .gs-site__footer { padding:42px 0; color:#c8d9d0; background:#0d2b24; }.gs-site__footer-row { display:flex; justify-content:space-between; gap:30px; align-items:start; }.gs-site__footer strong { color:#fff; }.gs-site__footer p { max-width:565px; margin:8px 0 0; font-size:12px; line-height:1.5; }.gs-site__footer a { color:#dff09b; font-size:13px; font-weight:800; }
        @media (max-width:850px) { .gs-site__hero-grid,.gs-site__reminders { grid-template-columns:1fr; gap:35px; }.gs-site__route-card { max-width:460px; }.gs-site__feature-grid,.gs-site__plans { grid-template-columns:1fr; }.gs-site__section-heading { align-items:start; flex-direction:column; }.gs-site__ready { grid-template-columns:1fr; } }
        @media (max-width:620px) { .gs-site__wrap { width:min(100% - 30px,1160px); }.gs-site__nav { min-height:69px; }.gs-site__navlinks { display:none; }.gs-site__hero { min-height:auto; padding:50px 0; }.gs-site__hero:after { width:310px; height:310px; right:-140px; top:-50px; }.gs-site__proof { grid-template-columns:1fr; }.gs-site__proof div { padding:15px; border-right:0; border-bottom:1px solid var(--line); }.gs-site__section { padding:62px 0; }.gs-site__form-grid { grid-template-columns:1fr; }.gs-site__field--wide { grid-column:auto; }.gs-site__footer-row { flex-direction:column; } }
    </style>
</head>
<body>
    <div class="gs-site">
        <div class="gs-site__notice">Fictional Green Shield Pest Control website · Demonstration only · No real services, reminders, or location data are provided from this page.</div>
        <header class="gs-site__wrap gs-site__nav">
            <a class="gs-site__brand" href="#top" aria-label="Green Shield Pest Control home"><span class="gs-site__mark" aria-hidden="true">✦</span><span>Green Shield<br>Pest Control</span></a>
            <nav class="gs-site__navlinks" aria-label="Primary navigation"><a href="#plans">Plans</a><a href="#how-it-works">How it works</a><a href="#reminders">Reminders</a></nav>
            <a class="gs-site__button" href="#reminders">Get pest-free updates <span aria-hidden="true">→</span></a>
        </header>

        <main id="top">
            <section class="gs-site__hero">
                <div class="gs-site__wrap gs-site__hero-grid">
                    <div><p class="gs-site__eyebrow">Charlotte homes & businesses</p><h1>Pest control that stays one step ahead.</h1><p class="gs-site__lede">Easy recurring protection, clearer service-day updates, and a team that remembers the little details around your property.</p><div class="gs-site__actions"><a class="gs-site__button" href="#plans">Explore protection plans</a><a class="gs-site__button gs-site__button--line" href="#reminders">Set my reminder preferences</a></div></div>
                    <aside class="gs-site__route-card" aria-label="Fictional service route illustration"><div class="gs-site__route-top"><span>Today’s service window</span><span class="gs-site__live"><i></i> On the route</span></div><div class="gs-site__map" aria-hidden="true"><span class="gs-site__route-line"></span><span class="gs-site__pin gs-site__pin--one"><span>1</span></span><span class="gs-site__pin gs-site__pin--two"><span>2</span></span><span class="gs-site__pin gs-site__pin--three"><span>3</span></span></div><div class="gs-site__route-bottom"><span><strong>Van 17</strong> · Bouncie linked</span><span>11:00–1:00 PM</span></div></aside>
                </div>
            </section>

            <section class="gs-site__wrap gs-site__proof" aria-label="Fictional business proof points"><div><b>4.9/5</b><span>fictional neighborhood rating</span></div><div><b>15 yrs</b><span>fictional local experience</span></div><div><b>1 clear plan</b><span>from first visit to next service</span></div></section>

            <section id="how-it-works" class="gs-site__section gs-site__wrap"><div class="gs-site__section-heading"><div><p class="gs-site__eyebrow">Designed around the customer</p><h2>Less wondering. More knowing what happens next.</h2></div><p>Every touchpoint is an opportunity to make recurring service feel reassuring instead of easy to forget.</p></div><div class="gs-site__feature-grid"><article class="gs-site__feature"><div class="gs-site__feature-icon" aria-hidden="true">◷</div><h3>Useful reminders</h3><p>Let customers choose service-day, seasonal pest, or mosquito-season updates that fit the protection they need.</p></article><article class="gs-site__feature"><div class="gs-site__feature-icon" aria-hidden="true">⌂</div><h3>Property context</h3><p>Gate access, pets, previous concerns, and prep notes can stay connected to the property—not lost in a call log.</p></article><article class="gs-site__feature"><div class="gs-site__feature-icon" aria-hidden="true">✓</div><h3>Clear service records</h3><p>After a visit, customers can receive a simple treatment summary, what to expect, and the next recommended step.</p></article></div></section>

            <section id="plans" class="gs-site__section gs-site__section--green"><div class="gs-site__wrap"><div class="gs-site__section-heading"><div><p class="gs-site__eyebrow" style="color:#cde85f">Fictional service plans</p><h2>Protection that can grow with the property.</h2></div><p>Use a simple plan page to move a customer from an immediate concern to dependable recurring care.</p></div><div class="gs-site__plans"><article class="gs-site__plan"><span>Start here</span><h3>Home Shield</h3><p>Reliable perimeter protection for the pests that try to make themselves at home.</p><ul><li>Quarterly exterior service</li><li>Easy callback request</li><li>Service-day updates</li></ul><a class="gs-site__button gs-site__button--line" href="#reminders">Request a plan</a></article><article class="gs-site__plan gs-site__plan--featured"><span>Seasonal favorite</span><h3>Yard + Mosquito</h3><p>Recurring protection for the places your family and friends actually spend time.</p><ul><li>Barrier application schedule</li><li>Seasonal timing alerts</li><li>Simple prep guidance</li></ul><a class="gs-site__button" href="#reminders">Choose reminders</a></article><article class="gs-site__plan"><span>For businesses</span><h3>Commercial Care</h3><p>Consistent visits, documented service, and site-specific details for a cleaner customer experience.</p><ul><li>Multi-location context</li><li>Service reporting</li><li>Priority issue requests</li></ul><a class="gs-site__button gs-site__button--line" href="#reminders">Talk to the team</a></article></div></div></section>

            <section id="reminders" class="gs-site__section gs-site__wrap"><div class="gs-site__reminders"><div class="gs-site__reminders-copy"><p class="gs-site__eyebrow">Pest prevention reminder sign-up</p><h2>Help customers stay ahead of the season.</h2><p>Give people a low-pressure way to tell the business which updates they would find useful. In a live rollout, this intake could begin a permission-based email or text journey.</p><div class="gs-site__note"><span aria-hidden="true">ⓘ</span><span><b>Demo safeguard.</b> This form stores a tenant-scoped fictional request only. It does not create a customer, consent record, automation, email, or text message.</span></div></div>
                    <form class="gs-site__form" method="POST" action="{{ route('platform.pest-control-website.reminders') }}">@csrf<input type="text" name="website" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-10000px" /><h3>Choose helpful updates</h3><p>Show the customer-facing collection point—not a generic “join our list” form.</p>@if(session('pest_reminder_status'))<div class="gs-site__success" role="status">{{ session('pest_reminder_status') }}</div>@endif<div class="gs-site__form-grid"><label class="gs-site__field">Name<input name="name" value="{{ old('name') }}" autocomplete="name" required placeholder="Taylor Morgan">@error('name')<span class="gs-site__error">{{ $message }}</span>@enderror</label><label class="gs-site__field">Email<input name="email" value="{{ old('email') }}" autocomplete="email" required placeholder="taylor@example.com">@error('email')<span class="gs-site__error">{{ $message }}</span>@enderror</label><label class="gs-site__field">Phone <small style="font-weight:600;color:#73877e">optional</small><input name="phone" value="{{ old('phone') }}" autocomplete="tel" placeholder="(704) 555-0123">@error('phone')<span class="gs-site__error">{{ $message }}</span>@enderror</label><label class="gs-site__field">Property<select name="property_type" required><option value="home" @selected(old('property_type') === 'home')>Home</option><option value="business" @selected(old('property_type') === 'business')>Business</option></select>@error('property_type')<span class="gs-site__error">{{ $message }}</span>@enderror</label><label class="gs-site__field gs-site__field--wide">Anything we should know? <small style="font-weight:600;color:#73877e">optional</small><textarea name="message" placeholder="Example: I want a spring mosquito reminder before backyard season.">{{ old('message') }}</textarea>@error('message')<span class="gs-site__error">{{ $message }}</span>@enderror</label></div><div class="gs-site__checks"><label class="gs-site__check"><input type="checkbox" name="reminders[]" value="service" @checked(in_array('service', $selectedReminders, true))><span>Service-day arrival and preparation reminders</span></label><label class="gs-site__check"><input type="checkbox" name="reminders[]" value="seasonal" @checked(in_array('seasonal', $selectedReminders, true))><span>Seasonal prevention check-ins</span></label><label class="gs-site__check"><input type="checkbox" name="reminders[]" value="mosquito" @checked(in_array('mosquito', $selectedReminders, true))><span>Mosquito-season planning reminders</span></label></div>@error('reminders')<p class="gs-site__error">{{ $message }}</p>@enderror<button class="gs-site__button" type="submit">Save fictional preferences <span aria-hidden="true">→</span></button></form>
                </div>
            </section>

            <section class="gs-site__section gs-site__wrap" style="padding-top:0"><div class="gs-site__ready"><article class="gs-site__ready-card"><p class="gs-site__eyebrow">Before service</p><h3>A little preparation goes a long way.</h3><p>Publish the quick things a customer can do before an indoor treatment: clear access, protect food surfaces, and share pet details.</p><a href="#reminders">See the fictional prep flow →</a></article><article class="gs-site__ready-card"><p class="gs-site__eyebrow" style="color:#cde85f">For the operations team</p><h3>Bouncie makes route context useful.</h3><p>Company-van hardware can make dispatch more informed while remaining separate from on-duty phone sharing and personal location.</p><a href="{{ route('platform.pest-control-fleet-demo') }}">Open the Bouncie workspace demo →</a></article></div></section>
        </main>

        <footer class="gs-site__footer"><div class="gs-site__wrap gs-site__footer-row"><div><strong>Green Shield Pest Control</strong><p>This is a fictional Everbranch demonstration. It illustrates how a pest-control company’s website, customer requests, service work, and Bouncie-aware dispatch can feel connected.</p></div><a href="{{ route('platform.pest-control-fleet-demo') }}">Explore the operations workspace →</a></div></footer>
    </div>
</body>
</html>
